// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/menta2k/iris/backend/app/admin/service/internal/data/ent/acmeaccount"
)

// AcmeAccountCreate is the builder for creating a AcmeAccount entity.
type AcmeAccountCreate struct {
	config
	mutation *AcmeAccountMutation
	hooks    []Hook
}

// SetEmail sets the "email" field.
func (_c *AcmeAccountCreate) SetEmail(v string) *AcmeAccountCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetServerURL sets the "server_url" field.
func (_c *AcmeAccountCreate) SetServerURL(v string) *AcmeAccountCreate {
	_c.mutation.SetServerURL(v)
	return _c
}

// SetRegistrationJSON sets the "registration_json" field.
func (_c *AcmeAccountCreate) SetRegistrationJSON(v string) *AcmeAccountCreate {
	_c.mutation.SetRegistrationJSON(v)
	return _c
}

// SetNillableRegistrationJSON sets the "registration_json" field if the given value is not nil.
func (_c *AcmeAccountCreate) SetNillableRegistrationJSON(v *string) *AcmeAccountCreate {
	if v != nil {
		_c.SetRegistrationJSON(*v)
	}
	return _c
}

// SetPrivateKeyPem sets the "private_key_pem" field.
func (_c *AcmeAccountCreate) SetPrivateKeyPem(v string) *AcmeAccountCreate {
	_c.mutation.SetPrivateKeyPem(v)
	return _c
}

// SetNillablePrivateKeyPem sets the "private_key_pem" field if the given value is not nil.
func (_c *AcmeAccountCreate) SetNillablePrivateKeyPem(v *string) *AcmeAccountCreate {
	if v != nil {
		_c.SetPrivateKeyPem(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AcmeAccountCreate) SetCreatedAt(v time.Time) *AcmeAccountCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AcmeAccountCreate) SetNillableCreatedAt(v *time.Time) *AcmeAccountCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AcmeAccountCreate) SetUpdatedAt(v time.Time) *AcmeAccountCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AcmeAccountCreate) SetNillableUpdatedAt(v *time.Time) *AcmeAccountCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AcmeAccountCreate) SetID(v int) *AcmeAccountCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *AcmeAccountCreate) SetNillableID(v *int) *AcmeAccountCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the AcmeAccountMutation object of the builder.
func (_c *AcmeAccountCreate) Mutation() *AcmeAccountMutation {
	return _c.mutation
}

// Save creates the AcmeAccount in the database.
func (_c *AcmeAccountCreate) Save(ctx context.Context) (*AcmeAccount, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AcmeAccountCreate) SaveX(ctx context.Context) *AcmeAccount {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AcmeAccountCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AcmeAccountCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AcmeAccountCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := acmeaccount.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := acmeaccount.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := acmeaccount.DefaultID
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AcmeAccountCreate) check() error {
	if _, ok := _c.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "AcmeAccount.email"`)}
	}
	if v, ok := _c.mutation.Email(); ok {
		if err := acmeaccount.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "AcmeAccount.email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ServerURL(); !ok {
		return &ValidationError{Name: "server_url", err: errors.New(`ent: missing required field "AcmeAccount.server_url"`)}
	}
	if v, ok := _c.mutation.ServerURL(); ok {
		if err := acmeaccount.ServerURLValidator(v); err != nil {
			return &ValidationError{Name: "server_url", err: fmt.Errorf(`ent: validator failed for field "AcmeAccount.server_url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AcmeAccount.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AcmeAccount.updated_at"`)}
	}
	return nil
}

func (_c *AcmeAccountCreate) sqlSave(ctx context.Context) (*AcmeAccount, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AcmeAccountCreate) createSpec() (*AcmeAccount, *sqlgraph.CreateSpec) {
	var (
		_node = &AcmeAccount{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(acmeaccount.Table, sqlgraph.NewFieldSpec(acmeaccount.FieldID, field.TypeInt))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(acmeaccount.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := _c.mutation.ServerURL(); ok {
		_spec.SetField(acmeaccount.FieldServerURL, field.TypeString, value)
		_node.ServerURL = value
	}
	if value, ok := _c.mutation.RegistrationJSON(); ok {
		_spec.SetField(acmeaccount.FieldRegistrationJSON, field.TypeString, value)
		_node.RegistrationJSON = value
	}
	if value, ok := _c.mutation.PrivateKeyPem(); ok {
		_spec.SetField(acmeaccount.FieldPrivateKeyPem, field.TypeString, value)
		_node.PrivateKeyPem = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(acmeaccount.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(acmeaccount.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// AcmeAccountCreateBulk is the builder for creating many AcmeAccount entities in bulk.
type AcmeAccountCreateBulk struct {
	config
	err      error
	builders []*AcmeAccountCreate
}

// Save creates the AcmeAccount entities in the database.
func (_c *AcmeAccountCreateBulk) Save(ctx context.Context) ([]*AcmeAccount, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AcmeAccount, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AcmeAccountMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AcmeAccountCreateBulk) SaveX(ctx context.Context) []*AcmeAccount {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AcmeAccountCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AcmeAccountCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
