// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/menta2k/iris/backend/app/admin/service/internal/data/ent/globalsettings"
)

// GlobalSettingsCreate is the builder for creating a GlobalSettings entity.
type GlobalSettingsCreate struct {
	config
	mutation *GlobalSettingsMutation
	hooks    []Hook
}

// SetKumoHTTPListen sets the "kumo_http_listen" field.
func (_c *GlobalSettingsCreate) SetKumoHTTPListen(v string) *GlobalSettingsCreate {
	_c.mutation.SetKumoHTTPListen(v)
	return _c
}

// SetNillableKumoHTTPListen sets the "kumo_http_listen" field if the given value is not nil.
func (_c *GlobalSettingsCreate) SetNillableKumoHTTPListen(v *string) *GlobalSettingsCreate {
	if v != nil {
		_c.SetKumoHTTPListen(*v)
	}
	return _c
}

// SetEsmtpListenAddr sets the "esmtp_listen_addr" field.
func (_c *GlobalSettingsCreate) SetEsmtpListenAddr(v string) *GlobalSettingsCreate {
	_c.mutation.SetEsmtpListenAddr(v)
	return _c
}

// SetNillableEsmtpListenAddr sets the "esmtp_listen_addr" field if the given value is not nil.
func (_c *GlobalSettingsCreate) SetNillableEsmtpListenAddr(v *string) *GlobalSettingsCreate {
	if v != nil {
		_c.SetEsmtpListenAddr(*v)
	}
	return _c
}

// SetEsmtpRelayHosts sets the "esmtp_relay_hosts" field.
func (_c *GlobalSettingsCreate) SetEsmtpRelayHosts(v []string) *GlobalSettingsCreate {
	_c.mutation.SetEsmtpRelayHosts(v)
	return _c
}

// SetHTTPTrustedHosts sets the "http_trusted_hosts" field.
func (_c *GlobalSettingsCreate) SetHTTPTrustedHosts(v []string) *GlobalSettingsCreate {
	_c.mutation.SetHTTPTrustedHosts(v)
	return _c
}

// SetBounceDomain sets the "bounce_domain" field.
func (_c *GlobalSettingsCreate) SetBounceDomain(v string) *GlobalSettingsCreate {
	_c.mutation.SetBounceDomain(v)
	return _c
}

// SetNillableBounceDomain sets the "bounce_domain" field if the given value is not nil.
func (_c *GlobalSettingsCreate) SetNillableBounceDomain(v *string) *GlobalSettingsCreate {
	if v != nil {
		_c.SetBounceDomain(*v)
	}
	return _c
}

// SetBounceSenderDomains sets the "bounce_sender_domains" field.
func (_c *GlobalSettingsCreate) SetBounceSenderDomains(v []string) *GlobalSettingsCreate {
	_c.mutation.SetBounceSenderDomains(v)
	return _c
}

// SetBouncePrefix sets the "bounce_prefix" field.
func (_c *GlobalSettingsCreate) SetBouncePrefix(v string) *GlobalSettingsCreate {
	_c.mutation.SetBouncePrefix(v)
	return _c
}

// SetNillableBouncePrefix sets the "bounce_prefix" field if the given value is not nil.
func (_c *GlobalSettingsCreate) SetNillableBouncePrefix(v *string) *GlobalSettingsCreate {
	if v != nil {
		_c.SetBouncePrefix(*v)
	}
	return _c
}

// SetMailClassHeader sets the "mail_class_header" field.
func (_c *GlobalSettingsCreate) SetMailClassHeader(v string) *GlobalSettingsCreate {
	_c.mutation.SetMailClassHeader(v)
	return _c
}

// SetNillableMailClassHeader sets the "mail_class_header" field if the given value is not nil.
func (_c *GlobalSettingsCreate) SetNillableMailClassHeader(v *string) *GlobalSettingsCreate {
	if v != nil {
		_c.SetMailClassHeader(*v)
	}
	return _c
}

// SetEgressEhloDomain sets the "egress_ehlo_domain" field.
func (_c *GlobalSettingsCreate) SetEgressEhloDomain(v string) *GlobalSettingsCreate {
	_c.mutation.SetEgressEhloDomain(v)
	return _c
}

// SetNillableEgressEhloDomain sets the "egress_ehlo_domain" field if the given value is not nil.
func (_c *GlobalSettingsCreate) SetNillableEgressEhloDomain(v *string) *GlobalSettingsCreate {
	if v != nil {
		_c.SetEgressEhloDomain(*v)
	}
	return _c
}

// SetEgressRetryInterval sets the "egress_retry_interval" field.
func (_c *GlobalSettingsCreate) SetEgressRetryInterval(v string) *GlobalSettingsCreate {
	_c.mutation.SetEgressRetryInterval(v)
	return _c
}

// SetNillableEgressRetryInterval sets the "egress_retry_interval" field if the given value is not nil.
func (_c *GlobalSettingsCreate) SetNillableEgressRetryInterval(v *string) *GlobalSettingsCreate {
	if v != nil {
		_c.SetEgressRetryInterval(*v)
	}
	return _c
}

// SetEgressMaxRetryInterval sets the "egress_max_retry_interval" field.
func (_c *GlobalSettingsCreate) SetEgressMaxRetryInterval(v string) *GlobalSettingsCreate {
	_c.mutation.SetEgressMaxRetryInterval(v)
	return _c
}

// SetNillableEgressMaxRetryInterval sets the "egress_max_retry_interval" field if the given value is not nil.
func (_c *GlobalSettingsCreate) SetNillableEgressMaxRetryInterval(v *string) *GlobalSettingsCreate {
	if v != nil {
		_c.SetEgressMaxRetryInterval(*v)
	}
	return _c
}

// SetEgressMaxAge sets the "egress_max_age" field.
func (_c *GlobalSettingsCreate) SetEgressMaxAge(v string) *GlobalSettingsCreate {
	_c.mutation.SetEgressMaxAge(v)
	return _c
}

// SetNillableEgressMaxAge sets the "egress_max_age" field if the given value is not nil.
func (_c *GlobalSettingsCreate) SetNillableEgressMaxAge(v *string) *GlobalSettingsCreate {
	if v != nil {
		_c.SetEgressMaxAge(*v)
	}
	return _c
}

// SetRspamdMode sets the "rspamd_mode" field.
func (_c *GlobalSettingsCreate) SetRspamdMode(v string) *GlobalSettingsCreate {
	_c.mutation.SetRspamdMode(v)
	return _c
}

// SetNillableRspamdMode sets the "rspamd_mode" field if the given value is not nil.
func (_c *GlobalSettingsCreate) SetNillableRspamdMode(v *string) *GlobalSettingsCreate {
	if v != nil {
		_c.SetRspamdMode(*v)
	}
	return _c
}

// SetRspamdURL sets the "rspamd_url" field.
func (_c *GlobalSettingsCreate) SetRspamdURL(v string) *GlobalSettingsCreate {
	_c.mutation.SetRspamdURL(v)
	return _c
}

// SetNillableRspamdURL sets the "rspamd_url" field if the given value is not nil.
func (_c *GlobalSettingsCreate) SetNillableRspamdURL(v *string) *GlobalSettingsCreate {
	if v != nil {
		_c.SetRspamdURL(*v)
	}
	return _c
}

// SetHTTPSListen sets the "https_listen" field.
func (_c *GlobalSettingsCreate) SetHTTPSListen(v string) *GlobalSettingsCreate {
	_c.mutation.SetHTTPSListen(v)
	return _c
}

// SetNillableHTTPSListen sets the "https_listen" field if the given value is not nil.
func (_c *GlobalSettingsCreate) SetNillableHTTPSListen(v *string) *GlobalSettingsCreate {
	if v != nil {
		_c.SetHTTPSListen(*v)
	}
	return _c
}

// SetHTTPSCertPemPath sets the "https_cert_pem_path" field.
func (_c *GlobalSettingsCreate) SetHTTPSCertPemPath(v string) *GlobalSettingsCreate {
	_c.mutation.SetHTTPSCertPemPath(v)
	return _c
}

// SetNillableHTTPSCertPemPath sets the "https_cert_pem_path" field if the given value is not nil.
func (_c *GlobalSettingsCreate) SetNillableHTTPSCertPemPath(v *string) *GlobalSettingsCreate {
	if v != nil {
		_c.SetHTTPSCertPemPath(*v)
	}
	return _c
}

// SetHTTPSKeyPemPath sets the "https_key_pem_path" field.
func (_c *GlobalSettingsCreate) SetHTTPSKeyPemPath(v string) *GlobalSettingsCreate {
	_c.mutation.SetHTTPSKeyPemPath(v)
	return _c
}

// SetNillableHTTPSKeyPemPath sets the "https_key_pem_path" field if the given value is not nil.
func (_c *GlobalSettingsCreate) SetNillableHTTPSKeyPemPath(v *string) *GlobalSettingsCreate {
	if v != nil {
		_c.SetHTTPSKeyPemPath(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *GlobalSettingsCreate) SetUpdatedAt(v time.Time) *GlobalSettingsCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *GlobalSettingsCreate) SetNillableUpdatedAt(v *time.Time) *GlobalSettingsCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *GlobalSettingsCreate) SetUpdatedBy(v string) *GlobalSettingsCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *GlobalSettingsCreate) SetNillableUpdatedBy(v *string) *GlobalSettingsCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *GlobalSettingsCreate) SetID(v int) *GlobalSettingsCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *GlobalSettingsCreate) SetNillableID(v *int) *GlobalSettingsCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the GlobalSettingsMutation object of the builder.
func (_c *GlobalSettingsCreate) Mutation() *GlobalSettingsMutation {
	return _c.mutation
}

// Save creates the GlobalSettings in the database.
func (_c *GlobalSettingsCreate) Save(ctx context.Context) (*GlobalSettings, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *GlobalSettingsCreate) SaveX(ctx context.Context) *GlobalSettings {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GlobalSettingsCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GlobalSettingsCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *GlobalSettingsCreate) defaults() {
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := globalsettings.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := globalsettings.DefaultID
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *GlobalSettingsCreate) check() error {
	if v, ok := _c.mutation.KumoHTTPListen(); ok {
		if err := globalsettings.KumoHTTPListenValidator(v); err != nil {
			return &ValidationError{Name: "kumo_http_listen", err: fmt.Errorf(`ent: validator failed for field "GlobalSettings.kumo_http_listen": %w`, err)}
		}
	}
	if v, ok := _c.mutation.EsmtpListenAddr(); ok {
		if err := globalsettings.EsmtpListenAddrValidator(v); err != nil {
			return &ValidationError{Name: "esmtp_listen_addr", err: fmt.Errorf(`ent: validator failed for field "GlobalSettings.esmtp_listen_addr": %w`, err)}
		}
	}
	if v, ok := _c.mutation.BounceDomain(); ok {
		if err := globalsettings.BounceDomainValidator(v); err != nil {
			return &ValidationError{Name: "bounce_domain", err: fmt.Errorf(`ent: validator failed for field "GlobalSettings.bounce_domain": %w`, err)}
		}
	}
	if v, ok := _c.mutation.BouncePrefix(); ok {
		if err := globalsettings.BouncePrefixValidator(v); err != nil {
			return &ValidationError{Name: "bounce_prefix", err: fmt.Errorf(`ent: validator failed for field "GlobalSettings.bounce_prefix": %w`, err)}
		}
	}
	if v, ok := _c.mutation.MailClassHeader(); ok {
		if err := globalsettings.MailClassHeaderValidator(v); err != nil {
			return &ValidationError{Name: "mail_class_header", err: fmt.Errorf(`ent: validator failed for field "GlobalSettings.mail_class_header": %w`, err)}
		}
	}
	if v, ok := _c.mutation.EgressEhloDomain(); ok {
		if err := globalsettings.EgressEhloDomainValidator(v); err != nil {
			return &ValidationError{Name: "egress_ehlo_domain", err: fmt.Errorf(`ent: validator failed for field "GlobalSettings.egress_ehlo_domain": %w`, err)}
		}
	}
	if v, ok := _c.mutation.EgressRetryInterval(); ok {
		if err := globalsettings.EgressRetryIntervalValidator(v); err != nil {
			return &ValidationError{Name: "egress_retry_interval", err: fmt.Errorf(`ent: validator failed for field "GlobalSettings.egress_retry_interval": %w`, err)}
		}
	}
	if v, ok := _c.mutation.EgressMaxRetryInterval(); ok {
		if err := globalsettings.EgressMaxRetryIntervalValidator(v); err != nil {
			return &ValidationError{Name: "egress_max_retry_interval", err: fmt.Errorf(`ent: validator failed for field "GlobalSettings.egress_max_retry_interval": %w`, err)}
		}
	}
	if v, ok := _c.mutation.EgressMaxAge(); ok {
		if err := globalsettings.EgressMaxAgeValidator(v); err != nil {
			return &ValidationError{Name: "egress_max_age", err: fmt.Errorf(`ent: validator failed for field "GlobalSettings.egress_max_age": %w`, err)}
		}
	}
	if v, ok := _c.mutation.RspamdMode(); ok {
		if err := globalsettings.RspamdModeValidator(v); err != nil {
			return &ValidationError{Name: "rspamd_mode", err: fmt.Errorf(`ent: validator failed for field "GlobalSettings.rspamd_mode": %w`, err)}
		}
	}
	if v, ok := _c.mutation.RspamdURL(); ok {
		if err := globalsettings.RspamdURLValidator(v); err != nil {
			return &ValidationError{Name: "rspamd_url", err: fmt.Errorf(`ent: validator failed for field "GlobalSettings.rspamd_url": %w`, err)}
		}
	}
	if v, ok := _c.mutation.HTTPSListen(); ok {
		if err := globalsettings.HTTPSListenValidator(v); err != nil {
			return &ValidationError{Name: "https_listen", err: fmt.Errorf(`ent: validator failed for field "GlobalSettings.https_listen": %w`, err)}
		}
	}
	if v, ok := _c.mutation.HTTPSCertPemPath(); ok {
		if err := globalsettings.HTTPSCertPemPathValidator(v); err != nil {
			return &ValidationError{Name: "https_cert_pem_path", err: fmt.Errorf(`ent: validator failed for field "GlobalSettings.https_cert_pem_path": %w`, err)}
		}
	}
	if v, ok := _c.mutation.HTTPSKeyPemPath(); ok {
		if err := globalsettings.HTTPSKeyPemPathValidator(v); err != nil {
			return &ValidationError{Name: "https_key_pem_path", err: fmt.Errorf(`ent: validator failed for field "GlobalSettings.https_key_pem_path": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "GlobalSettings.updated_at"`)}
	}
	if v, ok := _c.mutation.UpdatedBy(); ok {
		if err := globalsettings.UpdatedByValidator(v); err != nil {
			return &ValidationError{Name: "updated_by", err: fmt.Errorf(`ent: validator failed for field "GlobalSettings.updated_by": %w`, err)}
		}
	}
	return nil
}

func (_c *GlobalSettingsCreate) sqlSave(ctx context.Context) (*GlobalSettings, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *GlobalSettingsCreate) createSpec() (*GlobalSettings, *sqlgraph.CreateSpec) {
	var (
		_node = &GlobalSettings{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(globalsettings.Table, sqlgraph.NewFieldSpec(globalsettings.FieldID, field.TypeInt))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.KumoHTTPListen(); ok {
		_spec.SetField(globalsettings.FieldKumoHTTPListen, field.TypeString, value)
		_node.KumoHTTPListen = value
	}
	if value, ok := _c.mutation.EsmtpListenAddr(); ok {
		_spec.SetField(globalsettings.FieldEsmtpListenAddr, field.TypeString, value)
		_node.EsmtpListenAddr = value
	}
	if value, ok := _c.mutation.EsmtpRelayHosts(); ok {
		_spec.SetField(globalsettings.FieldEsmtpRelayHosts, field.TypeJSON, value)
		_node.EsmtpRelayHosts = value
	}
	if value, ok := _c.mutation.HTTPTrustedHosts(); ok {
		_spec.SetField(globalsettings.FieldHTTPTrustedHosts, field.TypeJSON, value)
		_node.HTTPTrustedHosts = value
	}
	if value, ok := _c.mutation.BounceDomain(); ok {
		_spec.SetField(globalsettings.FieldBounceDomain, field.TypeString, value)
		_node.BounceDomain = value
	}
	if value, ok := _c.mutation.BounceSenderDomains(); ok {
		_spec.SetField(globalsettings.FieldBounceSenderDomains, field.TypeJSON, value)
		_node.BounceSenderDomains = value
	}
	if value, ok := _c.mutation.BouncePrefix(); ok {
		_spec.SetField(globalsettings.FieldBouncePrefix, field.TypeString, value)
		_node.BouncePrefix = value
	}
	if value, ok := _c.mutation.MailClassHeader(); ok {
		_spec.SetField(globalsettings.FieldMailClassHeader, field.TypeString, value)
		_node.MailClassHeader = value
	}
	if value, ok := _c.mutation.EgressEhloDomain(); ok {
		_spec.SetField(globalsettings.FieldEgressEhloDomain, field.TypeString, value)
		_node.EgressEhloDomain = value
	}
	if value, ok := _c.mutation.EgressRetryInterval(); ok {
		_spec.SetField(globalsettings.FieldEgressRetryInterval, field.TypeString, value)
		_node.EgressRetryInterval = value
	}
	if value, ok := _c.mutation.EgressMaxRetryInterval(); ok {
		_spec.SetField(globalsettings.FieldEgressMaxRetryInterval, field.TypeString, value)
		_node.EgressMaxRetryInterval = value
	}
	if value, ok := _c.mutation.EgressMaxAge(); ok {
		_spec.SetField(globalsettings.FieldEgressMaxAge, field.TypeString, value)
		_node.EgressMaxAge = value
	}
	if value, ok := _c.mutation.RspamdMode(); ok {
		_spec.SetField(globalsettings.FieldRspamdMode, field.TypeString, value)
		_node.RspamdMode = value
	}
	if value, ok := _c.mutation.RspamdURL(); ok {
		_spec.SetField(globalsettings.FieldRspamdURL, field.TypeString, value)
		_node.RspamdURL = value
	}
	if value, ok := _c.mutation.HTTPSListen(); ok {
		_spec.SetField(globalsettings.FieldHTTPSListen, field.TypeString, value)
		_node.HTTPSListen = value
	}
	if value, ok := _c.mutation.HTTPSCertPemPath(); ok {
		_spec.SetField(globalsettings.FieldHTTPSCertPemPath, field.TypeString, value)
		_node.HTTPSCertPemPath = value
	}
	if value, ok := _c.mutation.HTTPSKeyPemPath(); ok {
		_spec.SetField(globalsettings.FieldHTTPSKeyPemPath, field.TypeString, value)
		_node.HTTPSKeyPemPath = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(globalsettings.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(globalsettings.FieldUpdatedBy, field.TypeString, value)
		_node.UpdatedBy = value
	}
	return _node, _spec
}

// GlobalSettingsCreateBulk is the builder for creating many GlobalSettings entities in bulk.
type GlobalSettingsCreateBulk struct {
	config
	err      error
	builders []*GlobalSettingsCreate
}

// Save creates the GlobalSettings entities in the database.
func (_c *GlobalSettingsCreateBulk) Save(ctx context.Context) ([]*GlobalSettings, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*GlobalSettings, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GlobalSettingsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *GlobalSettingsCreateBulk) SaveX(ctx context.Context) []*GlobalSettings {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GlobalSettingsCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GlobalSettingsCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
