// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/menta2k/iris/backend/app/admin/service/internal/data/ent/globalsettings"
)

// GlobalSettings is the model entity for the GlobalSettings schema.
type GlobalSettings struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// KumoHTTPListen holds the value of the "kumo_http_listen" field.
	KumoHTTPListen string `json:"kumo_http_listen,omitempty"`
	// EsmtpListenAddr holds the value of the "esmtp_listen_addr" field.
	EsmtpListenAddr string `json:"esmtp_listen_addr,omitempty"`
	// EsmtpRelayHosts holds the value of the "esmtp_relay_hosts" field.
	EsmtpRelayHosts []string `json:"esmtp_relay_hosts,omitempty"`
	// HTTPTrustedHosts holds the value of the "http_trusted_hosts" field.
	HTTPTrustedHosts []string `json:"http_trusted_hosts,omitempty"`
	// BounceDomain holds the value of the "bounce_domain" field.
	BounceDomain string `json:"bounce_domain,omitempty"`
	// BounceSenderDomains holds the value of the "bounce_sender_domains" field.
	BounceSenderDomains []string `json:"bounce_sender_domains,omitempty"`
	// BouncePrefix holds the value of the "bounce_prefix" field.
	BouncePrefix string `json:"bounce_prefix,omitempty"`
	// MailClassHeader holds the value of the "mail_class_header" field.
	MailClassHeader string `json:"mail_class_header,omitempty"`
	// EgressEhloDomain holds the value of the "egress_ehlo_domain" field.
	EgressEhloDomain string `json:"egress_ehlo_domain,omitempty"`
	// EgressRetryInterval holds the value of the "egress_retry_interval" field.
	EgressRetryInterval string `json:"egress_retry_interval,omitempty"`
	// EgressMaxRetryInterval holds the value of the "egress_max_retry_interval" field.
	EgressMaxRetryInterval string `json:"egress_max_retry_interval,omitempty"`
	// EgressMaxAge holds the value of the "egress_max_age" field.
	EgressMaxAge string `json:"egress_max_age,omitempty"`
	// HTTPSListen holds the value of the "https_listen" field.
	HTTPSListen string `json:"https_listen,omitempty"`
	// HTTPSCertPemPath holds the value of the "https_cert_pem_path" field.
	HTTPSCertPemPath string `json:"https_cert_pem_path,omitempty"`
	// HTTPSKeyPemPath holds the value of the "https_key_pem_path" field.
	HTTPSKeyPemPath string `json:"https_key_pem_path,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// UpdatedBy holds the value of the "updated_by" field.
	UpdatedBy    string `json:"updated_by,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*GlobalSettings) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case globalsettings.FieldEsmtpRelayHosts, globalsettings.FieldHTTPTrustedHosts, globalsettings.FieldBounceSenderDomains:
			values[i] = new([]byte)
		case globalsettings.FieldID:
			values[i] = new(sql.NullInt64)
		case globalsettings.FieldKumoHTTPListen, globalsettings.FieldEsmtpListenAddr, globalsettings.FieldBounceDomain, globalsettings.FieldBouncePrefix, globalsettings.FieldMailClassHeader, globalsettings.FieldEgressEhloDomain, globalsettings.FieldEgressRetryInterval, globalsettings.FieldEgressMaxRetryInterval, globalsettings.FieldEgressMaxAge, globalsettings.FieldHTTPSListen, globalsettings.FieldHTTPSCertPemPath, globalsettings.FieldHTTPSKeyPemPath, globalsettings.FieldUpdatedBy:
			values[i] = new(sql.NullString)
		case globalsettings.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the GlobalSettings fields.
func (_m *GlobalSettings) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case globalsettings.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case globalsettings.FieldKumoHTTPListen:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field kumo_http_listen", values[i])
			} else if value.Valid {
				_m.KumoHTTPListen = value.String
			}
		case globalsettings.FieldEsmtpListenAddr:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field esmtp_listen_addr", values[i])
			} else if value.Valid {
				_m.EsmtpListenAddr = value.String
			}
		case globalsettings.FieldEsmtpRelayHosts:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field esmtp_relay_hosts", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.EsmtpRelayHosts); err != nil {
					return fmt.Errorf("unmarshal field esmtp_relay_hosts: %w", err)
				}
			}
		case globalsettings.FieldHTTPTrustedHosts:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field http_trusted_hosts", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.HTTPTrustedHosts); err != nil {
					return fmt.Errorf("unmarshal field http_trusted_hosts: %w", err)
				}
			}
		case globalsettings.FieldBounceDomain:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field bounce_domain", values[i])
			} else if value.Valid {
				_m.BounceDomain = value.String
			}
		case globalsettings.FieldBounceSenderDomains:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field bounce_sender_domains", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.BounceSenderDomains); err != nil {
					return fmt.Errorf("unmarshal field bounce_sender_domains: %w", err)
				}
			}
		case globalsettings.FieldBouncePrefix:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field bounce_prefix", values[i])
			} else if value.Valid {
				_m.BouncePrefix = value.String
			}
		case globalsettings.FieldMailClassHeader:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field mail_class_header", values[i])
			} else if value.Valid {
				_m.MailClassHeader = value.String
			}
		case globalsettings.FieldEgressEhloDomain:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field egress_ehlo_domain", values[i])
			} else if value.Valid {
				_m.EgressEhloDomain = value.String
			}
		case globalsettings.FieldEgressRetryInterval:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field egress_retry_interval", values[i])
			} else if value.Valid {
				_m.EgressRetryInterval = value.String
			}
		case globalsettings.FieldEgressMaxRetryInterval:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field egress_max_retry_interval", values[i])
			} else if value.Valid {
				_m.EgressMaxRetryInterval = value.String
			}
		case globalsettings.FieldEgressMaxAge:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field egress_max_age", values[i])
			} else if value.Valid {
				_m.EgressMaxAge = value.String
			}
		case globalsettings.FieldHTTPSListen:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field https_listen", values[i])
			} else if value.Valid {
				_m.HTTPSListen = value.String
			}
		case globalsettings.FieldHTTPSCertPemPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field https_cert_pem_path", values[i])
			} else if value.Valid {
				_m.HTTPSCertPemPath = value.String
			}
		case globalsettings.FieldHTTPSKeyPemPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field https_key_pem_path", values[i])
			} else if value.Valid {
				_m.HTTPSKeyPemPath = value.String
			}
		case globalsettings.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case globalsettings.FieldUpdatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value.Valid {
				_m.UpdatedBy = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the GlobalSettings.
// This includes values selected through modifiers, order, etc.
func (_m *GlobalSettings) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this GlobalSettings.
// Note that you need to call GlobalSettings.Unwrap() before calling this method if this GlobalSettings
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *GlobalSettings) Update() *GlobalSettingsUpdateOne {
	return NewGlobalSettingsClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the GlobalSettings entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *GlobalSettings) Unwrap() *GlobalSettings {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: GlobalSettings is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *GlobalSettings) String() string {
	var builder strings.Builder
	builder.WriteString("GlobalSettings(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("kumo_http_listen=")
	builder.WriteString(_m.KumoHTTPListen)
	builder.WriteString(", ")
	builder.WriteString("esmtp_listen_addr=")
	builder.WriteString(_m.EsmtpListenAddr)
	builder.WriteString(", ")
	builder.WriteString("esmtp_relay_hosts=")
	builder.WriteString(fmt.Sprintf("%v", _m.EsmtpRelayHosts))
	builder.WriteString(", ")
	builder.WriteString("http_trusted_hosts=")
	builder.WriteString(fmt.Sprintf("%v", _m.HTTPTrustedHosts))
	builder.WriteString(", ")
	builder.WriteString("bounce_domain=")
	builder.WriteString(_m.BounceDomain)
	builder.WriteString(", ")
	builder.WriteString("bounce_sender_domains=")
	builder.WriteString(fmt.Sprintf("%v", _m.BounceSenderDomains))
	builder.WriteString(", ")
	builder.WriteString("bounce_prefix=")
	builder.WriteString(_m.BouncePrefix)
	builder.WriteString(", ")
	builder.WriteString("mail_class_header=")
	builder.WriteString(_m.MailClassHeader)
	builder.WriteString(", ")
	builder.WriteString("egress_ehlo_domain=")
	builder.WriteString(_m.EgressEhloDomain)
	builder.WriteString(", ")
	builder.WriteString("egress_retry_interval=")
	builder.WriteString(_m.EgressRetryInterval)
	builder.WriteString(", ")
	builder.WriteString("egress_max_retry_interval=")
	builder.WriteString(_m.EgressMaxRetryInterval)
	builder.WriteString(", ")
	builder.WriteString("egress_max_age=")
	builder.WriteString(_m.EgressMaxAge)
	builder.WriteString(", ")
	builder.WriteString("https_listen=")
	builder.WriteString(_m.HTTPSListen)
	builder.WriteString(", ")
	builder.WriteString("https_cert_pem_path=")
	builder.WriteString(_m.HTTPSCertPemPath)
	builder.WriteString(", ")
	builder.WriteString("https_key_pem_path=")
	builder.WriteString(_m.HTTPSKeyPemPath)
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_by=")
	builder.WriteString(_m.UpdatedBy)
	builder.WriteByte(')')
	return builder.String()
}

// GlobalSettingsSlice is a parsable slice of GlobalSettings.
type GlobalSettingsSlice []*GlobalSettings
