// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/menta2k/iris/backend/app/admin/service/internal/data/ent/listenerconfig"
	"github.com/menta2k/iris/backend/app/admin/service/internal/data/ent/listenerdomain"
	"github.com/menta2k/iris/backend/app/admin/service/internal/data/ent/predicate"
)

// ListenerConfigQuery is the builder for querying ListenerConfig entities.
type ListenerConfigQuery struct {
	config
	ctx         *QueryContext
	order       []listenerconfig.OrderOption
	inters      []Interceptor
	predicates  []predicate.ListenerConfig
	withDomains *ListenerDomainQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ListenerConfigQuery builder.
func (_q *ListenerConfigQuery) Where(ps ...predicate.ListenerConfig) *ListenerConfigQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *ListenerConfigQuery) Limit(limit int) *ListenerConfigQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *ListenerConfigQuery) Offset(offset int) *ListenerConfigQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *ListenerConfigQuery) Unique(unique bool) *ListenerConfigQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *ListenerConfigQuery) Order(o ...listenerconfig.OrderOption) *ListenerConfigQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryDomains chains the current query on the "domains" edge.
func (_q *ListenerConfigQuery) QueryDomains() *ListenerDomainQuery {
	query := (&ListenerDomainClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(listenerconfig.Table, listenerconfig.FieldID, selector),
			sqlgraph.To(listenerdomain.Table, listenerdomain.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, listenerconfig.DomainsTable, listenerconfig.DomainsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ListenerConfig entity from the query.
// Returns a *NotFoundError when no ListenerConfig was found.
func (_q *ListenerConfigQuery) First(ctx context.Context) (*ListenerConfig, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{listenerconfig.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *ListenerConfigQuery) FirstX(ctx context.Context) *ListenerConfig {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ListenerConfig ID from the query.
// Returns a *NotFoundError when no ListenerConfig ID was found.
func (_q *ListenerConfigQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{listenerconfig.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *ListenerConfigQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ListenerConfig entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ListenerConfig entity is found.
// Returns a *NotFoundError when no ListenerConfig entities are found.
func (_q *ListenerConfigQuery) Only(ctx context.Context) (*ListenerConfig, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{listenerconfig.Label}
	default:
		return nil, &NotSingularError{listenerconfig.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *ListenerConfigQuery) OnlyX(ctx context.Context) *ListenerConfig {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ListenerConfig ID in the query.
// Returns a *NotSingularError when more than one ListenerConfig ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *ListenerConfigQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{listenerconfig.Label}
	default:
		err = &NotSingularError{listenerconfig.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *ListenerConfigQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ListenerConfigs.
func (_q *ListenerConfigQuery) All(ctx context.Context) ([]*ListenerConfig, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ListenerConfig, *ListenerConfigQuery]()
	return withInterceptors[[]*ListenerConfig](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *ListenerConfigQuery) AllX(ctx context.Context) []*ListenerConfig {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ListenerConfig IDs.
func (_q *ListenerConfigQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(listenerconfig.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *ListenerConfigQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *ListenerConfigQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*ListenerConfigQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *ListenerConfigQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *ListenerConfigQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *ListenerConfigQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ListenerConfigQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *ListenerConfigQuery) Clone() *ListenerConfigQuery {
	if _q == nil {
		return nil
	}
	return &ListenerConfigQuery{
		config:      _q.config,
		ctx:         _q.ctx.Clone(),
		order:       append([]listenerconfig.OrderOption{}, _q.order...),
		inters:      append([]Interceptor{}, _q.inters...),
		predicates:  append([]predicate.ListenerConfig{}, _q.predicates...),
		withDomains: _q.withDomains.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithDomains tells the query-builder to eager-load the nodes that are connected to
// the "domains" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ListenerConfigQuery) WithDomains(opts ...func(*ListenerDomainQuery)) *ListenerConfigQuery {
	query := (&ListenerDomainClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withDomains = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ListenerConfig.Query().
//		GroupBy(listenerconfig.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *ListenerConfigQuery) GroupBy(field string, fields ...string) *ListenerConfigGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ListenerConfigGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = listenerconfig.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.ListenerConfig.Query().
//		Select(listenerconfig.FieldName).
//		Scan(ctx, &v)
func (_q *ListenerConfigQuery) Select(fields ...string) *ListenerConfigSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &ListenerConfigSelect{ListenerConfigQuery: _q}
	sbuild.label = listenerconfig.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ListenerConfigSelect configured with the given aggregations.
func (_q *ListenerConfigQuery) Aggregate(fns ...AggregateFunc) *ListenerConfigSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *ListenerConfigQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !listenerconfig.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *ListenerConfigQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ListenerConfig, error) {
	var (
		nodes       = []*ListenerConfig{}
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withDomains != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ListenerConfig).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ListenerConfig{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withDomains; query != nil {
		if err := _q.loadDomains(ctx, query, nodes,
			func(n *ListenerConfig) { n.Edges.Domains = []*ListenerDomain{} },
			func(n *ListenerConfig, e *ListenerDomain) { n.Edges.Domains = append(n.Edges.Domains, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *ListenerConfigQuery) loadDomains(ctx context.Context, query *ListenerDomainQuery, nodes []*ListenerConfig, init func(*ListenerConfig), assign func(*ListenerConfig, *ListenerDomain)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*ListenerConfig)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.ListenerDomain(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(listenerconfig.DomainsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.listener_config_domains
		if fk == nil {
			return fmt.Errorf(`foreign-key "listener_config_domains" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "listener_config_domains" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *ListenerConfigQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *ListenerConfigQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(listenerconfig.Table, listenerconfig.Columns, sqlgraph.NewFieldSpec(listenerconfig.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, listenerconfig.FieldID)
		for i := range fields {
			if fields[i] != listenerconfig.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *ListenerConfigQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(listenerconfig.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = listenerconfig.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ListenerConfigGroupBy is the group-by builder for ListenerConfig entities.
type ListenerConfigGroupBy struct {
	selector
	build *ListenerConfigQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *ListenerConfigGroupBy) Aggregate(fns ...AggregateFunc) *ListenerConfigGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *ListenerConfigGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ListenerConfigQuery, *ListenerConfigGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *ListenerConfigGroupBy) sqlScan(ctx context.Context, root *ListenerConfigQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ListenerConfigSelect is the builder for selecting fields of ListenerConfig entities.
type ListenerConfigSelect struct {
	*ListenerConfigQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *ListenerConfigSelect) Aggregate(fns ...AggregateFunc) *ListenerConfigSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *ListenerConfigSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ListenerConfigQuery, *ListenerConfigSelect](ctx, _s.ListenerConfigQuery, _s, _s.inters, v)
}

func (_s *ListenerConfigSelect) sqlScan(ctx context.Context, root *ListenerConfigQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
