// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/menta2k/iris/backend/app/admin/service/internal/data/ent/listenerconfig"
	"github.com/menta2k/iris/backend/app/admin/service/internal/data/ent/listenerdomain"
	"github.com/menta2k/iris/backend/app/admin/service/internal/data/ent/predicate"
)

// ListenerConfigUpdate is the builder for updating ListenerConfig entities.
type ListenerConfigUpdate struct {
	config
	hooks    []Hook
	mutation *ListenerConfigMutation
}

// Where appends a list predicates to the ListenerConfigUpdate builder.
func (_u *ListenerConfigUpdate) Where(ps ...predicate.ListenerConfig) *ListenerConfigUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *ListenerConfigUpdate) SetName(v string) *ListenerConfigUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ListenerConfigUpdate) SetNillableName(v *string) *ListenerConfigUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetListenAddr sets the "listen_addr" field.
func (_u *ListenerConfigUpdate) SetListenAddr(v string) *ListenerConfigUpdate {
	_u.mutation.SetListenAddr(v)
	return _u
}

// SetNillableListenAddr sets the "listen_addr" field if the given value is not nil.
func (_u *ListenerConfigUpdate) SetNillableListenAddr(v *string) *ListenerConfigUpdate {
	if v != nil {
		_u.SetListenAddr(*v)
	}
	return _u
}

// SetHostname sets the "hostname" field.
func (_u *ListenerConfigUpdate) SetHostname(v string) *ListenerConfigUpdate {
	_u.mutation.SetHostname(v)
	return _u
}

// SetNillableHostname sets the "hostname" field if the given value is not nil.
func (_u *ListenerConfigUpdate) SetNillableHostname(v *string) *ListenerConfigUpdate {
	if v != nil {
		_u.SetHostname(*v)
	}
	return _u
}

// SetTLSEnabled sets the "tls_enabled" field.
func (_u *ListenerConfigUpdate) SetTLSEnabled(v bool) *ListenerConfigUpdate {
	_u.mutation.SetTLSEnabled(v)
	return _u
}

// SetNillableTLSEnabled sets the "tls_enabled" field if the given value is not nil.
func (_u *ListenerConfigUpdate) SetNillableTLSEnabled(v *bool) *ListenerConfigUpdate {
	if v != nil {
		_u.SetTLSEnabled(*v)
	}
	return _u
}

// SetTLSCertPemPath sets the "tls_cert_pem_path" field.
func (_u *ListenerConfigUpdate) SetTLSCertPemPath(v string) *ListenerConfigUpdate {
	_u.mutation.SetTLSCertPemPath(v)
	return _u
}

// SetNillableTLSCertPemPath sets the "tls_cert_pem_path" field if the given value is not nil.
func (_u *ListenerConfigUpdate) SetNillableTLSCertPemPath(v *string) *ListenerConfigUpdate {
	if v != nil {
		_u.SetTLSCertPemPath(*v)
	}
	return _u
}

// ClearTLSCertPemPath clears the value of the "tls_cert_pem_path" field.
func (_u *ListenerConfigUpdate) ClearTLSCertPemPath() *ListenerConfigUpdate {
	_u.mutation.ClearTLSCertPemPath()
	return _u
}

// SetTLSKeyPemPath sets the "tls_key_pem_path" field.
func (_u *ListenerConfigUpdate) SetTLSKeyPemPath(v string) *ListenerConfigUpdate {
	_u.mutation.SetTLSKeyPemPath(v)
	return _u
}

// SetNillableTLSKeyPemPath sets the "tls_key_pem_path" field if the given value is not nil.
func (_u *ListenerConfigUpdate) SetNillableTLSKeyPemPath(v *string) *ListenerConfigUpdate {
	if v != nil {
		_u.SetTLSKeyPemPath(*v)
	}
	return _u
}

// ClearTLSKeyPemPath clears the value of the "tls_key_pem_path" field.
func (_u *ListenerConfigUpdate) ClearTLSKeyPemPath() *ListenerConfigUpdate {
	_u.mutation.ClearTLSKeyPemPath()
	return _u
}

// SetRequireAuth sets the "require_auth" field.
func (_u *ListenerConfigUpdate) SetRequireAuth(v bool) *ListenerConfigUpdate {
	_u.mutation.SetRequireAuth(v)
	return _u
}

// SetNillableRequireAuth sets the "require_auth" field if the given value is not nil.
func (_u *ListenerConfigUpdate) SetNillableRequireAuth(v *bool) *ListenerConfigUpdate {
	if v != nil {
		_u.SetRequireAuth(*v)
	}
	return _u
}

// SetMaxMessageSize sets the "max_message_size" field.
func (_u *ListenerConfigUpdate) SetMaxMessageSize(v uint64) *ListenerConfigUpdate {
	_u.mutation.ResetMaxMessageSize()
	_u.mutation.SetMaxMessageSize(v)
	return _u
}

// SetNillableMaxMessageSize sets the "max_message_size" field if the given value is not nil.
func (_u *ListenerConfigUpdate) SetNillableMaxMessageSize(v *uint64) *ListenerConfigUpdate {
	if v != nil {
		_u.SetMaxMessageSize(*v)
	}
	return _u
}

// AddMaxMessageSize adds value to the "max_message_size" field.
func (_u *ListenerConfigUpdate) AddMaxMessageSize(v int64) *ListenerConfigUpdate {
	_u.mutation.AddMaxMessageSize(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ListenerConfigUpdate) SetUpdatedAt(v time.Time) *ListenerConfigUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddDomainIDs adds the "domains" edge to the ListenerDomain entity by IDs.
func (_u *ListenerConfigUpdate) AddDomainIDs(ids ...int) *ListenerConfigUpdate {
	_u.mutation.AddDomainIDs(ids...)
	return _u
}

// AddDomains adds the "domains" edges to the ListenerDomain entity.
func (_u *ListenerConfigUpdate) AddDomains(v ...*ListenerDomain) *ListenerConfigUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDomainIDs(ids...)
}

// Mutation returns the ListenerConfigMutation object of the builder.
func (_u *ListenerConfigUpdate) Mutation() *ListenerConfigMutation {
	return _u.mutation
}

// ClearDomains clears all "domains" edges to the ListenerDomain entity.
func (_u *ListenerConfigUpdate) ClearDomains() *ListenerConfigUpdate {
	_u.mutation.ClearDomains()
	return _u
}

// RemoveDomainIDs removes the "domains" edge to ListenerDomain entities by IDs.
func (_u *ListenerConfigUpdate) RemoveDomainIDs(ids ...int) *ListenerConfigUpdate {
	_u.mutation.RemoveDomainIDs(ids...)
	return _u
}

// RemoveDomains removes "domains" edges to ListenerDomain entities.
func (_u *ListenerConfigUpdate) RemoveDomains(v ...*ListenerDomain) *ListenerConfigUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDomainIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ListenerConfigUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ListenerConfigUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ListenerConfigUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ListenerConfigUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ListenerConfigUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := listenerconfig.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ListenerConfigUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := listenerconfig.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ListenerConfig.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ListenAddr(); ok {
		if err := listenerconfig.ListenAddrValidator(v); err != nil {
			return &ValidationError{Name: "listen_addr", err: fmt.Errorf(`ent: validator failed for field "ListenerConfig.listen_addr": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Hostname(); ok {
		if err := listenerconfig.HostnameValidator(v); err != nil {
			return &ValidationError{Name: "hostname", err: fmt.Errorf(`ent: validator failed for field "ListenerConfig.hostname": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TLSCertPemPath(); ok {
		if err := listenerconfig.TLSCertPemPathValidator(v); err != nil {
			return &ValidationError{Name: "tls_cert_pem_path", err: fmt.Errorf(`ent: validator failed for field "ListenerConfig.tls_cert_pem_path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TLSKeyPemPath(); ok {
		if err := listenerconfig.TLSKeyPemPathValidator(v); err != nil {
			return &ValidationError{Name: "tls_key_pem_path", err: fmt.Errorf(`ent: validator failed for field "ListenerConfig.tls_key_pem_path": %w`, err)}
		}
	}
	return nil
}

func (_u *ListenerConfigUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(listenerconfig.Table, listenerconfig.Columns, sqlgraph.NewFieldSpec(listenerconfig.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(listenerconfig.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ListenAddr(); ok {
		_spec.SetField(listenerconfig.FieldListenAddr, field.TypeString, value)
	}
	if value, ok := _u.mutation.Hostname(); ok {
		_spec.SetField(listenerconfig.FieldHostname, field.TypeString, value)
	}
	if value, ok := _u.mutation.TLSEnabled(); ok {
		_spec.SetField(listenerconfig.FieldTLSEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.TLSCertPemPath(); ok {
		_spec.SetField(listenerconfig.FieldTLSCertPemPath, field.TypeString, value)
	}
	if _u.mutation.TLSCertPemPathCleared() {
		_spec.ClearField(listenerconfig.FieldTLSCertPemPath, field.TypeString)
	}
	if value, ok := _u.mutation.TLSKeyPemPath(); ok {
		_spec.SetField(listenerconfig.FieldTLSKeyPemPath, field.TypeString, value)
	}
	if _u.mutation.TLSKeyPemPathCleared() {
		_spec.ClearField(listenerconfig.FieldTLSKeyPemPath, field.TypeString)
	}
	if value, ok := _u.mutation.RequireAuth(); ok {
		_spec.SetField(listenerconfig.FieldRequireAuth, field.TypeBool, value)
	}
	if value, ok := _u.mutation.MaxMessageSize(); ok {
		_spec.SetField(listenerconfig.FieldMaxMessageSize, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedMaxMessageSize(); ok {
		_spec.AddField(listenerconfig.FieldMaxMessageSize, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(listenerconfig.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.DomainsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   listenerconfig.DomainsTable,
			Columns: []string{listenerconfig.DomainsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(listenerdomain.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDomainsIDs(); len(nodes) > 0 && !_u.mutation.DomainsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   listenerconfig.DomainsTable,
			Columns: []string{listenerconfig.DomainsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(listenerdomain.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DomainsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   listenerconfig.DomainsTable,
			Columns: []string{listenerconfig.DomainsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(listenerdomain.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{listenerconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ListenerConfigUpdateOne is the builder for updating a single ListenerConfig entity.
type ListenerConfigUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ListenerConfigMutation
}

// SetName sets the "name" field.
func (_u *ListenerConfigUpdateOne) SetName(v string) *ListenerConfigUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ListenerConfigUpdateOne) SetNillableName(v *string) *ListenerConfigUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetListenAddr sets the "listen_addr" field.
func (_u *ListenerConfigUpdateOne) SetListenAddr(v string) *ListenerConfigUpdateOne {
	_u.mutation.SetListenAddr(v)
	return _u
}

// SetNillableListenAddr sets the "listen_addr" field if the given value is not nil.
func (_u *ListenerConfigUpdateOne) SetNillableListenAddr(v *string) *ListenerConfigUpdateOne {
	if v != nil {
		_u.SetListenAddr(*v)
	}
	return _u
}

// SetHostname sets the "hostname" field.
func (_u *ListenerConfigUpdateOne) SetHostname(v string) *ListenerConfigUpdateOne {
	_u.mutation.SetHostname(v)
	return _u
}

// SetNillableHostname sets the "hostname" field if the given value is not nil.
func (_u *ListenerConfigUpdateOne) SetNillableHostname(v *string) *ListenerConfigUpdateOne {
	if v != nil {
		_u.SetHostname(*v)
	}
	return _u
}

// SetTLSEnabled sets the "tls_enabled" field.
func (_u *ListenerConfigUpdateOne) SetTLSEnabled(v bool) *ListenerConfigUpdateOne {
	_u.mutation.SetTLSEnabled(v)
	return _u
}

// SetNillableTLSEnabled sets the "tls_enabled" field if the given value is not nil.
func (_u *ListenerConfigUpdateOne) SetNillableTLSEnabled(v *bool) *ListenerConfigUpdateOne {
	if v != nil {
		_u.SetTLSEnabled(*v)
	}
	return _u
}

// SetTLSCertPemPath sets the "tls_cert_pem_path" field.
func (_u *ListenerConfigUpdateOne) SetTLSCertPemPath(v string) *ListenerConfigUpdateOne {
	_u.mutation.SetTLSCertPemPath(v)
	return _u
}

// SetNillableTLSCertPemPath sets the "tls_cert_pem_path" field if the given value is not nil.
func (_u *ListenerConfigUpdateOne) SetNillableTLSCertPemPath(v *string) *ListenerConfigUpdateOne {
	if v != nil {
		_u.SetTLSCertPemPath(*v)
	}
	return _u
}

// ClearTLSCertPemPath clears the value of the "tls_cert_pem_path" field.
func (_u *ListenerConfigUpdateOne) ClearTLSCertPemPath() *ListenerConfigUpdateOne {
	_u.mutation.ClearTLSCertPemPath()
	return _u
}

// SetTLSKeyPemPath sets the "tls_key_pem_path" field.
func (_u *ListenerConfigUpdateOne) SetTLSKeyPemPath(v string) *ListenerConfigUpdateOne {
	_u.mutation.SetTLSKeyPemPath(v)
	return _u
}

// SetNillableTLSKeyPemPath sets the "tls_key_pem_path" field if the given value is not nil.
func (_u *ListenerConfigUpdateOne) SetNillableTLSKeyPemPath(v *string) *ListenerConfigUpdateOne {
	if v != nil {
		_u.SetTLSKeyPemPath(*v)
	}
	return _u
}

// ClearTLSKeyPemPath clears the value of the "tls_key_pem_path" field.
func (_u *ListenerConfigUpdateOne) ClearTLSKeyPemPath() *ListenerConfigUpdateOne {
	_u.mutation.ClearTLSKeyPemPath()
	return _u
}

// SetRequireAuth sets the "require_auth" field.
func (_u *ListenerConfigUpdateOne) SetRequireAuth(v bool) *ListenerConfigUpdateOne {
	_u.mutation.SetRequireAuth(v)
	return _u
}

// SetNillableRequireAuth sets the "require_auth" field if the given value is not nil.
func (_u *ListenerConfigUpdateOne) SetNillableRequireAuth(v *bool) *ListenerConfigUpdateOne {
	if v != nil {
		_u.SetRequireAuth(*v)
	}
	return _u
}

// SetMaxMessageSize sets the "max_message_size" field.
func (_u *ListenerConfigUpdateOne) SetMaxMessageSize(v uint64) *ListenerConfigUpdateOne {
	_u.mutation.ResetMaxMessageSize()
	_u.mutation.SetMaxMessageSize(v)
	return _u
}

// SetNillableMaxMessageSize sets the "max_message_size" field if the given value is not nil.
func (_u *ListenerConfigUpdateOne) SetNillableMaxMessageSize(v *uint64) *ListenerConfigUpdateOne {
	if v != nil {
		_u.SetMaxMessageSize(*v)
	}
	return _u
}

// AddMaxMessageSize adds value to the "max_message_size" field.
func (_u *ListenerConfigUpdateOne) AddMaxMessageSize(v int64) *ListenerConfigUpdateOne {
	_u.mutation.AddMaxMessageSize(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ListenerConfigUpdateOne) SetUpdatedAt(v time.Time) *ListenerConfigUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddDomainIDs adds the "domains" edge to the ListenerDomain entity by IDs.
func (_u *ListenerConfigUpdateOne) AddDomainIDs(ids ...int) *ListenerConfigUpdateOne {
	_u.mutation.AddDomainIDs(ids...)
	return _u
}

// AddDomains adds the "domains" edges to the ListenerDomain entity.
func (_u *ListenerConfigUpdateOne) AddDomains(v ...*ListenerDomain) *ListenerConfigUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDomainIDs(ids...)
}

// Mutation returns the ListenerConfigMutation object of the builder.
func (_u *ListenerConfigUpdateOne) Mutation() *ListenerConfigMutation {
	return _u.mutation
}

// ClearDomains clears all "domains" edges to the ListenerDomain entity.
func (_u *ListenerConfigUpdateOne) ClearDomains() *ListenerConfigUpdateOne {
	_u.mutation.ClearDomains()
	return _u
}

// RemoveDomainIDs removes the "domains" edge to ListenerDomain entities by IDs.
func (_u *ListenerConfigUpdateOne) RemoveDomainIDs(ids ...int) *ListenerConfigUpdateOne {
	_u.mutation.RemoveDomainIDs(ids...)
	return _u
}

// RemoveDomains removes "domains" edges to ListenerDomain entities.
func (_u *ListenerConfigUpdateOne) RemoveDomains(v ...*ListenerDomain) *ListenerConfigUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDomainIDs(ids...)
}

// Where appends a list predicates to the ListenerConfigUpdate builder.
func (_u *ListenerConfigUpdateOne) Where(ps ...predicate.ListenerConfig) *ListenerConfigUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ListenerConfigUpdateOne) Select(field string, fields ...string) *ListenerConfigUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ListenerConfig entity.
func (_u *ListenerConfigUpdateOne) Save(ctx context.Context) (*ListenerConfig, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ListenerConfigUpdateOne) SaveX(ctx context.Context) *ListenerConfig {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ListenerConfigUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ListenerConfigUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ListenerConfigUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := listenerconfig.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ListenerConfigUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := listenerconfig.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ListenerConfig.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ListenAddr(); ok {
		if err := listenerconfig.ListenAddrValidator(v); err != nil {
			return &ValidationError{Name: "listen_addr", err: fmt.Errorf(`ent: validator failed for field "ListenerConfig.listen_addr": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Hostname(); ok {
		if err := listenerconfig.HostnameValidator(v); err != nil {
			return &ValidationError{Name: "hostname", err: fmt.Errorf(`ent: validator failed for field "ListenerConfig.hostname": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TLSCertPemPath(); ok {
		if err := listenerconfig.TLSCertPemPathValidator(v); err != nil {
			return &ValidationError{Name: "tls_cert_pem_path", err: fmt.Errorf(`ent: validator failed for field "ListenerConfig.tls_cert_pem_path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TLSKeyPemPath(); ok {
		if err := listenerconfig.TLSKeyPemPathValidator(v); err != nil {
			return &ValidationError{Name: "tls_key_pem_path", err: fmt.Errorf(`ent: validator failed for field "ListenerConfig.tls_key_pem_path": %w`, err)}
		}
	}
	return nil
}

func (_u *ListenerConfigUpdateOne) sqlSave(ctx context.Context) (_node *ListenerConfig, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(listenerconfig.Table, listenerconfig.Columns, sqlgraph.NewFieldSpec(listenerconfig.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ListenerConfig.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, listenerconfig.FieldID)
		for _, f := range fields {
			if !listenerconfig.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != listenerconfig.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(listenerconfig.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ListenAddr(); ok {
		_spec.SetField(listenerconfig.FieldListenAddr, field.TypeString, value)
	}
	if value, ok := _u.mutation.Hostname(); ok {
		_spec.SetField(listenerconfig.FieldHostname, field.TypeString, value)
	}
	if value, ok := _u.mutation.TLSEnabled(); ok {
		_spec.SetField(listenerconfig.FieldTLSEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.TLSCertPemPath(); ok {
		_spec.SetField(listenerconfig.FieldTLSCertPemPath, field.TypeString, value)
	}
	if _u.mutation.TLSCertPemPathCleared() {
		_spec.ClearField(listenerconfig.FieldTLSCertPemPath, field.TypeString)
	}
	if value, ok := _u.mutation.TLSKeyPemPath(); ok {
		_spec.SetField(listenerconfig.FieldTLSKeyPemPath, field.TypeString, value)
	}
	if _u.mutation.TLSKeyPemPathCleared() {
		_spec.ClearField(listenerconfig.FieldTLSKeyPemPath, field.TypeString)
	}
	if value, ok := _u.mutation.RequireAuth(); ok {
		_spec.SetField(listenerconfig.FieldRequireAuth, field.TypeBool, value)
	}
	if value, ok := _u.mutation.MaxMessageSize(); ok {
		_spec.SetField(listenerconfig.FieldMaxMessageSize, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedMaxMessageSize(); ok {
		_spec.AddField(listenerconfig.FieldMaxMessageSize, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(listenerconfig.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.DomainsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   listenerconfig.DomainsTable,
			Columns: []string{listenerconfig.DomainsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(listenerdomain.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDomainsIDs(); len(nodes) > 0 && !_u.mutation.DomainsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   listenerconfig.DomainsTable,
			Columns: []string{listenerconfig.DomainsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(listenerdomain.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DomainsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   listenerconfig.DomainsTable,
			Columns: []string{listenerconfig.DomainsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(listenerdomain.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ListenerConfig{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{listenerconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
