// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/menta2k/iris/backend/app/admin/service/internal/data/ent/listenerconfig"
	"github.com/menta2k/iris/backend/app/admin/service/internal/data/ent/listenerdomain"
)

// ListenerDomainCreate is the builder for creating a ListenerDomain entity.
type ListenerDomainCreate struct {
	config
	mutation *ListenerDomainMutation
	hooks    []Hook
}

// SetDomain sets the "domain" field.
func (_c *ListenerDomainCreate) SetDomain(v string) *ListenerDomainCreate {
	_c.mutation.SetDomain(v)
	return _c
}

// SetRelayAllowed sets the "relay_allowed" field.
func (_c *ListenerDomainCreate) SetRelayAllowed(v bool) *ListenerDomainCreate {
	_c.mutation.SetRelayAllowed(v)
	return _c
}

// SetNillableRelayAllowed sets the "relay_allowed" field if the given value is not nil.
func (_c *ListenerDomainCreate) SetNillableRelayAllowed(v *bool) *ListenerDomainCreate {
	if v != nil {
		_c.SetRelayAllowed(*v)
	}
	return _c
}

// SetRequireTLS sets the "require_tls" field.
func (_c *ListenerDomainCreate) SetRequireTLS(v bool) *ListenerDomainCreate {
	_c.mutation.SetRequireTLS(v)
	return _c
}

// SetNillableRequireTLS sets the "require_tls" field if the given value is not nil.
func (_c *ListenerDomainCreate) SetNillableRequireTLS(v *bool) *ListenerDomainCreate {
	if v != nil {
		_c.SetRequireTLS(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ListenerDomainCreate) SetCreatedAt(v time.Time) *ListenerDomainCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ListenerDomainCreate) SetNillableCreatedAt(v *time.Time) *ListenerDomainCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ListenerDomainCreate) SetUpdatedAt(v time.Time) *ListenerDomainCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ListenerDomainCreate) SetNillableUpdatedAt(v *time.Time) *ListenerDomainCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetListenerID sets the "listener" edge to the ListenerConfig entity by ID.
func (_c *ListenerDomainCreate) SetListenerID(id int) *ListenerDomainCreate {
	_c.mutation.SetListenerID(id)
	return _c
}

// SetNillableListenerID sets the "listener" edge to the ListenerConfig entity by ID if the given value is not nil.
func (_c *ListenerDomainCreate) SetNillableListenerID(id *int) *ListenerDomainCreate {
	if id != nil {
		_c = _c.SetListenerID(*id)
	}
	return _c
}

// SetListener sets the "listener" edge to the ListenerConfig entity.
func (_c *ListenerDomainCreate) SetListener(v *ListenerConfig) *ListenerDomainCreate {
	return _c.SetListenerID(v.ID)
}

// Mutation returns the ListenerDomainMutation object of the builder.
func (_c *ListenerDomainCreate) Mutation() *ListenerDomainMutation {
	return _c.mutation
}

// Save creates the ListenerDomain in the database.
func (_c *ListenerDomainCreate) Save(ctx context.Context) (*ListenerDomain, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ListenerDomainCreate) SaveX(ctx context.Context) *ListenerDomain {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ListenerDomainCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ListenerDomainCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ListenerDomainCreate) defaults() {
	if _, ok := _c.mutation.RelayAllowed(); !ok {
		v := listenerdomain.DefaultRelayAllowed
		_c.mutation.SetRelayAllowed(v)
	}
	if _, ok := _c.mutation.RequireTLS(); !ok {
		v := listenerdomain.DefaultRequireTLS
		_c.mutation.SetRequireTLS(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := listenerdomain.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := listenerdomain.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ListenerDomainCreate) check() error {
	if _, ok := _c.mutation.Domain(); !ok {
		return &ValidationError{Name: "domain", err: errors.New(`ent: missing required field "ListenerDomain.domain"`)}
	}
	if v, ok := _c.mutation.Domain(); ok {
		if err := listenerdomain.DomainValidator(v); err != nil {
			return &ValidationError{Name: "domain", err: fmt.Errorf(`ent: validator failed for field "ListenerDomain.domain": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RelayAllowed(); !ok {
		return &ValidationError{Name: "relay_allowed", err: errors.New(`ent: missing required field "ListenerDomain.relay_allowed"`)}
	}
	if _, ok := _c.mutation.RequireTLS(); !ok {
		return &ValidationError{Name: "require_tls", err: errors.New(`ent: missing required field "ListenerDomain.require_tls"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ListenerDomain.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ListenerDomain.updated_at"`)}
	}
	return nil
}

func (_c *ListenerDomainCreate) sqlSave(ctx context.Context) (*ListenerDomain, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ListenerDomainCreate) createSpec() (*ListenerDomain, *sqlgraph.CreateSpec) {
	var (
		_node = &ListenerDomain{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(listenerdomain.Table, sqlgraph.NewFieldSpec(listenerdomain.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Domain(); ok {
		_spec.SetField(listenerdomain.FieldDomain, field.TypeString, value)
		_node.Domain = value
	}
	if value, ok := _c.mutation.RelayAllowed(); ok {
		_spec.SetField(listenerdomain.FieldRelayAllowed, field.TypeBool, value)
		_node.RelayAllowed = value
	}
	if value, ok := _c.mutation.RequireTLS(); ok {
		_spec.SetField(listenerdomain.FieldRequireTLS, field.TypeBool, value)
		_node.RequireTLS = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(listenerdomain.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(listenerdomain.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.ListenerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   listenerdomain.ListenerTable,
			Columns: []string{listenerdomain.ListenerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(listenerconfig.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.listener_config_domains = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ListenerDomainCreateBulk is the builder for creating many ListenerDomain entities in bulk.
type ListenerDomainCreateBulk struct {
	config
	err      error
	builders []*ListenerDomainCreate
}

// Save creates the ListenerDomain entities in the database.
func (_c *ListenerDomainCreateBulk) Save(ctx context.Context) ([]*ListenerDomain, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ListenerDomain, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ListenerDomainMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ListenerDomainCreateBulk) SaveX(ctx context.Context) []*ListenerDomain {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ListenerDomainCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ListenerDomainCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
