// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/menta2k/iris/backend/app/admin/service/internal/data/ent/metricsnapshot"
)

// MetricSnapshotCreate is the builder for creating a MetricSnapshot entity.
type MetricSnapshotCreate struct {
	config
	mutation *MetricSnapshotMutation
	hooks    []Hook
}

// SetAt sets the "at" field.
func (_c *MetricSnapshotCreate) SetAt(v time.Time) *MetricSnapshotCreate {
	_c.mutation.SetAt(v)
	return _c
}

// SetNillableAt sets the "at" field if the given value is not nil.
func (_c *MetricSnapshotCreate) SetNillableAt(v *time.Time) *MetricSnapshotCreate {
	if v != nil {
		_c.SetAt(*v)
	}
	return _c
}

// SetQueue sets the "queue" field.
func (_c *MetricSnapshotCreate) SetQueue(v string) *MetricSnapshotCreate {
	_c.mutation.SetQueue(v)
	return _c
}

// SetNillableQueue sets the "queue" field if the given value is not nil.
func (_c *MetricSnapshotCreate) SetNillableQueue(v *string) *MetricSnapshotCreate {
	if v != nil {
		_c.SetQueue(*v)
	}
	return _c
}

// SetQueueSize sets the "queue_size" field.
func (_c *MetricSnapshotCreate) SetQueueSize(v uint64) *MetricSnapshotCreate {
	_c.mutation.SetQueueSize(v)
	return _c
}

// SetNillableQueueSize sets the "queue_size" field if the given value is not nil.
func (_c *MetricSnapshotCreate) SetNillableQueueSize(v *uint64) *MetricSnapshotCreate {
	if v != nil {
		_c.SetQueueSize(*v)
	}
	return _c
}

// SetDeliveredTotal sets the "delivered_total" field.
func (_c *MetricSnapshotCreate) SetDeliveredTotal(v uint64) *MetricSnapshotCreate {
	_c.mutation.SetDeliveredTotal(v)
	return _c
}

// SetNillableDeliveredTotal sets the "delivered_total" field if the given value is not nil.
func (_c *MetricSnapshotCreate) SetNillableDeliveredTotal(v *uint64) *MetricSnapshotCreate {
	if v != nil {
		_c.SetDeliveredTotal(*v)
	}
	return _c
}

// SetFailedTotal sets the "failed_total" field.
func (_c *MetricSnapshotCreate) SetFailedTotal(v uint64) *MetricSnapshotCreate {
	_c.mutation.SetFailedTotal(v)
	return _c
}

// SetNillableFailedTotal sets the "failed_total" field if the given value is not nil.
func (_c *MetricSnapshotCreate) SetNillableFailedTotal(v *uint64) *MetricSnapshotCreate {
	if v != nil {
		_c.SetFailedTotal(*v)
	}
	return _c
}

// SetDeferredTotal sets the "deferred_total" field.
func (_c *MetricSnapshotCreate) SetDeferredTotal(v uint64) *MetricSnapshotCreate {
	_c.mutation.SetDeferredTotal(v)
	return _c
}

// SetNillableDeferredTotal sets the "deferred_total" field if the given value is not nil.
func (_c *MetricSnapshotCreate) SetNillableDeferredTotal(v *uint64) *MetricSnapshotCreate {
	if v != nil {
		_c.SetDeferredTotal(*v)
	}
	return _c
}

// SetDeliveryRatePerMin sets the "delivery_rate_per_min" field.
func (_c *MetricSnapshotCreate) SetDeliveryRatePerMin(v float64) *MetricSnapshotCreate {
	_c.mutation.SetDeliveryRatePerMin(v)
	return _c
}

// SetNillableDeliveryRatePerMin sets the "delivery_rate_per_min" field if the given value is not nil.
func (_c *MetricSnapshotCreate) SetNillableDeliveryRatePerMin(v *float64) *MetricSnapshotCreate {
	if v != nil {
		_c.SetDeliveryRatePerMin(*v)
	}
	return _c
}

// SetSuspended sets the "suspended" field.
func (_c *MetricSnapshotCreate) SetSuspended(v bool) *MetricSnapshotCreate {
	_c.mutation.SetSuspended(v)
	return _c
}

// SetNillableSuspended sets the "suspended" field if the given value is not nil.
func (_c *MetricSnapshotCreate) SetNillableSuspended(v *bool) *MetricSnapshotCreate {
	if v != nil {
		_c.SetSuspended(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *MetricSnapshotCreate) SetID(v int64) *MetricSnapshotCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the MetricSnapshotMutation object of the builder.
func (_c *MetricSnapshotCreate) Mutation() *MetricSnapshotMutation {
	return _c.mutation
}

// Save creates the MetricSnapshot in the database.
func (_c *MetricSnapshotCreate) Save(ctx context.Context) (*MetricSnapshot, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MetricSnapshotCreate) SaveX(ctx context.Context) *MetricSnapshot {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MetricSnapshotCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MetricSnapshotCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MetricSnapshotCreate) defaults() {
	if _, ok := _c.mutation.At(); !ok {
		v := metricsnapshot.DefaultAt()
		_c.mutation.SetAt(v)
	}
	if _, ok := _c.mutation.QueueSize(); !ok {
		v := metricsnapshot.DefaultQueueSize
		_c.mutation.SetQueueSize(v)
	}
	if _, ok := _c.mutation.DeliveredTotal(); !ok {
		v := metricsnapshot.DefaultDeliveredTotal
		_c.mutation.SetDeliveredTotal(v)
	}
	if _, ok := _c.mutation.FailedTotal(); !ok {
		v := metricsnapshot.DefaultFailedTotal
		_c.mutation.SetFailedTotal(v)
	}
	if _, ok := _c.mutation.DeferredTotal(); !ok {
		v := metricsnapshot.DefaultDeferredTotal
		_c.mutation.SetDeferredTotal(v)
	}
	if _, ok := _c.mutation.DeliveryRatePerMin(); !ok {
		v := metricsnapshot.DefaultDeliveryRatePerMin
		_c.mutation.SetDeliveryRatePerMin(v)
	}
	if _, ok := _c.mutation.Suspended(); !ok {
		v := metricsnapshot.DefaultSuspended
		_c.mutation.SetSuspended(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MetricSnapshotCreate) check() error {
	if _, ok := _c.mutation.At(); !ok {
		return &ValidationError{Name: "at", err: errors.New(`ent: missing required field "MetricSnapshot.at"`)}
	}
	if v, ok := _c.mutation.Queue(); ok {
		if err := metricsnapshot.QueueValidator(v); err != nil {
			return &ValidationError{Name: "queue", err: fmt.Errorf(`ent: validator failed for field "MetricSnapshot.queue": %w`, err)}
		}
	}
	if _, ok := _c.mutation.QueueSize(); !ok {
		return &ValidationError{Name: "queue_size", err: errors.New(`ent: missing required field "MetricSnapshot.queue_size"`)}
	}
	if _, ok := _c.mutation.DeliveredTotal(); !ok {
		return &ValidationError{Name: "delivered_total", err: errors.New(`ent: missing required field "MetricSnapshot.delivered_total"`)}
	}
	if _, ok := _c.mutation.FailedTotal(); !ok {
		return &ValidationError{Name: "failed_total", err: errors.New(`ent: missing required field "MetricSnapshot.failed_total"`)}
	}
	if _, ok := _c.mutation.DeferredTotal(); !ok {
		return &ValidationError{Name: "deferred_total", err: errors.New(`ent: missing required field "MetricSnapshot.deferred_total"`)}
	}
	if _, ok := _c.mutation.DeliveryRatePerMin(); !ok {
		return &ValidationError{Name: "delivery_rate_per_min", err: errors.New(`ent: missing required field "MetricSnapshot.delivery_rate_per_min"`)}
	}
	if _, ok := _c.mutation.Suspended(); !ok {
		return &ValidationError{Name: "suspended", err: errors.New(`ent: missing required field "MetricSnapshot.suspended"`)}
	}
	return nil
}

func (_c *MetricSnapshotCreate) sqlSave(ctx context.Context) (*MetricSnapshot, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MetricSnapshotCreate) createSpec() (*MetricSnapshot, *sqlgraph.CreateSpec) {
	var (
		_node = &MetricSnapshot{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(metricsnapshot.Table, sqlgraph.NewFieldSpec(metricsnapshot.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.At(); ok {
		_spec.SetField(metricsnapshot.FieldAt, field.TypeTime, value)
		_node.At = value
	}
	if value, ok := _c.mutation.Queue(); ok {
		_spec.SetField(metricsnapshot.FieldQueue, field.TypeString, value)
		_node.Queue = value
	}
	if value, ok := _c.mutation.QueueSize(); ok {
		_spec.SetField(metricsnapshot.FieldQueueSize, field.TypeUint64, value)
		_node.QueueSize = value
	}
	if value, ok := _c.mutation.DeliveredTotal(); ok {
		_spec.SetField(metricsnapshot.FieldDeliveredTotal, field.TypeUint64, value)
		_node.DeliveredTotal = value
	}
	if value, ok := _c.mutation.FailedTotal(); ok {
		_spec.SetField(metricsnapshot.FieldFailedTotal, field.TypeUint64, value)
		_node.FailedTotal = value
	}
	if value, ok := _c.mutation.DeferredTotal(); ok {
		_spec.SetField(metricsnapshot.FieldDeferredTotal, field.TypeUint64, value)
		_node.DeferredTotal = value
	}
	if value, ok := _c.mutation.DeliveryRatePerMin(); ok {
		_spec.SetField(metricsnapshot.FieldDeliveryRatePerMin, field.TypeFloat64, value)
		_node.DeliveryRatePerMin = value
	}
	if value, ok := _c.mutation.Suspended(); ok {
		_spec.SetField(metricsnapshot.FieldSuspended, field.TypeBool, value)
		_node.Suspended = value
	}
	return _node, _spec
}

// MetricSnapshotCreateBulk is the builder for creating many MetricSnapshot entities in bulk.
type MetricSnapshotCreateBulk struct {
	config
	err      error
	builders []*MetricSnapshotCreate
}

// Save creates the MetricSnapshot entities in the database.
func (_c *MetricSnapshotCreateBulk) Save(ctx context.Context) ([]*MetricSnapshot, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MetricSnapshot, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MetricSnapshotMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MetricSnapshotCreateBulk) SaveX(ctx context.Context) []*MetricSnapshot {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MetricSnapshotCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MetricSnapshotCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
