// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/menta2k/iris/backend/app/admin/service/internal/data/ent/metricsnapshot"
)

// MetricSnapshot is the model entity for the MetricSnapshot schema.
type MetricSnapshot struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// At holds the value of the "at" field.
	At time.Time `json:"at,omitempty"`
	// Queue holds the value of the "queue" field.
	Queue string `json:"queue,omitempty"`
	// QueueSize holds the value of the "queue_size" field.
	QueueSize uint64 `json:"queue_size,omitempty"`
	// DeliveredTotal holds the value of the "delivered_total" field.
	DeliveredTotal uint64 `json:"delivered_total,omitempty"`
	// FailedTotal holds the value of the "failed_total" field.
	FailedTotal uint64 `json:"failed_total,omitempty"`
	// DeferredTotal holds the value of the "deferred_total" field.
	DeferredTotal uint64 `json:"deferred_total,omitempty"`
	// DeliveryRatePerMin holds the value of the "delivery_rate_per_min" field.
	DeliveryRatePerMin float64 `json:"delivery_rate_per_min,omitempty"`
	// Suspended holds the value of the "suspended" field.
	Suspended    bool `json:"suspended,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MetricSnapshot) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case metricsnapshot.FieldSuspended:
			values[i] = new(sql.NullBool)
		case metricsnapshot.FieldDeliveryRatePerMin:
			values[i] = new(sql.NullFloat64)
		case metricsnapshot.FieldID, metricsnapshot.FieldQueueSize, metricsnapshot.FieldDeliveredTotal, metricsnapshot.FieldFailedTotal, metricsnapshot.FieldDeferredTotal:
			values[i] = new(sql.NullInt64)
		case metricsnapshot.FieldQueue:
			values[i] = new(sql.NullString)
		case metricsnapshot.FieldAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MetricSnapshot fields.
func (_m *MetricSnapshot) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case metricsnapshot.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case metricsnapshot.FieldAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field at", values[i])
			} else if value.Valid {
				_m.At = value.Time
			}
		case metricsnapshot.FieldQueue:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field queue", values[i])
			} else if value.Valid {
				_m.Queue = value.String
			}
		case metricsnapshot.FieldQueueSize:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field queue_size", values[i])
			} else if value.Valid {
				_m.QueueSize = uint64(value.Int64)
			}
		case metricsnapshot.FieldDeliveredTotal:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field delivered_total", values[i])
			} else if value.Valid {
				_m.DeliveredTotal = uint64(value.Int64)
			}
		case metricsnapshot.FieldFailedTotal:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field failed_total", values[i])
			} else if value.Valid {
				_m.FailedTotal = uint64(value.Int64)
			}
		case metricsnapshot.FieldDeferredTotal:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deferred_total", values[i])
			} else if value.Valid {
				_m.DeferredTotal = uint64(value.Int64)
			}
		case metricsnapshot.FieldDeliveryRatePerMin:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field delivery_rate_per_min", values[i])
			} else if value.Valid {
				_m.DeliveryRatePerMin = value.Float64
			}
		case metricsnapshot.FieldSuspended:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field suspended", values[i])
			} else if value.Valid {
				_m.Suspended = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MetricSnapshot.
// This includes values selected through modifiers, order, etc.
func (_m *MetricSnapshot) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this MetricSnapshot.
// Note that you need to call MetricSnapshot.Unwrap() before calling this method if this MetricSnapshot
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *MetricSnapshot) Update() *MetricSnapshotUpdateOne {
	return NewMetricSnapshotClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the MetricSnapshot entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *MetricSnapshot) Unwrap() *MetricSnapshot {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: MetricSnapshot is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *MetricSnapshot) String() string {
	var builder strings.Builder
	builder.WriteString("MetricSnapshot(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("at=")
	builder.WriteString(_m.At.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("queue=")
	builder.WriteString(_m.Queue)
	builder.WriteString(", ")
	builder.WriteString("queue_size=")
	builder.WriteString(fmt.Sprintf("%v", _m.QueueSize))
	builder.WriteString(", ")
	builder.WriteString("delivered_total=")
	builder.WriteString(fmt.Sprintf("%v", _m.DeliveredTotal))
	builder.WriteString(", ")
	builder.WriteString("failed_total=")
	builder.WriteString(fmt.Sprintf("%v", _m.FailedTotal))
	builder.WriteString(", ")
	builder.WriteString("deferred_total=")
	builder.WriteString(fmt.Sprintf("%v", _m.DeferredTotal))
	builder.WriteString(", ")
	builder.WriteString("delivery_rate_per_min=")
	builder.WriteString(fmt.Sprintf("%v", _m.DeliveryRatePerMin))
	builder.WriteString(", ")
	builder.WriteString("suspended=")
	builder.WriteString(fmt.Sprintf("%v", _m.Suspended))
	builder.WriteByte(')')
	return builder.String()
}

// MetricSnapshots is a parsable slice of MetricSnapshot.
type MetricSnapshots []*MetricSnapshot
