// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/menta2k/iris/backend/app/admin/service/internal/data/ent/mfacredential"
	"github.com/menta2k/iris/backend/app/admin/service/internal/data/ent/predicate"
)

// MfaCredentialDelete is the builder for deleting a MfaCredential entity.
type MfaCredentialDelete struct {
	config
	hooks    []Hook
	mutation *MfaCredentialMutation
}

// Where appends a list predicates to the MfaCredentialDelete builder.
func (_d *MfaCredentialDelete) Where(ps ...predicate.MfaCredential) *MfaCredentialDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *MfaCredentialDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *MfaCredentialDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *MfaCredentialDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(mfacredential.Table, sqlgraph.NewFieldSpec(mfacredential.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// MfaCredentialDeleteOne is the builder for deleting a single MfaCredential entity.
type MfaCredentialDeleteOne struct {
	_d *MfaCredentialDelete
}

// Where appends a list predicates to the MfaCredentialDelete builder.
func (_d *MfaCredentialDeleteOne) Where(ps ...predicate.MfaCredential) *MfaCredentialDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *MfaCredentialDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{mfacredential.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *MfaCredentialDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
