// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/menta2k/iris/backend/app/admin/service/internal/data/ent/acmeaccount"
	"github.com/menta2k/iris/backend/app/admin/service/internal/data/ent/acmecertificate"
	"github.com/menta2k/iris/backend/app/admin/service/internal/data/ent/acmednsproviderconfig"
	"github.com/menta2k/iris/backend/app/admin/service/internal/data/ent/auditentry"
	"github.com/menta2k/iris/backend/app/admin/service/internal/data/ent/dkimidentity"
	"github.com/menta2k/iris/backend/app/admin/service/internal/data/ent/dsnevent"
	"github.com/menta2k/iris/backend/app/admin/service/internal/data/ent/feedbackreport"
	"github.com/menta2k/iris/backend/app/admin/service/internal/data/ent/globalsettings"
	"github.com/menta2k/iris/backend/app/admin/service/internal/data/ent/listenerconfig"
	"github.com/menta2k/iris/backend/app/admin/service/internal/data/ent/listenerdomain"
	"github.com/menta2k/iris/backend/app/admin/service/internal/data/ent/logevent"
	"github.com/menta2k/iris/backend/app/admin/service/internal/data/ent/loginpolicy"
	"github.com/menta2k/iris/backend/app/admin/service/internal/data/ent/mailclass"
	"github.com/menta2k/iris/backend/app/admin/service/internal/data/ent/mailwebhook"
	"github.com/menta2k/iris/backend/app/admin/service/internal/data/ent/metricsnapshot"
	"github.com/menta2k/iris/backend/app/admin/service/internal/data/ent/mfacredential"
	"github.com/menta2k/iris/backend/app/admin/service/internal/data/ent/policyhistory"
	"github.com/menta2k/iris/backend/app/admin/service/internal/data/ent/role"
	"github.com/menta2k/iris/backend/app/admin/service/internal/data/ent/routingrule"
	"github.com/menta2k/iris/backend/app/admin/service/internal/data/ent/rulecondition"
	"github.com/menta2k/iris/backend/app/admin/service/internal/data/ent/ruletarget"
	"github.com/menta2k/iris/backend/app/admin/service/internal/data/ent/schema"
	"github.com/menta2k/iris/backend/app/admin/service/internal/data/ent/suppressionentry"
	"github.com/menta2k/iris/backend/app/admin/service/internal/data/ent/user"
	"github.com/menta2k/iris/backend/app/admin/service/internal/data/ent/virtualmta"
	"github.com/menta2k/iris/backend/app/admin/service/internal/data/ent/virtualmtagroup"
	"github.com/menta2k/iris/backend/app/admin/service/internal/data/ent/virtualmtagroupmember"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	acmeaccountFields := schema.AcmeAccount{}.Fields()
	_ = acmeaccountFields
	// acmeaccountDescEmail is the schema descriptor for email field.
	acmeaccountDescEmail := acmeaccountFields[1].Descriptor()
	// acmeaccount.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	acmeaccount.EmailValidator = func() func(string) error {
		validators := acmeaccountDescEmail.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(email string) error {
			for _, fn := range fns {
				if err := fn(email); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// acmeaccountDescServerURL is the schema descriptor for server_url field.
	acmeaccountDescServerURL := acmeaccountFields[2].Descriptor()
	// acmeaccount.ServerURLValidator is a validator for the "server_url" field. It is called by the builders before save.
	acmeaccount.ServerURLValidator = func() func(string) error {
		validators := acmeaccountDescServerURL.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(server_url string) error {
			for _, fn := range fns {
				if err := fn(server_url); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// acmeaccountDescCreatedAt is the schema descriptor for created_at field.
	acmeaccountDescCreatedAt := acmeaccountFields[5].Descriptor()
	// acmeaccount.DefaultCreatedAt holds the default value on creation for the created_at field.
	acmeaccount.DefaultCreatedAt = acmeaccountDescCreatedAt.Default.(func() time.Time)
	// acmeaccountDescUpdatedAt is the schema descriptor for updated_at field.
	acmeaccountDescUpdatedAt := acmeaccountFields[6].Descriptor()
	// acmeaccount.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	acmeaccount.DefaultUpdatedAt = acmeaccountDescUpdatedAt.Default.(func() time.Time)
	// acmeaccount.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	acmeaccount.UpdateDefaultUpdatedAt = acmeaccountDescUpdatedAt.UpdateDefault.(func() time.Time)
	// acmeaccountDescID is the schema descriptor for id field.
	acmeaccountDescID := acmeaccountFields[0].Descriptor()
	// acmeaccount.DefaultID holds the default value on creation for the id field.
	acmeaccount.DefaultID = acmeaccountDescID.Default.(int)
	acmecertificateFields := schema.AcmeCertificate{}.Fields()
	_ = acmecertificateFields
	// acmecertificateDescDomain is the schema descriptor for domain field.
	acmecertificateDescDomain := acmecertificateFields[1].Descriptor()
	// acmecertificate.DomainValidator is a validator for the "domain" field. It is called by the builders before save.
	acmecertificate.DomainValidator = func() func(string) error {
		validators := acmecertificateDescDomain.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(domain string) error {
			for _, fn := range fns {
				if err := fn(domain); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// acmecertificateDescChallengeType is the schema descriptor for challenge_type field.
	acmecertificateDescChallengeType := acmecertificateFields[3].Descriptor()
	// acmecertificate.DefaultChallengeType holds the default value on creation for the challenge_type field.
	acmecertificate.DefaultChallengeType = acmecertificateDescChallengeType.Default.(string)
	// acmecertificate.ChallengeTypeValidator is a validator for the "challenge_type" field. It is called by the builders before save.
	acmecertificate.ChallengeTypeValidator = acmecertificateDescChallengeType.Validators[0].(func(string) error)
	// acmecertificateDescDNSProvider is the schema descriptor for dns_provider field.
	acmecertificateDescDNSProvider := acmecertificateFields[4].Descriptor()
	// acmecertificate.DNSProviderValidator is a validator for the "dns_provider" field. It is called by the builders before save.
	acmecertificate.DNSProviderValidator = acmecertificateDescDNSProvider.Validators[0].(func(string) error)
	// acmecertificateDescCertPemPath is the schema descriptor for cert_pem_path field.
	acmecertificateDescCertPemPath := acmecertificateFields[7].Descriptor()
	// acmecertificate.CertPemPathValidator is a validator for the "cert_pem_path" field. It is called by the builders before save.
	acmecertificate.CertPemPathValidator = acmecertificateDescCertPemPath.Validators[0].(func(string) error)
	// acmecertificateDescKeyPemPath is the schema descriptor for key_pem_path field.
	acmecertificateDescKeyPemPath := acmecertificateFields[8].Descriptor()
	// acmecertificate.KeyPemPathValidator is a validator for the "key_pem_path" field. It is called by the builders before save.
	acmecertificate.KeyPemPathValidator = acmecertificateDescKeyPemPath.Validators[0].(func(string) error)
	// acmecertificateDescStatus is the schema descriptor for status field.
	acmecertificateDescStatus := acmecertificateFields[11].Descriptor()
	// acmecertificate.DefaultStatus holds the default value on creation for the status field.
	acmecertificate.DefaultStatus = acmecertificateDescStatus.Default.(string)
	// acmecertificate.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	acmecertificate.StatusValidator = acmecertificateDescStatus.Validators[0].(func(string) error)
	// acmecertificateDescCreatedAt is the schema descriptor for created_at field.
	acmecertificateDescCreatedAt := acmecertificateFields[13].Descriptor()
	// acmecertificate.DefaultCreatedAt holds the default value on creation for the created_at field.
	acmecertificate.DefaultCreatedAt = acmecertificateDescCreatedAt.Default.(func() time.Time)
	// acmecertificateDescUpdatedAt is the schema descriptor for updated_at field.
	acmecertificateDescUpdatedAt := acmecertificateFields[14].Descriptor()
	// acmecertificate.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	acmecertificate.DefaultUpdatedAt = acmecertificateDescUpdatedAt.Default.(func() time.Time)
	// acmecertificate.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	acmecertificate.UpdateDefaultUpdatedAt = acmecertificateDescUpdatedAt.UpdateDefault.(func() time.Time)
	// acmecertificateDescID is the schema descriptor for id field.
	acmecertificateDescID := acmecertificateFields[0].Descriptor()
	// acmecertificate.DefaultID holds the default value on creation for the id field.
	acmecertificate.DefaultID = acmecertificateDescID.Default.(int)
	acmednsproviderconfigFields := schema.AcmeDnsProviderConfig{}.Fields()
	_ = acmednsproviderconfigFields
	// acmednsproviderconfigDescProvider is the schema descriptor for provider field.
	acmednsproviderconfigDescProvider := acmednsproviderconfigFields[1].Descriptor()
	// acmednsproviderconfig.ProviderValidator is a validator for the "provider" field. It is called by the builders before save.
	acmednsproviderconfig.ProviderValidator = func() func(string) error {
		validators := acmednsproviderconfigDescProvider.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(provider string) error {
			for _, fn := range fns {
				if err := fn(provider); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// acmednsproviderconfigDescCreatedAt is the schema descriptor for created_at field.
	acmednsproviderconfigDescCreatedAt := acmednsproviderconfigFields[3].Descriptor()
	// acmednsproviderconfig.DefaultCreatedAt holds the default value on creation for the created_at field.
	acmednsproviderconfig.DefaultCreatedAt = acmednsproviderconfigDescCreatedAt.Default.(func() time.Time)
	// acmednsproviderconfigDescUpdatedAt is the schema descriptor for updated_at field.
	acmednsproviderconfigDescUpdatedAt := acmednsproviderconfigFields[4].Descriptor()
	// acmednsproviderconfig.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	acmednsproviderconfig.DefaultUpdatedAt = acmednsproviderconfigDescUpdatedAt.Default.(func() time.Time)
	// acmednsproviderconfig.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	acmednsproviderconfig.UpdateDefaultUpdatedAt = acmednsproviderconfigDescUpdatedAt.UpdateDefault.(func() time.Time)
	// acmednsproviderconfigDescUpdatedBy is the schema descriptor for updated_by field.
	acmednsproviderconfigDescUpdatedBy := acmednsproviderconfigFields[5].Descriptor()
	// acmednsproviderconfig.UpdatedByValidator is a validator for the "updated_by" field. It is called by the builders before save.
	acmednsproviderconfig.UpdatedByValidator = acmednsproviderconfigDescUpdatedBy.Validators[0].(func(string) error)
	// acmednsproviderconfigDescID is the schema descriptor for id field.
	acmednsproviderconfigDescID := acmednsproviderconfigFields[0].Descriptor()
	// acmednsproviderconfig.DefaultID holds the default value on creation for the id field.
	acmednsproviderconfig.DefaultID = acmednsproviderconfigDescID.Default.(int)
	auditentryFields := schema.AuditEntry{}.Fields()
	_ = auditentryFields
	// auditentryDescAt is the schema descriptor for at field.
	auditentryDescAt := auditentryFields[1].Descriptor()
	// auditentry.DefaultAt holds the default value on creation for the at field.
	auditentry.DefaultAt = auditentryDescAt.Default.(func() time.Time)
	// auditentryDescOperation is the schema descriptor for operation field.
	auditentryDescOperation := auditentryFields[2].Descriptor()
	// auditentry.OperationValidator is a validator for the "operation" field. It is called by the builders before save.
	auditentry.OperationValidator = func() func(string) error {
		validators := auditentryDescOperation.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(operation string) error {
			for _, fn := range fns {
				if err := fn(operation); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// auditentryDescResourceType is the schema descriptor for resource_type field.
	auditentryDescResourceType := auditentryFields[3].Descriptor()
	// auditentry.ResourceTypeValidator is a validator for the "resource_type" field. It is called by the builders before save.
	auditentry.ResourceTypeValidator = auditentryDescResourceType.Validators[0].(func(string) error)
	// auditentryDescResourceID is the schema descriptor for resource_id field.
	auditentryDescResourceID := auditentryFields[4].Descriptor()
	// auditentry.ResourceIDValidator is a validator for the "resource_id" field. It is called by the builders before save.
	auditentry.ResourceIDValidator = auditentryDescResourceID.Validators[0].(func(string) error)
	// auditentryDescActorUserID is the schema descriptor for actor_user_id field.
	auditentryDescActorUserID := auditentryFields[5].Descriptor()
	// auditentry.DefaultActorUserID holds the default value on creation for the actor_user_id field.
	auditentry.DefaultActorUserID = auditentryDescActorUserID.Default.(uint32)
	// auditentryDescActorUsername is the schema descriptor for actor_username field.
	auditentryDescActorUsername := auditentryFields[6].Descriptor()
	// auditentry.ActorUsernameValidator is a validator for the "actor_username" field. It is called by the builders before save.
	auditentry.ActorUsernameValidator = auditentryDescActorUsername.Validators[0].(func(string) error)
	// auditentryDescClientIP is the schema descriptor for client_ip field.
	auditentryDescClientIP := auditentryFields[7].Descriptor()
	// auditentry.ClientIPValidator is a validator for the "client_ip" field. It is called by the builders before save.
	auditentry.ClientIPValidator = auditentryDescClientIP.Validators[0].(func(string) error)
	// auditentryDescUserAgent is the schema descriptor for user_agent field.
	auditentryDescUserAgent := auditentryFields[8].Descriptor()
	// auditentry.UserAgentValidator is a validator for the "user_agent" field. It is called by the builders before save.
	auditentry.UserAgentValidator = auditentryDescUserAgent.Validators[0].(func(string) error)
	// auditentryDescRequestID is the schema descriptor for request_id field.
	auditentryDescRequestID := auditentryFields[9].Descriptor()
	// auditentry.RequestIDValidator is a validator for the "request_id" field. It is called by the builders before save.
	auditentry.RequestIDValidator = auditentryDescRequestID.Validators[0].(func(string) error)
	// auditentryDescStatusCode is the schema descriptor for status_code field.
	auditentryDescStatusCode := auditentryFields[10].Descriptor()
	// auditentry.DefaultStatusCode holds the default value on creation for the status_code field.
	auditentry.DefaultStatusCode = auditentryDescStatusCode.Default.(int32)
	// auditentryDescStatusMessage is the schema descriptor for status_message field.
	auditentryDescStatusMessage := auditentryFields[11].Descriptor()
	// auditentry.StatusMessageValidator is a validator for the "status_message" field. It is called by the builders before save.
	auditentry.StatusMessageValidator = auditentryDescStatusMessage.Validators[0].(func(string) error)
	// auditentryDescDurationMs is the schema descriptor for duration_ms field.
	auditentryDescDurationMs := auditentryFields[14].Descriptor()
	// auditentry.DefaultDurationMs holds the default value on creation for the duration_ms field.
	auditentry.DefaultDurationMs = auditentryDescDurationMs.Default.(int64)
	dkimidentityFields := schema.DkimIdentity{}.Fields()
	_ = dkimidentityFields
	// dkimidentityDescDomain is the schema descriptor for domain field.
	dkimidentityDescDomain := dkimidentityFields[0].Descriptor()
	// dkimidentity.DomainValidator is a validator for the "domain" field. It is called by the builders before save.
	dkimidentity.DomainValidator = func() func(string) error {
		validators := dkimidentityDescDomain.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(domain string) error {
			for _, fn := range fns {
				if err := fn(domain); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// dkimidentityDescSelector is the schema descriptor for selector field.
	dkimidentityDescSelector := dkimidentityFields[1].Descriptor()
	// dkimidentity.SelectorValidator is a validator for the "selector" field. It is called by the builders before save.
	dkimidentity.SelectorValidator = func() func(string) error {
		validators := dkimidentityDescSelector.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(selector string) error {
			for _, fn := range fns {
				if err := fn(selector); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// dkimidentityDescAlgorithm is the schema descriptor for algorithm field.
	dkimidentityDescAlgorithm := dkimidentityFields[2].Descriptor()
	// dkimidentity.AlgorithmValidator is a validator for the "algorithm" field. It is called by the builders before save.
	dkimidentity.AlgorithmValidator = func() func(string) error {
		validators := dkimidentityDescAlgorithm.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(algorithm string) error {
			for _, fn := range fns {
				if err := fn(algorithm); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// dkimidentityDescKeyPath is the schema descriptor for key_path field.
	dkimidentityDescKeyPath := dkimidentityFields[4].Descriptor()
	// dkimidentity.KeyPathValidator is a validator for the "key_path" field. It is called by the builders before save.
	dkimidentity.KeyPathValidator = func() func(string) error {
		validators := dkimidentityDescKeyPath.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(key_path string) error {
			for _, fn := range fns {
				if err := fn(key_path); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// dkimidentityDescActive is the schema descriptor for active field.
	dkimidentityDescActive := dkimidentityFields[5].Descriptor()
	// dkimidentity.DefaultActive holds the default value on creation for the active field.
	dkimidentity.DefaultActive = dkimidentityDescActive.Default.(bool)
	// dkimidentityDescCreatedAt is the schema descriptor for created_at field.
	dkimidentityDescCreatedAt := dkimidentityFields[6].Descriptor()
	// dkimidentity.DefaultCreatedAt holds the default value on creation for the created_at field.
	dkimidentity.DefaultCreatedAt = dkimidentityDescCreatedAt.Default.(func() time.Time)
	// dkimidentityDescUpdatedAt is the schema descriptor for updated_at field.
	dkimidentityDescUpdatedAt := dkimidentityFields[7].Descriptor()
	// dkimidentity.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	dkimidentity.DefaultUpdatedAt = dkimidentityDescUpdatedAt.Default.(func() time.Time)
	// dkimidentity.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	dkimidentity.UpdateDefaultUpdatedAt = dkimidentityDescUpdatedAt.UpdateDefault.(func() time.Time)
	dsneventFields := schema.DsnEvent{}.Fields()
	_ = dsneventFields
	// dsneventDescReceivedAt is the schema descriptor for received_at field.
	dsneventDescReceivedAt := dsneventFields[1].Descriptor()
	// dsnevent.DefaultReceivedAt holds the default value on creation for the received_at field.
	dsnevent.DefaultReceivedAt = dsneventDescReceivedAt.Default.(func() time.Time)
	// dsneventDescVerpToken is the schema descriptor for verp_token field.
	dsneventDescVerpToken := dsneventFields[2].Descriptor()
	// dsnevent.VerpTokenValidator is a validator for the "verp_token" field. It is called by the builders before save.
	dsnevent.VerpTokenValidator = dsneventDescVerpToken.Validators[0].(func(string) error)
	// dsneventDescMessageIDRef is the schema descriptor for message_id_ref field.
	dsneventDescMessageIDRef := dsneventFields[3].Descriptor()
	// dsnevent.MessageIDRefValidator is a validator for the "message_id_ref" field. It is called by the builders before save.
	dsnevent.MessageIDRefValidator = dsneventDescMessageIDRef.Validators[0].(func(string) error)
	// dsneventDescOriginalRecipient is the schema descriptor for original_recipient field.
	dsneventDescOriginalRecipient := dsneventFields[4].Descriptor()
	// dsnevent.OriginalRecipientValidator is a validator for the "original_recipient" field. It is called by the builders before save.
	dsnevent.OriginalRecipientValidator = dsneventDescOriginalRecipient.Validators[0].(func(string) error)
	// dsneventDescFinalRecipient is the schema descriptor for final_recipient field.
	dsneventDescFinalRecipient := dsneventFields[5].Descriptor()
	// dsnevent.FinalRecipientValidator is a validator for the "final_recipient" field. It is called by the builders before save.
	dsnevent.FinalRecipientValidator = dsneventDescFinalRecipient.Validators[0].(func(string) error)
	// dsneventDescAction is the schema descriptor for action field.
	dsneventDescAction := dsneventFields[6].Descriptor()
	// dsnevent.ActionValidator is a validator for the "action" field. It is called by the builders before save.
	dsnevent.ActionValidator = dsneventDescAction.Validators[0].(func(string) error)
	// dsneventDescStatus is the schema descriptor for status field.
	dsneventDescStatus := dsneventFields[7].Descriptor()
	// dsnevent.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	dsnevent.StatusValidator = dsneventDescStatus.Validators[0].(func(string) error)
	// dsneventDescStatusClass is the schema descriptor for status_class field.
	dsneventDescStatusClass := dsneventFields[8].Descriptor()
	// dsnevent.StatusClassValidator is a validator for the "status_class" field. It is called by the builders before save.
	dsnevent.StatusClassValidator = dsneventDescStatusClass.Validators[0].(func(string) error)
	// dsneventDescDiagnosticCode is the schema descriptor for diagnostic_code field.
	dsneventDescDiagnosticCode := dsneventFields[9].Descriptor()
	// dsnevent.DiagnosticCodeValidator is a validator for the "diagnostic_code" field. It is called by the builders before save.
	dsnevent.DiagnosticCodeValidator = dsneventDescDiagnosticCode.Validators[0].(func(string) error)
	// dsneventDescRemoteMta is the schema descriptor for remote_mta field.
	dsneventDescRemoteMta := dsneventFields[10].Descriptor()
	// dsnevent.RemoteMtaValidator is a validator for the "remote_mta" field. It is called by the builders before save.
	dsnevent.RemoteMtaValidator = dsneventDescRemoteMta.Validators[0].(func(string) error)
	// dsneventDescCategory is the schema descriptor for category field.
	dsneventDescCategory := dsneventFields[11].Descriptor()
	// dsnevent.CategoryValidator is a validator for the "category" field. It is called by the builders before save.
	dsnevent.CategoryValidator = dsneventDescCategory.Validators[0].(func(string) error)
	// dsneventDescMailClass is the schema descriptor for mail_class field.
	dsneventDescMailClass := dsneventFields[12].Descriptor()
	// dsnevent.MailClassValidator is a validator for the "mail_class" field. It is called by the builders before save.
	dsnevent.MailClassValidator = dsneventDescMailClass.Validators[0].(func(string) error)
	// dsneventDescTenant is the schema descriptor for tenant field.
	dsneventDescTenant := dsneventFields[13].Descriptor()
	// dsnevent.TenantValidator is a validator for the "tenant" field. It is called by the builders before save.
	dsnevent.TenantValidator = dsneventDescTenant.Validators[0].(func(string) error)
	// dsneventDescCampaign is the schema descriptor for campaign field.
	dsneventDescCampaign := dsneventFields[14].Descriptor()
	// dsnevent.CampaignValidator is a validator for the "campaign" field. It is called by the builders before save.
	dsnevent.CampaignValidator = dsneventDescCampaign.Validators[0].(func(string) error)
	// dsneventDescRawSize is the schema descriptor for raw_size field.
	dsneventDescRawSize := dsneventFields[15].Descriptor()
	// dsnevent.DefaultRawSize holds the default value on creation for the raw_size field.
	dsnevent.DefaultRawSize = dsneventDescRawSize.Default.(int32)
	feedbackreportFields := schema.FeedbackReport{}.Fields()
	_ = feedbackreportFields
	// feedbackreportDescReceivedAt is the schema descriptor for received_at field.
	feedbackreportDescReceivedAt := feedbackreportFields[1].Descriptor()
	// feedbackreport.DefaultReceivedAt holds the default value on creation for the received_at field.
	feedbackreport.DefaultReceivedAt = feedbackreportDescReceivedAt.Default.(func() time.Time)
	// feedbackreportDescFeedbackType is the schema descriptor for feedback_type field.
	feedbackreportDescFeedbackType := feedbackreportFields[2].Descriptor()
	// feedbackreport.FeedbackTypeValidator is a validator for the "feedback_type" field. It is called by the builders before save.
	feedbackreport.FeedbackTypeValidator = func() func(string) error {
		validators := feedbackreportDescFeedbackType.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(feedback_type string) error {
			for _, fn := range fns {
				if err := fn(feedback_type); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// feedbackreportDescUserAgent is the schema descriptor for user_agent field.
	feedbackreportDescUserAgent := feedbackreportFields[3].Descriptor()
	// feedbackreport.UserAgentValidator is a validator for the "user_agent" field. It is called by the builders before save.
	feedbackreport.UserAgentValidator = feedbackreportDescUserAgent.Validators[0].(func(string) error)
	// feedbackreportDescSourceIP is the schema descriptor for source_ip field.
	feedbackreportDescSourceIP := feedbackreportFields[4].Descriptor()
	// feedbackreport.SourceIPValidator is a validator for the "source_ip" field. It is called by the builders before save.
	feedbackreport.SourceIPValidator = feedbackreportDescSourceIP.Validators[0].(func(string) error)
	// feedbackreportDescOriginalRecipient is the schema descriptor for original_recipient field.
	feedbackreportDescOriginalRecipient := feedbackreportFields[5].Descriptor()
	// feedbackreport.OriginalRecipientValidator is a validator for the "original_recipient" field. It is called by the builders before save.
	feedbackreport.OriginalRecipientValidator = feedbackreportDescOriginalRecipient.Validators[0].(func(string) error)
	// feedbackreportDescOriginalSender is the schema descriptor for original_sender field.
	feedbackreportDescOriginalSender := feedbackreportFields[6].Descriptor()
	// feedbackreport.OriginalSenderValidator is a validator for the "original_sender" field. It is called by the builders before save.
	feedbackreport.OriginalSenderValidator = feedbackreportDescOriginalSender.Validators[0].(func(string) error)
	// feedbackreportDescOriginalMessageID is the schema descriptor for original_message_id field.
	feedbackreportDescOriginalMessageID := feedbackreportFields[7].Descriptor()
	// feedbackreport.OriginalMessageIDValidator is a validator for the "original_message_id" field. It is called by the builders before save.
	feedbackreport.OriginalMessageIDValidator = feedbackreportDescOriginalMessageID.Validators[0].(func(string) error)
	// feedbackreportDescReportingMta is the schema descriptor for reporting_mta field.
	feedbackreportDescReportingMta := feedbackreportFields[8].Descriptor()
	// feedbackreport.ReportingMtaValidator is a validator for the "reporting_mta" field. It is called by the builders before save.
	feedbackreport.ReportingMtaValidator = feedbackreportDescReportingMta.Validators[0].(func(string) error)
	globalsettingsFields := schema.GlobalSettings{}.Fields()
	_ = globalsettingsFields
	// globalsettingsDescKumoHTTPListen is the schema descriptor for kumo_http_listen field.
	globalsettingsDescKumoHTTPListen := globalsettingsFields[1].Descriptor()
	// globalsettings.KumoHTTPListenValidator is a validator for the "kumo_http_listen" field. It is called by the builders before save.
	globalsettings.KumoHTTPListenValidator = globalsettingsDescKumoHTTPListen.Validators[0].(func(string) error)
	// globalsettingsDescEsmtpListenAddr is the schema descriptor for esmtp_listen_addr field.
	globalsettingsDescEsmtpListenAddr := globalsettingsFields[2].Descriptor()
	// globalsettings.EsmtpListenAddrValidator is a validator for the "esmtp_listen_addr" field. It is called by the builders before save.
	globalsettings.EsmtpListenAddrValidator = globalsettingsDescEsmtpListenAddr.Validators[0].(func(string) error)
	// globalsettingsDescBounceDomain is the schema descriptor for bounce_domain field.
	globalsettingsDescBounceDomain := globalsettingsFields[5].Descriptor()
	// globalsettings.BounceDomainValidator is a validator for the "bounce_domain" field. It is called by the builders before save.
	globalsettings.BounceDomainValidator = globalsettingsDescBounceDomain.Validators[0].(func(string) error)
	// globalsettingsDescBouncePrefix is the schema descriptor for bounce_prefix field.
	globalsettingsDescBouncePrefix := globalsettingsFields[7].Descriptor()
	// globalsettings.BouncePrefixValidator is a validator for the "bounce_prefix" field. It is called by the builders before save.
	globalsettings.BouncePrefixValidator = globalsettingsDescBouncePrefix.Validators[0].(func(string) error)
	// globalsettingsDescMailClassHeader is the schema descriptor for mail_class_header field.
	globalsettingsDescMailClassHeader := globalsettingsFields[8].Descriptor()
	// globalsettings.MailClassHeaderValidator is a validator for the "mail_class_header" field. It is called by the builders before save.
	globalsettings.MailClassHeaderValidator = globalsettingsDescMailClassHeader.Validators[0].(func(string) error)
	// globalsettingsDescEgressEhloDomain is the schema descriptor for egress_ehlo_domain field.
	globalsettingsDescEgressEhloDomain := globalsettingsFields[9].Descriptor()
	// globalsettings.EgressEhloDomainValidator is a validator for the "egress_ehlo_domain" field. It is called by the builders before save.
	globalsettings.EgressEhloDomainValidator = globalsettingsDescEgressEhloDomain.Validators[0].(func(string) error)
	// globalsettingsDescEgressRetryInterval is the schema descriptor for egress_retry_interval field.
	globalsettingsDescEgressRetryInterval := globalsettingsFields[10].Descriptor()
	// globalsettings.EgressRetryIntervalValidator is a validator for the "egress_retry_interval" field. It is called by the builders before save.
	globalsettings.EgressRetryIntervalValidator = globalsettingsDescEgressRetryInterval.Validators[0].(func(string) error)
	// globalsettingsDescEgressMaxRetryInterval is the schema descriptor for egress_max_retry_interval field.
	globalsettingsDescEgressMaxRetryInterval := globalsettingsFields[11].Descriptor()
	// globalsettings.EgressMaxRetryIntervalValidator is a validator for the "egress_max_retry_interval" field. It is called by the builders before save.
	globalsettings.EgressMaxRetryIntervalValidator = globalsettingsDescEgressMaxRetryInterval.Validators[0].(func(string) error)
	// globalsettingsDescEgressMaxAge is the schema descriptor for egress_max_age field.
	globalsettingsDescEgressMaxAge := globalsettingsFields[12].Descriptor()
	// globalsettings.EgressMaxAgeValidator is a validator for the "egress_max_age" field. It is called by the builders before save.
	globalsettings.EgressMaxAgeValidator = globalsettingsDescEgressMaxAge.Validators[0].(func(string) error)
	// globalsettingsDescRspamdMode is the schema descriptor for rspamd_mode field.
	globalsettingsDescRspamdMode := globalsettingsFields[13].Descriptor()
	// globalsettings.RspamdModeValidator is a validator for the "rspamd_mode" field. It is called by the builders before save.
	globalsettings.RspamdModeValidator = globalsettingsDescRspamdMode.Validators[0].(func(string) error)
	// globalsettingsDescRspamdURL is the schema descriptor for rspamd_url field.
	globalsettingsDescRspamdURL := globalsettingsFields[14].Descriptor()
	// globalsettings.RspamdURLValidator is a validator for the "rspamd_url" field. It is called by the builders before save.
	globalsettings.RspamdURLValidator = globalsettingsDescRspamdURL.Validators[0].(func(string) error)
	// globalsettingsDescHTTPSListen is the schema descriptor for https_listen field.
	globalsettingsDescHTTPSListen := globalsettingsFields[15].Descriptor()
	// globalsettings.HTTPSListenValidator is a validator for the "https_listen" field. It is called by the builders before save.
	globalsettings.HTTPSListenValidator = globalsettingsDescHTTPSListen.Validators[0].(func(string) error)
	// globalsettingsDescHTTPSCertPemPath is the schema descriptor for https_cert_pem_path field.
	globalsettingsDescHTTPSCertPemPath := globalsettingsFields[16].Descriptor()
	// globalsettings.HTTPSCertPemPathValidator is a validator for the "https_cert_pem_path" field. It is called by the builders before save.
	globalsettings.HTTPSCertPemPathValidator = globalsettingsDescHTTPSCertPemPath.Validators[0].(func(string) error)
	// globalsettingsDescHTTPSKeyPemPath is the schema descriptor for https_key_pem_path field.
	globalsettingsDescHTTPSKeyPemPath := globalsettingsFields[17].Descriptor()
	// globalsettings.HTTPSKeyPemPathValidator is a validator for the "https_key_pem_path" field. It is called by the builders before save.
	globalsettings.HTTPSKeyPemPathValidator = globalsettingsDescHTTPSKeyPemPath.Validators[0].(func(string) error)
	// globalsettingsDescUpdatedAt is the schema descriptor for updated_at field.
	globalsettingsDescUpdatedAt := globalsettingsFields[18].Descriptor()
	// globalsettings.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	globalsettings.DefaultUpdatedAt = globalsettingsDescUpdatedAt.Default.(func() time.Time)
	// globalsettings.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	globalsettings.UpdateDefaultUpdatedAt = globalsettingsDescUpdatedAt.UpdateDefault.(func() time.Time)
	// globalsettingsDescUpdatedBy is the schema descriptor for updated_by field.
	globalsettingsDescUpdatedBy := globalsettingsFields[19].Descriptor()
	// globalsettings.UpdatedByValidator is a validator for the "updated_by" field. It is called by the builders before save.
	globalsettings.UpdatedByValidator = globalsettingsDescUpdatedBy.Validators[0].(func(string) error)
	// globalsettingsDescID is the schema descriptor for id field.
	globalsettingsDescID := globalsettingsFields[0].Descriptor()
	// globalsettings.DefaultID holds the default value on creation for the id field.
	globalsettings.DefaultID = globalsettingsDescID.Default.(int)
	listenerconfigFields := schema.ListenerConfig{}.Fields()
	_ = listenerconfigFields
	// listenerconfigDescName is the schema descriptor for name field.
	listenerconfigDescName := listenerconfigFields[0].Descriptor()
	// listenerconfig.NameValidator is a validator for the "name" field. It is called by the builders before save.
	listenerconfig.NameValidator = func() func(string) error {
		validators := listenerconfigDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// listenerconfigDescListenAddr is the schema descriptor for listen_addr field.
	listenerconfigDescListenAddr := listenerconfigFields[1].Descriptor()
	// listenerconfig.ListenAddrValidator is a validator for the "listen_addr" field. It is called by the builders before save.
	listenerconfig.ListenAddrValidator = func() func(string) error {
		validators := listenerconfigDescListenAddr.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(listen_addr string) error {
			for _, fn := range fns {
				if err := fn(listen_addr); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// listenerconfigDescHostname is the schema descriptor for hostname field.
	listenerconfigDescHostname := listenerconfigFields[2].Descriptor()
	// listenerconfig.HostnameValidator is a validator for the "hostname" field. It is called by the builders before save.
	listenerconfig.HostnameValidator = func() func(string) error {
		validators := listenerconfigDescHostname.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(hostname string) error {
			for _, fn := range fns {
				if err := fn(hostname); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// listenerconfigDescTLSEnabled is the schema descriptor for tls_enabled field.
	listenerconfigDescTLSEnabled := listenerconfigFields[3].Descriptor()
	// listenerconfig.DefaultTLSEnabled holds the default value on creation for the tls_enabled field.
	listenerconfig.DefaultTLSEnabled = listenerconfigDescTLSEnabled.Default.(bool)
	// listenerconfigDescTLSCertPemPath is the schema descriptor for tls_cert_pem_path field.
	listenerconfigDescTLSCertPemPath := listenerconfigFields[4].Descriptor()
	// listenerconfig.TLSCertPemPathValidator is a validator for the "tls_cert_pem_path" field. It is called by the builders before save.
	listenerconfig.TLSCertPemPathValidator = listenerconfigDescTLSCertPemPath.Validators[0].(func(string) error)
	// listenerconfigDescTLSKeyPemPath is the schema descriptor for tls_key_pem_path field.
	listenerconfigDescTLSKeyPemPath := listenerconfigFields[5].Descriptor()
	// listenerconfig.TLSKeyPemPathValidator is a validator for the "tls_key_pem_path" field. It is called by the builders before save.
	listenerconfig.TLSKeyPemPathValidator = listenerconfigDescTLSKeyPemPath.Validators[0].(func(string) error)
	// listenerconfigDescRequireAuth is the schema descriptor for require_auth field.
	listenerconfigDescRequireAuth := listenerconfigFields[6].Descriptor()
	// listenerconfig.DefaultRequireAuth holds the default value on creation for the require_auth field.
	listenerconfig.DefaultRequireAuth = listenerconfigDescRequireAuth.Default.(bool)
	// listenerconfigDescMaxMessageSize is the schema descriptor for max_message_size field.
	listenerconfigDescMaxMessageSize := listenerconfigFields[7].Descriptor()
	// listenerconfig.DefaultMaxMessageSize holds the default value on creation for the max_message_size field.
	listenerconfig.DefaultMaxMessageSize = listenerconfigDescMaxMessageSize.Default.(uint64)
	// listenerconfigDescCreatedAt is the schema descriptor for created_at field.
	listenerconfigDescCreatedAt := listenerconfigFields[8].Descriptor()
	// listenerconfig.DefaultCreatedAt holds the default value on creation for the created_at field.
	listenerconfig.DefaultCreatedAt = listenerconfigDescCreatedAt.Default.(func() time.Time)
	// listenerconfigDescUpdatedAt is the schema descriptor for updated_at field.
	listenerconfigDescUpdatedAt := listenerconfigFields[9].Descriptor()
	// listenerconfig.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	listenerconfig.DefaultUpdatedAt = listenerconfigDescUpdatedAt.Default.(func() time.Time)
	// listenerconfig.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	listenerconfig.UpdateDefaultUpdatedAt = listenerconfigDescUpdatedAt.UpdateDefault.(func() time.Time)
	listenerdomainFields := schema.ListenerDomain{}.Fields()
	_ = listenerdomainFields
	// listenerdomainDescDomain is the schema descriptor for domain field.
	listenerdomainDescDomain := listenerdomainFields[0].Descriptor()
	// listenerdomain.DomainValidator is a validator for the "domain" field. It is called by the builders before save.
	listenerdomain.DomainValidator = func() func(string) error {
		validators := listenerdomainDescDomain.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(domain string) error {
			for _, fn := range fns {
				if err := fn(domain); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// listenerdomainDescRelayAllowed is the schema descriptor for relay_allowed field.
	listenerdomainDescRelayAllowed := listenerdomainFields[1].Descriptor()
	// listenerdomain.DefaultRelayAllowed holds the default value on creation for the relay_allowed field.
	listenerdomain.DefaultRelayAllowed = listenerdomainDescRelayAllowed.Default.(bool)
	// listenerdomainDescRequireTLS is the schema descriptor for require_tls field.
	listenerdomainDescRequireTLS := listenerdomainFields[2].Descriptor()
	// listenerdomain.DefaultRequireTLS holds the default value on creation for the require_tls field.
	listenerdomain.DefaultRequireTLS = listenerdomainDescRequireTLS.Default.(bool)
	// listenerdomainDescCreatedAt is the schema descriptor for created_at field.
	listenerdomainDescCreatedAt := listenerdomainFields[3].Descriptor()
	// listenerdomain.DefaultCreatedAt holds the default value on creation for the created_at field.
	listenerdomain.DefaultCreatedAt = listenerdomainDescCreatedAt.Default.(func() time.Time)
	// listenerdomainDescUpdatedAt is the schema descriptor for updated_at field.
	listenerdomainDescUpdatedAt := listenerdomainFields[4].Descriptor()
	// listenerdomain.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	listenerdomain.DefaultUpdatedAt = listenerdomainDescUpdatedAt.Default.(func() time.Time)
	// listenerdomain.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	listenerdomain.UpdateDefaultUpdatedAt = listenerdomainDescUpdatedAt.UpdateDefault.(func() time.Time)
	logeventFields := schema.LogEvent{}.Fields()
	_ = logeventFields
	// logeventDescAt is the schema descriptor for at field.
	logeventDescAt := logeventFields[1].Descriptor()
	// logevent.DefaultAt holds the default value on creation for the at field.
	logevent.DefaultAt = logeventDescAt.Default.(func() time.Time)
	// logeventDescEventType is the schema descriptor for event_type field.
	logeventDescEventType := logeventFields[2].Descriptor()
	// logevent.EventTypeValidator is a validator for the "event_type" field. It is called by the builders before save.
	logevent.EventTypeValidator = logeventDescEventType.Validators[0].(func(string) error)
	// logeventDescQueue is the schema descriptor for queue field.
	logeventDescQueue := logeventFields[3].Descriptor()
	// logevent.QueueValidator is a validator for the "queue" field. It is called by the builders before save.
	logevent.QueueValidator = logeventDescQueue.Validators[0].(func(string) error)
	// logeventDescSender is the schema descriptor for sender field.
	logeventDescSender := logeventFields[4].Descriptor()
	// logevent.SenderValidator is a validator for the "sender" field. It is called by the builders before save.
	logevent.SenderValidator = logeventDescSender.Validators[0].(func(string) error)
	// logeventDescRecipient is the schema descriptor for recipient field.
	logeventDescRecipient := logeventFields[5].Descriptor()
	// logevent.RecipientValidator is a validator for the "recipient" field. It is called by the builders before save.
	logevent.RecipientValidator = logeventDescRecipient.Validators[0].(func(string) error)
	// logeventDescMessageID is the schema descriptor for message_id field.
	logeventDescMessageID := logeventFields[6].Descriptor()
	// logevent.MessageIDValidator is a validator for the "message_id" field. It is called by the builders before save.
	logevent.MessageIDValidator = logeventDescMessageID.Validators[0].(func(string) error)
	// logeventDescResponseCode is the schema descriptor for response_code field.
	logeventDescResponseCode := logeventFields[7].Descriptor()
	// logevent.DefaultResponseCode holds the default value on creation for the response_code field.
	logevent.DefaultResponseCode = logeventDescResponseCode.Default.(int32)
	// logeventDescResponseText is the schema descriptor for response_text field.
	logeventDescResponseText := logeventFields[8].Descriptor()
	// logevent.ResponseTextValidator is a validator for the "response_text" field. It is called by the builders before save.
	logevent.ResponseTextValidator = logeventDescResponseText.Validators[0].(func(string) error)
	// logeventDescSourceIP is the schema descriptor for source_ip field.
	logeventDescSourceIP := logeventFields[9].Descriptor()
	// logevent.SourceIPValidator is a validator for the "source_ip" field. It is called by the builders before save.
	logevent.SourceIPValidator = logeventDescSourceIP.Validators[0].(func(string) error)
	// logeventDescVmta is the schema descriptor for vmta field.
	logeventDescVmta := logeventFields[10].Descriptor()
	// logevent.VmtaValidator is a validator for the "vmta" field. It is called by the builders before save.
	logevent.VmtaValidator = logeventDescVmta.Validators[0].(func(string) error)
	// logeventDescMailClass is the schema descriptor for mail_class field.
	logeventDescMailClass := logeventFields[11].Descriptor()
	// logevent.MailClassValidator is a validator for the "mail_class" field. It is called by the builders before save.
	logevent.MailClassValidator = logeventDescMailClass.Validators[0].(func(string) error)
	loginpolicyFields := schema.LoginPolicy{}.Fields()
	_ = loginpolicyFields
	// loginpolicyDescTargetID is the schema descriptor for target_id field.
	loginpolicyDescTargetID := loginpolicyFields[0].Descriptor()
	// loginpolicy.DefaultTargetID holds the default value on creation for the target_id field.
	loginpolicy.DefaultTargetID = loginpolicyDescTargetID.Default.(uint32)
	// loginpolicyDescValue is the schema descriptor for value field.
	loginpolicyDescValue := loginpolicyFields[3].Descriptor()
	// loginpolicy.ValueValidator is a validator for the "value" field. It is called by the builders before save.
	loginpolicy.ValueValidator = loginpolicyDescValue.Validators[0].(func(string) error)
	// loginpolicyDescTimeWindow is the schema descriptor for time_window field.
	loginpolicyDescTimeWindow := loginpolicyFields[4].Descriptor()
	// loginpolicy.TimeWindowValidator is a validator for the "time_window" field. It is called by the builders before save.
	loginpolicy.TimeWindowValidator = loginpolicyDescTimeWindow.Validators[0].(func(string) error)
	// loginpolicyDescReason is the schema descriptor for reason field.
	loginpolicyDescReason := loginpolicyFields[5].Descriptor()
	// loginpolicy.ReasonValidator is a validator for the "reason" field. It is called by the builders before save.
	loginpolicy.ReasonValidator = loginpolicyDescReason.Validators[0].(func(string) error)
	// loginpolicyDescEnabled is the schema descriptor for enabled field.
	loginpolicyDescEnabled := loginpolicyFields[6].Descriptor()
	// loginpolicy.DefaultEnabled holds the default value on creation for the enabled field.
	loginpolicy.DefaultEnabled = loginpolicyDescEnabled.Default.(bool)
	// loginpolicyDescCreatedBy is the schema descriptor for created_by field.
	loginpolicyDescCreatedBy := loginpolicyFields[7].Descriptor()
	// loginpolicy.DefaultCreatedBy holds the default value on creation for the created_by field.
	loginpolicy.DefaultCreatedBy = loginpolicyDescCreatedBy.Default.(uint32)
	// loginpolicyDescUpdatedBy is the schema descriptor for updated_by field.
	loginpolicyDescUpdatedBy := loginpolicyFields[8].Descriptor()
	// loginpolicy.DefaultUpdatedBy holds the default value on creation for the updated_by field.
	loginpolicy.DefaultUpdatedBy = loginpolicyDescUpdatedBy.Default.(uint32)
	// loginpolicyDescDeletedBy is the schema descriptor for deleted_by field.
	loginpolicyDescDeletedBy := loginpolicyFields[9].Descriptor()
	// loginpolicy.DefaultDeletedBy holds the default value on creation for the deleted_by field.
	loginpolicy.DefaultDeletedBy = loginpolicyDescDeletedBy.Default.(uint32)
	// loginpolicyDescCreatedAt is the schema descriptor for created_at field.
	loginpolicyDescCreatedAt := loginpolicyFields[10].Descriptor()
	// loginpolicy.DefaultCreatedAt holds the default value on creation for the created_at field.
	loginpolicy.DefaultCreatedAt = loginpolicyDescCreatedAt.Default.(func() time.Time)
	// loginpolicyDescUpdatedAt is the schema descriptor for updated_at field.
	loginpolicyDescUpdatedAt := loginpolicyFields[11].Descriptor()
	// loginpolicy.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	loginpolicy.DefaultUpdatedAt = loginpolicyDescUpdatedAt.Default.(func() time.Time)
	// loginpolicy.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	loginpolicy.UpdateDefaultUpdatedAt = loginpolicyDescUpdatedAt.UpdateDefault.(func() time.Time)
	mailclassFields := schema.MailClass{}.Fields()
	_ = mailclassFields
	// mailclassDescName is the schema descriptor for name field.
	mailclassDescName := mailclassFields[0].Descriptor()
	// mailclass.NameValidator is a validator for the "name" field. It is called by the builders before save.
	mailclass.NameValidator = func() func(string) error {
		validators := mailclassDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// mailclassDescDescription is the schema descriptor for description field.
	mailclassDescDescription := mailclassFields[1].Descriptor()
	// mailclass.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	mailclass.DescriptionValidator = mailclassDescDescription.Validators[0].(func(string) error)
	// mailclassDescEnabled is the schema descriptor for enabled field.
	mailclassDescEnabled := mailclassFields[2].Descriptor()
	// mailclass.DefaultEnabled holds the default value on creation for the enabled field.
	mailclass.DefaultEnabled = mailclassDescEnabled.Default.(bool)
	// mailclassDescTargetKind is the schema descriptor for target_kind field.
	mailclassDescTargetKind := mailclassFields[3].Descriptor()
	// mailclass.TargetKindValidator is a validator for the "target_kind" field. It is called by the builders before save.
	mailclass.TargetKindValidator = mailclassDescTargetKind.Validators[0].(func(string) error)
	// mailclassDescTargetRef is the schema descriptor for target_ref field.
	mailclassDescTargetRef := mailclassFields[4].Descriptor()
	// mailclass.TargetRefValidator is a validator for the "target_ref" field. It is called by the builders before save.
	mailclass.TargetRefValidator = mailclassDescTargetRef.Validators[0].(func(string) error)
	// mailclassDescCreatedAt is the schema descriptor for created_at field.
	mailclassDescCreatedAt := mailclassFields[5].Descriptor()
	// mailclass.DefaultCreatedAt holds the default value on creation for the created_at field.
	mailclass.DefaultCreatedAt = mailclassDescCreatedAt.Default.(func() time.Time)
	// mailclassDescUpdatedAt is the schema descriptor for updated_at field.
	mailclassDescUpdatedAt := mailclassFields[6].Descriptor()
	// mailclass.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	mailclass.DefaultUpdatedAt = mailclassDescUpdatedAt.Default.(func() time.Time)
	// mailclass.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	mailclass.UpdateDefaultUpdatedAt = mailclassDescUpdatedAt.UpdateDefault.(func() time.Time)
	mailwebhookFields := schema.MailWebhook{}.Fields()
	_ = mailwebhookFields
	// mailwebhookDescName is the schema descriptor for name field.
	mailwebhookDescName := mailwebhookFields[0].Descriptor()
	// mailwebhook.NameValidator is a validator for the "name" field. It is called by the builders before save.
	mailwebhook.NameValidator = func() func(string) error {
		validators := mailwebhookDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// mailwebhookDescAddress is the schema descriptor for address field.
	mailwebhookDescAddress := mailwebhookFields[1].Descriptor()
	// mailwebhook.AddressValidator is a validator for the "address" field. It is called by the builders before save.
	mailwebhook.AddressValidator = func() func(string) error {
		validators := mailwebhookDescAddress.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(address string) error {
			for _, fn := range fns {
				if err := fn(address); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// mailwebhookDescURL is the schema descriptor for url field.
	mailwebhookDescURL := mailwebhookFields[2].Descriptor()
	// mailwebhook.URLValidator is a validator for the "url" field. It is called by the builders before save.
	mailwebhook.URLValidator = func() func(string) error {
		validators := mailwebhookDescURL.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(url string) error {
			for _, fn := range fns {
				if err := fn(url); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// mailwebhookDescSecret is the schema descriptor for secret field.
	mailwebhookDescSecret := mailwebhookFields[3].Descriptor()
	// mailwebhook.SecretValidator is a validator for the "secret" field. It is called by the builders before save.
	mailwebhook.SecretValidator = mailwebhookDescSecret.Validators[0].(func(string) error)
	// mailwebhookDescEnabled is the schema descriptor for enabled field.
	mailwebhookDescEnabled := mailwebhookFields[4].Descriptor()
	// mailwebhook.DefaultEnabled holds the default value on creation for the enabled field.
	mailwebhook.DefaultEnabled = mailwebhookDescEnabled.Default.(bool)
	// mailwebhookDescCreatedAt is the schema descriptor for created_at field.
	mailwebhookDescCreatedAt := mailwebhookFields[5].Descriptor()
	// mailwebhook.DefaultCreatedAt holds the default value on creation for the created_at field.
	mailwebhook.DefaultCreatedAt = mailwebhookDescCreatedAt.Default.(func() time.Time)
	// mailwebhookDescUpdatedAt is the schema descriptor for updated_at field.
	mailwebhookDescUpdatedAt := mailwebhookFields[6].Descriptor()
	// mailwebhook.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	mailwebhook.DefaultUpdatedAt = mailwebhookDescUpdatedAt.Default.(func() time.Time)
	// mailwebhook.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	mailwebhook.UpdateDefaultUpdatedAt = mailwebhookDescUpdatedAt.UpdateDefault.(func() time.Time)
	metricsnapshotFields := schema.MetricSnapshot{}.Fields()
	_ = metricsnapshotFields
	// metricsnapshotDescAt is the schema descriptor for at field.
	metricsnapshotDescAt := metricsnapshotFields[1].Descriptor()
	// metricsnapshot.DefaultAt holds the default value on creation for the at field.
	metricsnapshot.DefaultAt = metricsnapshotDescAt.Default.(func() time.Time)
	// metricsnapshotDescQueue is the schema descriptor for queue field.
	metricsnapshotDescQueue := metricsnapshotFields[2].Descriptor()
	// metricsnapshot.QueueValidator is a validator for the "queue" field. It is called by the builders before save.
	metricsnapshot.QueueValidator = metricsnapshotDescQueue.Validators[0].(func(string) error)
	// metricsnapshotDescQueueSize is the schema descriptor for queue_size field.
	metricsnapshotDescQueueSize := metricsnapshotFields[3].Descriptor()
	// metricsnapshot.DefaultQueueSize holds the default value on creation for the queue_size field.
	metricsnapshot.DefaultQueueSize = metricsnapshotDescQueueSize.Default.(uint64)
	// metricsnapshotDescDeliveredTotal is the schema descriptor for delivered_total field.
	metricsnapshotDescDeliveredTotal := metricsnapshotFields[4].Descriptor()
	// metricsnapshot.DefaultDeliveredTotal holds the default value on creation for the delivered_total field.
	metricsnapshot.DefaultDeliveredTotal = metricsnapshotDescDeliveredTotal.Default.(uint64)
	// metricsnapshotDescFailedTotal is the schema descriptor for failed_total field.
	metricsnapshotDescFailedTotal := metricsnapshotFields[5].Descriptor()
	// metricsnapshot.DefaultFailedTotal holds the default value on creation for the failed_total field.
	metricsnapshot.DefaultFailedTotal = metricsnapshotDescFailedTotal.Default.(uint64)
	// metricsnapshotDescDeferredTotal is the schema descriptor for deferred_total field.
	metricsnapshotDescDeferredTotal := metricsnapshotFields[6].Descriptor()
	// metricsnapshot.DefaultDeferredTotal holds the default value on creation for the deferred_total field.
	metricsnapshot.DefaultDeferredTotal = metricsnapshotDescDeferredTotal.Default.(uint64)
	// metricsnapshotDescDeliveryRatePerMin is the schema descriptor for delivery_rate_per_min field.
	metricsnapshotDescDeliveryRatePerMin := metricsnapshotFields[7].Descriptor()
	// metricsnapshot.DefaultDeliveryRatePerMin holds the default value on creation for the delivery_rate_per_min field.
	metricsnapshot.DefaultDeliveryRatePerMin = metricsnapshotDescDeliveryRatePerMin.Default.(float64)
	// metricsnapshotDescSuspended is the schema descriptor for suspended field.
	metricsnapshotDescSuspended := metricsnapshotFields[8].Descriptor()
	// metricsnapshot.DefaultSuspended holds the default value on creation for the suspended field.
	metricsnapshot.DefaultSuspended = metricsnapshotDescSuspended.Default.(bool)
	mfacredentialFields := schema.MfaCredential{}.Fields()
	_ = mfacredentialFields
	// mfacredentialDescSecret is the schema descriptor for secret field.
	mfacredentialDescSecret := mfacredentialFields[2].Descriptor()
	// mfacredential.SecretValidator is a validator for the "secret" field. It is called by the builders before save.
	mfacredential.SecretValidator = mfacredentialDescSecret.Validators[0].(func(string) error)
	// mfacredentialDescLabel is the schema descriptor for label field.
	mfacredentialDescLabel := mfacredentialFields[3].Descriptor()
	// mfacredential.LabelValidator is a validator for the "label" field. It is called by the builders before save.
	mfacredential.LabelValidator = mfacredentialDescLabel.Validators[0].(func(string) error)
	// mfacredentialDescSignCount is the schema descriptor for sign_count field.
	mfacredentialDescSignCount := mfacredentialFields[5].Descriptor()
	// mfacredential.DefaultSignCount holds the default value on creation for the sign_count field.
	mfacredential.DefaultSignCount = mfacredentialDescSignCount.Default.(uint32)
	// mfacredentialDescCreatedAt is the schema descriptor for created_at field.
	mfacredentialDescCreatedAt := mfacredentialFields[6].Descriptor()
	// mfacredential.DefaultCreatedAt holds the default value on creation for the created_at field.
	mfacredential.DefaultCreatedAt = mfacredentialDescCreatedAt.Default.(func() time.Time)
	// mfacredentialDescUpdatedAt is the schema descriptor for updated_at field.
	mfacredentialDescUpdatedAt := mfacredentialFields[7].Descriptor()
	// mfacredential.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	mfacredential.DefaultUpdatedAt = mfacredentialDescUpdatedAt.Default.(func() time.Time)
	// mfacredential.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	mfacredential.UpdateDefaultUpdatedAt = mfacredentialDescUpdatedAt.UpdateDefault.(func() time.Time)
	policyhistoryFields := schema.PolicyHistory{}.Fields()
	_ = policyhistoryFields
	// policyhistoryDescSha256 is the schema descriptor for sha256 field.
	policyhistoryDescSha256 := policyhistoryFields[1].Descriptor()
	// policyhistory.Sha256Validator is a validator for the "sha256" field. It is called by the builders before save.
	policyhistory.Sha256Validator = func() func(string) error {
		validators := policyhistoryDescSha256.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(sha256 string) error {
			for _, fn := range fns {
				if err := fn(sha256); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// policyhistoryDescNote is the schema descriptor for note field.
	policyhistoryDescNote := policyhistoryFields[2].Descriptor()
	// policyhistory.NoteValidator is a validator for the "note" field. It is called by the builders before save.
	policyhistory.NoteValidator = policyhistoryDescNote.Validators[0].(func(string) error)
	// policyhistoryDescActorUserID is the schema descriptor for actor_user_id field.
	policyhistoryDescActorUserID := policyhistoryFields[3].Descriptor()
	// policyhistory.DefaultActorUserID holds the default value on creation for the actor_user_id field.
	policyhistory.DefaultActorUserID = policyhistoryDescActorUserID.Default.(uint32)
	// policyhistoryDescAppliedAt is the schema descriptor for applied_at field.
	policyhistoryDescAppliedAt := policyhistoryFields[4].Descriptor()
	// policyhistory.DefaultAppliedAt holds the default value on creation for the applied_at field.
	policyhistory.DefaultAppliedAt = policyhistoryDescAppliedAt.Default.(func() time.Time)
	roleFields := schema.Role{}.Fields()
	_ = roleFields
	// roleDescCode is the schema descriptor for code field.
	roleDescCode := roleFields[0].Descriptor()
	// role.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	role.CodeValidator = func() func(string) error {
		validators := roleDescCode.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(code string) error {
			for _, fn := range fns {
				if err := fn(code); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// roleDescName is the schema descriptor for name field.
	roleDescName := roleFields[1].Descriptor()
	// role.NameValidator is a validator for the "name" field. It is called by the builders before save.
	role.NameValidator = func() func(string) error {
		validators := roleDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// roleDescDescription is the schema descriptor for description field.
	roleDescDescription := roleFields[2].Descriptor()
	// role.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	role.DescriptionValidator = roleDescDescription.Validators[0].(func(string) error)
	// roleDescSystem is the schema descriptor for system field.
	roleDescSystem := roleFields[4].Descriptor()
	// role.DefaultSystem holds the default value on creation for the system field.
	role.DefaultSystem = roleDescSystem.Default.(bool)
	// roleDescCreatedAt is the schema descriptor for created_at field.
	roleDescCreatedAt := roleFields[5].Descriptor()
	// role.DefaultCreatedAt holds the default value on creation for the created_at field.
	role.DefaultCreatedAt = roleDescCreatedAt.Default.(func() time.Time)
	// roleDescUpdatedAt is the schema descriptor for updated_at field.
	roleDescUpdatedAt := roleFields[6].Descriptor()
	// role.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	role.DefaultUpdatedAt = roleDescUpdatedAt.Default.(func() time.Time)
	// role.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	role.UpdateDefaultUpdatedAt = roleDescUpdatedAt.UpdateDefault.(func() time.Time)
	routingruleFields := schema.RoutingRule{}.Fields()
	_ = routingruleFields
	// routingruleDescName is the schema descriptor for name field.
	routingruleDescName := routingruleFields[0].Descriptor()
	// routingrule.NameValidator is a validator for the "name" field. It is called by the builders before save.
	routingrule.NameValidator = func() func(string) error {
		validators := routingruleDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// routingruleDescPriority is the schema descriptor for priority field.
	routingruleDescPriority := routingruleFields[1].Descriptor()
	// routingrule.DefaultPriority holds the default value on creation for the priority field.
	routingrule.DefaultPriority = routingruleDescPriority.Default.(int32)
	// routingruleDescEnabled is the schema descriptor for enabled field.
	routingruleDescEnabled := routingruleFields[2].Descriptor()
	// routingrule.DefaultEnabled holds the default value on creation for the enabled field.
	routingrule.DefaultEnabled = routingruleDescEnabled.Default.(bool)
	// routingruleDescCreatedAt is the schema descriptor for created_at field.
	routingruleDescCreatedAt := routingruleFields[3].Descriptor()
	// routingrule.DefaultCreatedAt holds the default value on creation for the created_at field.
	routingrule.DefaultCreatedAt = routingruleDescCreatedAt.Default.(func() time.Time)
	// routingruleDescUpdatedAt is the schema descriptor for updated_at field.
	routingruleDescUpdatedAt := routingruleFields[4].Descriptor()
	// routingrule.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	routingrule.DefaultUpdatedAt = routingruleDescUpdatedAt.Default.(func() time.Time)
	// routingrule.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	routingrule.UpdateDefaultUpdatedAt = routingruleDescUpdatedAt.UpdateDefault.(func() time.Time)
	ruleconditionFields := schema.RuleCondition{}.Fields()
	_ = ruleconditionFields
	// ruleconditionDescField is the schema descriptor for field field.
	ruleconditionDescField := ruleconditionFields[0].Descriptor()
	// rulecondition.FieldValidator is a validator for the "field" field. It is called by the builders before save.
	rulecondition.FieldValidator = func() func(string) error {
		validators := ruleconditionDescField.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(field string) error {
			for _, fn := range fns {
				if err := fn(field); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// ruleconditionDescOp is the schema descriptor for op field.
	ruleconditionDescOp := ruleconditionFields[1].Descriptor()
	// rulecondition.OpValidator is a validator for the "op" field. It is called by the builders before save.
	rulecondition.OpValidator = func() func(string) error {
		validators := ruleconditionDescOp.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(_op string) error {
			for _, fn := range fns {
				if err := fn(_op); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// ruleconditionDescValue is the schema descriptor for value field.
	ruleconditionDescValue := ruleconditionFields[2].Descriptor()
	// rulecondition.ValueValidator is a validator for the "value" field. It is called by the builders before save.
	rulecondition.ValueValidator = func() func(string) error {
		validators := ruleconditionDescValue.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(value string) error {
			for _, fn := range fns {
				if err := fn(value); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	ruletargetFields := schema.RuleTarget{}.Fields()
	_ = ruletargetFields
	// ruletargetDescKind is the schema descriptor for kind field.
	ruletargetDescKind := ruletargetFields[0].Descriptor()
	// ruletarget.KindValidator is a validator for the "kind" field. It is called by the builders before save.
	ruletarget.KindValidator = func() func(string) error {
		validators := ruletargetDescKind.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(kind string) error {
			for _, fn := range fns {
				if err := fn(kind); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// ruletargetDescRef is the schema descriptor for ref field.
	ruletargetDescRef := ruletargetFields[1].Descriptor()
	// ruletarget.RefValidator is a validator for the "ref" field. It is called by the builders before save.
	ruletarget.RefValidator = ruletargetDescRef.Validators[0].(func(string) error)
	// ruletargetDescRejectCode is the schema descriptor for reject_code field.
	ruletargetDescRejectCode := ruletargetFields[2].Descriptor()
	// ruletarget.DefaultRejectCode holds the default value on creation for the reject_code field.
	ruletarget.DefaultRejectCode = ruletargetDescRejectCode.Default.(uint32)
	// ruletargetDescRejectText is the schema descriptor for reject_text field.
	ruletargetDescRejectText := ruletargetFields[3].Descriptor()
	// ruletarget.RejectTextValidator is a validator for the "reject_text" field. It is called by the builders before save.
	ruletarget.RejectTextValidator = ruletargetDescRejectText.Validators[0].(func(string) error)
	suppressionentryFields := schema.SuppressionEntry{}.Fields()
	_ = suppressionentryFields
	// suppressionentryDescAddress is the schema descriptor for address field.
	suppressionentryDescAddress := suppressionentryFields[0].Descriptor()
	// suppressionentry.AddressValidator is a validator for the "address" field. It is called by the builders before save.
	suppressionentry.AddressValidator = func() func(string) error {
		validators := suppressionentryDescAddress.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(address string) error {
			for _, fn := range fns {
				if err := fn(address); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// suppressionentryDescScope is the schema descriptor for scope field.
	suppressionentryDescScope := suppressionentryFields[1].Descriptor()
	// suppressionentry.DefaultScope holds the default value on creation for the scope field.
	suppressionentry.DefaultScope = suppressionentryDescScope.Default.(string)
	// suppressionentry.ScopeValidator is a validator for the "scope" field. It is called by the builders before save.
	suppressionentry.ScopeValidator = func() func(string) error {
		validators := suppressionentryDescScope.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(scope string) error {
			for _, fn := range fns {
				if err := fn(scope); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// suppressionentryDescReason is the schema descriptor for reason field.
	suppressionentryDescReason := suppressionentryFields[2].Descriptor()
	// suppressionentry.DefaultReason holds the default value on creation for the reason field.
	suppressionentry.DefaultReason = suppressionentryDescReason.Default.(string)
	// suppressionentry.ReasonValidator is a validator for the "reason" field. It is called by the builders before save.
	suppressionentry.ReasonValidator = func() func(string) error {
		validators := suppressionentryDescReason.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(reason string) error {
			for _, fn := range fns {
				if err := fn(reason); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// suppressionentryDescNote is the schema descriptor for note field.
	suppressionentryDescNote := suppressionentryFields[3].Descriptor()
	// suppressionentry.NoteValidator is a validator for the "note" field. It is called by the builders before save.
	suppressionentry.NoteValidator = suppressionentryDescNote.Validators[0].(func(string) error)
	// suppressionentryDescCreatedAt is the schema descriptor for created_at field.
	suppressionentryDescCreatedAt := suppressionentryFields[4].Descriptor()
	// suppressionentry.DefaultCreatedAt holds the default value on creation for the created_at field.
	suppressionentry.DefaultCreatedAt = suppressionentryDescCreatedAt.Default.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[0].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = func() func(string) error {
		validators := userDescUsername.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(username string) error {
			for _, fn := range fns {
				if err := fn(username); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[1].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = func() func(string) error {
		validators := userDescEmail.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(email string) error {
			for _, fn := range fns {
				if err := fn(email); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescDisplayName is the schema descriptor for display_name field.
	userDescDisplayName := userFields[2].Descriptor()
	// user.DisplayNameValidator is a validator for the "display_name" field. It is called by the builders before save.
	user.DisplayNameValidator = userDescDisplayName.Validators[0].(func(string) error)
	// userDescPasswordHash is the schema descriptor for password_hash field.
	userDescPasswordHash := userFields[3].Descriptor()
	// user.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	user.PasswordHashValidator = func() func(string) error {
		validators := userDescPasswordHash.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(password_hash string) error {
			for _, fn := range fns {
				if err := fn(password_hash); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescActive is the schema descriptor for active field.
	userDescActive := userFields[4].Descriptor()
	// user.DefaultActive holds the default value on creation for the active field.
	user.DefaultActive = userDescActive.Default.(bool)
	// userDescLastLoginIP is the schema descriptor for last_login_ip field.
	userDescLastLoginIP := userFields[7].Descriptor()
	// user.LastLoginIPValidator is a validator for the "last_login_ip" field. It is called by the builders before save.
	user.LastLoginIPValidator = userDescLastLoginIP.Validators[0].(func(string) error)
	// userDescFailedLogins is the schema descriptor for failed_logins field.
	userDescFailedLogins := userFields[8].Descriptor()
	// user.DefaultFailedLogins holds the default value on creation for the failed_logins field.
	user.DefaultFailedLogins = userDescFailedLogins.Default.(int)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[10].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[11].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	virtualmtaFields := schema.VirtualMta{}.Fields()
	_ = virtualmtaFields
	// virtualmtaDescName is the schema descriptor for name field.
	virtualmtaDescName := virtualmtaFields[0].Descriptor()
	// virtualmta.NameValidator is a validator for the "name" field. It is called by the builders before save.
	virtualmta.NameValidator = func() func(string) error {
		validators := virtualmtaDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// virtualmtaDescHeloName is the schema descriptor for helo_name field.
	virtualmtaDescHeloName := virtualmtaFields[2].Descriptor()
	// virtualmta.HeloNameValidator is a validator for the "helo_name" field. It is called by the builders before save.
	virtualmta.HeloNameValidator = virtualmtaDescHeloName.Validators[0].(func(string) error)
	// virtualmtaDescMaxConnections is the schema descriptor for max_connections field.
	virtualmtaDescMaxConnections := virtualmtaFields[3].Descriptor()
	// virtualmta.DefaultMaxConnections holds the default value on creation for the max_connections field.
	virtualmta.DefaultMaxConnections = virtualmtaDescMaxConnections.Default.(uint32)
	// virtualmtaDescMaxMessagesPerConnection is the schema descriptor for max_messages_per_connection field.
	virtualmtaDescMaxMessagesPerConnection := virtualmtaFields[4].Descriptor()
	// virtualmta.DefaultMaxMessagesPerConnection holds the default value on creation for the max_messages_per_connection field.
	virtualmta.DefaultMaxMessagesPerConnection = virtualmtaDescMaxMessagesPerConnection.Default.(uint32)
	// virtualmtaDescConnectTimeout is the schema descriptor for connect_timeout field.
	virtualmtaDescConnectTimeout := virtualmtaFields[5].Descriptor()
	// virtualmta.DefaultConnectTimeout holds the default value on creation for the connect_timeout field.
	virtualmta.DefaultConnectTimeout = virtualmtaDescConnectTimeout.Default.(uint32)
	// virtualmtaDescProviderProfile is the schema descriptor for provider_profile field.
	virtualmtaDescProviderProfile := virtualmtaFields[6].Descriptor()
	// virtualmta.DefaultProviderProfile holds the default value on creation for the provider_profile field.
	virtualmta.DefaultProviderProfile = virtualmtaDescProviderProfile.Default.(string)
	// virtualmta.ProviderProfileValidator is a validator for the "provider_profile" field. It is called by the builders before save.
	virtualmta.ProviderProfileValidator = virtualmtaDescProviderProfile.Validators[0].(func(string) error)
	// virtualmtaDescCreatedAt is the schema descriptor for created_at field.
	virtualmtaDescCreatedAt := virtualmtaFields[7].Descriptor()
	// virtualmta.DefaultCreatedAt holds the default value on creation for the created_at field.
	virtualmta.DefaultCreatedAt = virtualmtaDescCreatedAt.Default.(func() time.Time)
	// virtualmtaDescUpdatedAt is the schema descriptor for updated_at field.
	virtualmtaDescUpdatedAt := virtualmtaFields[8].Descriptor()
	// virtualmta.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	virtualmta.DefaultUpdatedAt = virtualmtaDescUpdatedAt.Default.(func() time.Time)
	// virtualmta.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	virtualmta.UpdateDefaultUpdatedAt = virtualmtaDescUpdatedAt.UpdateDefault.(func() time.Time)
	virtualmtagroupFields := schema.VirtualMtaGroup{}.Fields()
	_ = virtualmtagroupFields
	// virtualmtagroupDescName is the schema descriptor for name field.
	virtualmtagroupDescName := virtualmtagroupFields[0].Descriptor()
	// virtualmtagroup.NameValidator is a validator for the "name" field. It is called by the builders before save.
	virtualmtagroup.NameValidator = func() func(string) error {
		validators := virtualmtagroupDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// virtualmtagroupDescDescription is the schema descriptor for description field.
	virtualmtagroupDescDescription := virtualmtagroupFields[1].Descriptor()
	// virtualmtagroup.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	virtualmtagroup.DescriptionValidator = virtualmtagroupDescDescription.Validators[0].(func(string) error)
	// virtualmtagroupDescEnabled is the schema descriptor for enabled field.
	virtualmtagroupDescEnabled := virtualmtagroupFields[2].Descriptor()
	// virtualmtagroup.DefaultEnabled holds the default value on creation for the enabled field.
	virtualmtagroup.DefaultEnabled = virtualmtagroupDescEnabled.Default.(bool)
	// virtualmtagroupDescCreatedAt is the schema descriptor for created_at field.
	virtualmtagroupDescCreatedAt := virtualmtagroupFields[3].Descriptor()
	// virtualmtagroup.DefaultCreatedAt holds the default value on creation for the created_at field.
	virtualmtagroup.DefaultCreatedAt = virtualmtagroupDescCreatedAt.Default.(func() time.Time)
	// virtualmtagroupDescUpdatedAt is the schema descriptor for updated_at field.
	virtualmtagroupDescUpdatedAt := virtualmtagroupFields[4].Descriptor()
	// virtualmtagroup.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	virtualmtagroup.DefaultUpdatedAt = virtualmtagroupDescUpdatedAt.Default.(func() time.Time)
	// virtualmtagroup.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	virtualmtagroup.UpdateDefaultUpdatedAt = virtualmtagroupDescUpdatedAt.UpdateDefault.(func() time.Time)
	virtualmtagroupmemberFields := schema.VirtualMtaGroupMember{}.Fields()
	_ = virtualmtagroupmemberFields
	// virtualmtagroupmemberDescWeight is the schema descriptor for weight field.
	virtualmtagroupmemberDescWeight := virtualmtagroupmemberFields[0].Descriptor()
	// virtualmtagroupmember.DefaultWeight holds the default value on creation for the weight field.
	virtualmtagroupmember.DefaultWeight = virtualmtagroupmemberDescWeight.Default.(uint32)
	// virtualmtagroupmemberDescPriority is the schema descriptor for priority field.
	virtualmtagroupmemberDescPriority := virtualmtagroupmemberFields[1].Descriptor()
	// virtualmtagroupmember.DefaultPriority holds the default value on creation for the priority field.
	virtualmtagroupmember.DefaultPriority = virtualmtagroupmemberDescPriority.Default.(uint32)
	// virtualmtagroupmemberDescEnabled is the schema descriptor for enabled field.
	virtualmtagroupmemberDescEnabled := virtualmtagroupmemberFields[2].Descriptor()
	// virtualmtagroupmember.DefaultEnabled holds the default value on creation for the enabled field.
	virtualmtagroupmember.DefaultEnabled = virtualmtagroupmemberDescEnabled.Default.(bool)
}
