// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/menta2k/iris/backend/app/admin/service/internal/data/ent/predicate"
	"github.com/menta2k/iris/backend/app/admin/service/internal/data/ent/virtualmta"
)

// VirtualMtaDelete is the builder for deleting a VirtualMta entity.
type VirtualMtaDelete struct {
	config
	hooks    []Hook
	mutation *VirtualMtaMutation
}

// Where appends a list predicates to the VirtualMtaDelete builder.
func (_d *VirtualMtaDelete) Where(ps ...predicate.VirtualMta) *VirtualMtaDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *VirtualMtaDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *VirtualMtaDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *VirtualMtaDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(virtualmta.Table, sqlgraph.NewFieldSpec(virtualmta.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// VirtualMtaDeleteOne is the builder for deleting a single VirtualMta entity.
type VirtualMtaDeleteOne struct {
	_d *VirtualMtaDelete
}

// Where appends a list predicates to the VirtualMtaDelete builder.
func (_d *VirtualMtaDeleteOne) Where(ps ...predicate.VirtualMta) *VirtualMtaDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *VirtualMtaDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{virtualmta.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *VirtualMtaDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
