version: v2

clean: false

managed:
  enabled: true

  disable:
    - module: buf.build/googleapis/googleapis
    - module: 'buf.build/envoyproxy/protoc-gen-validate'
    - module: 'buf.build/kratos/apis'
    - module: 'buf.build/gnostic/gnostic'
    - module: 'buf.build/tx7do/pagination'

inputs:
  - directory: protos

plugins:
  - local: protoc-gen-openapi
    out: ../app/admin/service/cmd/server/assets
    opt:
      - title=Go-Kumo-UI Admin API
      - version=1.0
      - default_response=false
