// Code generated by ent, DO NOT EDIT.

package metricsnapshot

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/menta2k/iris/backend/app/admin/service/internal/data/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldLTE(FieldID, id))
}

// At applies equality check predicate on the "at" field. It's identical to AtEQ.
func At(v time.Time) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldEQ(FieldAt, v))
}

// Queue applies equality check predicate on the "queue" field. It's identical to QueueEQ.
func Queue(v string) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldEQ(FieldQueue, v))
}

// QueueSize applies equality check predicate on the "queue_size" field. It's identical to QueueSizeEQ.
func QueueSize(v uint64) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldEQ(FieldQueueSize, v))
}

// DeliveredTotal applies equality check predicate on the "delivered_total" field. It's identical to DeliveredTotalEQ.
func DeliveredTotal(v uint64) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldEQ(FieldDeliveredTotal, v))
}

// FailedTotal applies equality check predicate on the "failed_total" field. It's identical to FailedTotalEQ.
func FailedTotal(v uint64) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldEQ(FieldFailedTotal, v))
}

// DeferredTotal applies equality check predicate on the "deferred_total" field. It's identical to DeferredTotalEQ.
func DeferredTotal(v uint64) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldEQ(FieldDeferredTotal, v))
}

// DeliveryRatePerMin applies equality check predicate on the "delivery_rate_per_min" field. It's identical to DeliveryRatePerMinEQ.
func DeliveryRatePerMin(v float64) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldEQ(FieldDeliveryRatePerMin, v))
}

// Suspended applies equality check predicate on the "suspended" field. It's identical to SuspendedEQ.
func Suspended(v bool) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldEQ(FieldSuspended, v))
}

// AtEQ applies the EQ predicate on the "at" field.
func AtEQ(v time.Time) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldEQ(FieldAt, v))
}

// AtNEQ applies the NEQ predicate on the "at" field.
func AtNEQ(v time.Time) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldNEQ(FieldAt, v))
}

// AtIn applies the In predicate on the "at" field.
func AtIn(vs ...time.Time) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldIn(FieldAt, vs...))
}

// AtNotIn applies the NotIn predicate on the "at" field.
func AtNotIn(vs ...time.Time) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldNotIn(FieldAt, vs...))
}

// AtGT applies the GT predicate on the "at" field.
func AtGT(v time.Time) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldGT(FieldAt, v))
}

// AtGTE applies the GTE predicate on the "at" field.
func AtGTE(v time.Time) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldGTE(FieldAt, v))
}

// AtLT applies the LT predicate on the "at" field.
func AtLT(v time.Time) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldLT(FieldAt, v))
}

// AtLTE applies the LTE predicate on the "at" field.
func AtLTE(v time.Time) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldLTE(FieldAt, v))
}

// QueueEQ applies the EQ predicate on the "queue" field.
func QueueEQ(v string) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldEQ(FieldQueue, v))
}

// QueueNEQ applies the NEQ predicate on the "queue" field.
func QueueNEQ(v string) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldNEQ(FieldQueue, v))
}

// QueueIn applies the In predicate on the "queue" field.
func QueueIn(vs ...string) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldIn(FieldQueue, vs...))
}

// QueueNotIn applies the NotIn predicate on the "queue" field.
func QueueNotIn(vs ...string) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldNotIn(FieldQueue, vs...))
}

// QueueGT applies the GT predicate on the "queue" field.
func QueueGT(v string) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldGT(FieldQueue, v))
}

// QueueGTE applies the GTE predicate on the "queue" field.
func QueueGTE(v string) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldGTE(FieldQueue, v))
}

// QueueLT applies the LT predicate on the "queue" field.
func QueueLT(v string) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldLT(FieldQueue, v))
}

// QueueLTE applies the LTE predicate on the "queue" field.
func QueueLTE(v string) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldLTE(FieldQueue, v))
}

// QueueContains applies the Contains predicate on the "queue" field.
func QueueContains(v string) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldContains(FieldQueue, v))
}

// QueueHasPrefix applies the HasPrefix predicate on the "queue" field.
func QueueHasPrefix(v string) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldHasPrefix(FieldQueue, v))
}

// QueueHasSuffix applies the HasSuffix predicate on the "queue" field.
func QueueHasSuffix(v string) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldHasSuffix(FieldQueue, v))
}

// QueueIsNil applies the IsNil predicate on the "queue" field.
func QueueIsNil() predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldIsNull(FieldQueue))
}

// QueueNotNil applies the NotNil predicate on the "queue" field.
func QueueNotNil() predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldNotNull(FieldQueue))
}

// QueueEqualFold applies the EqualFold predicate on the "queue" field.
func QueueEqualFold(v string) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldEqualFold(FieldQueue, v))
}

// QueueContainsFold applies the ContainsFold predicate on the "queue" field.
func QueueContainsFold(v string) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldContainsFold(FieldQueue, v))
}

// QueueSizeEQ applies the EQ predicate on the "queue_size" field.
func QueueSizeEQ(v uint64) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldEQ(FieldQueueSize, v))
}

// QueueSizeNEQ applies the NEQ predicate on the "queue_size" field.
func QueueSizeNEQ(v uint64) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldNEQ(FieldQueueSize, v))
}

// QueueSizeIn applies the In predicate on the "queue_size" field.
func QueueSizeIn(vs ...uint64) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldIn(FieldQueueSize, vs...))
}

// QueueSizeNotIn applies the NotIn predicate on the "queue_size" field.
func QueueSizeNotIn(vs ...uint64) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldNotIn(FieldQueueSize, vs...))
}

// QueueSizeGT applies the GT predicate on the "queue_size" field.
func QueueSizeGT(v uint64) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldGT(FieldQueueSize, v))
}

// QueueSizeGTE applies the GTE predicate on the "queue_size" field.
func QueueSizeGTE(v uint64) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldGTE(FieldQueueSize, v))
}

// QueueSizeLT applies the LT predicate on the "queue_size" field.
func QueueSizeLT(v uint64) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldLT(FieldQueueSize, v))
}

// QueueSizeLTE applies the LTE predicate on the "queue_size" field.
func QueueSizeLTE(v uint64) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldLTE(FieldQueueSize, v))
}

// DeliveredTotalEQ applies the EQ predicate on the "delivered_total" field.
func DeliveredTotalEQ(v uint64) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldEQ(FieldDeliveredTotal, v))
}

// DeliveredTotalNEQ applies the NEQ predicate on the "delivered_total" field.
func DeliveredTotalNEQ(v uint64) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldNEQ(FieldDeliveredTotal, v))
}

// DeliveredTotalIn applies the In predicate on the "delivered_total" field.
func DeliveredTotalIn(vs ...uint64) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldIn(FieldDeliveredTotal, vs...))
}

// DeliveredTotalNotIn applies the NotIn predicate on the "delivered_total" field.
func DeliveredTotalNotIn(vs ...uint64) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldNotIn(FieldDeliveredTotal, vs...))
}

// DeliveredTotalGT applies the GT predicate on the "delivered_total" field.
func DeliveredTotalGT(v uint64) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldGT(FieldDeliveredTotal, v))
}

// DeliveredTotalGTE applies the GTE predicate on the "delivered_total" field.
func DeliveredTotalGTE(v uint64) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldGTE(FieldDeliveredTotal, v))
}

// DeliveredTotalLT applies the LT predicate on the "delivered_total" field.
func DeliveredTotalLT(v uint64) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldLT(FieldDeliveredTotal, v))
}

// DeliveredTotalLTE applies the LTE predicate on the "delivered_total" field.
func DeliveredTotalLTE(v uint64) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldLTE(FieldDeliveredTotal, v))
}

// FailedTotalEQ applies the EQ predicate on the "failed_total" field.
func FailedTotalEQ(v uint64) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldEQ(FieldFailedTotal, v))
}

// FailedTotalNEQ applies the NEQ predicate on the "failed_total" field.
func FailedTotalNEQ(v uint64) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldNEQ(FieldFailedTotal, v))
}

// FailedTotalIn applies the In predicate on the "failed_total" field.
func FailedTotalIn(vs ...uint64) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldIn(FieldFailedTotal, vs...))
}

// FailedTotalNotIn applies the NotIn predicate on the "failed_total" field.
func FailedTotalNotIn(vs ...uint64) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldNotIn(FieldFailedTotal, vs...))
}

// FailedTotalGT applies the GT predicate on the "failed_total" field.
func FailedTotalGT(v uint64) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldGT(FieldFailedTotal, v))
}

// FailedTotalGTE applies the GTE predicate on the "failed_total" field.
func FailedTotalGTE(v uint64) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldGTE(FieldFailedTotal, v))
}

// FailedTotalLT applies the LT predicate on the "failed_total" field.
func FailedTotalLT(v uint64) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldLT(FieldFailedTotal, v))
}

// FailedTotalLTE applies the LTE predicate on the "failed_total" field.
func FailedTotalLTE(v uint64) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldLTE(FieldFailedTotal, v))
}

// DeferredTotalEQ applies the EQ predicate on the "deferred_total" field.
func DeferredTotalEQ(v uint64) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldEQ(FieldDeferredTotal, v))
}

// DeferredTotalNEQ applies the NEQ predicate on the "deferred_total" field.
func DeferredTotalNEQ(v uint64) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldNEQ(FieldDeferredTotal, v))
}

// DeferredTotalIn applies the In predicate on the "deferred_total" field.
func DeferredTotalIn(vs ...uint64) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldIn(FieldDeferredTotal, vs...))
}

// DeferredTotalNotIn applies the NotIn predicate on the "deferred_total" field.
func DeferredTotalNotIn(vs ...uint64) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldNotIn(FieldDeferredTotal, vs...))
}

// DeferredTotalGT applies the GT predicate on the "deferred_total" field.
func DeferredTotalGT(v uint64) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldGT(FieldDeferredTotal, v))
}

// DeferredTotalGTE applies the GTE predicate on the "deferred_total" field.
func DeferredTotalGTE(v uint64) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldGTE(FieldDeferredTotal, v))
}

// DeferredTotalLT applies the LT predicate on the "deferred_total" field.
func DeferredTotalLT(v uint64) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldLT(FieldDeferredTotal, v))
}

// DeferredTotalLTE applies the LTE predicate on the "deferred_total" field.
func DeferredTotalLTE(v uint64) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldLTE(FieldDeferredTotal, v))
}

// DeliveryRatePerMinEQ applies the EQ predicate on the "delivery_rate_per_min" field.
func DeliveryRatePerMinEQ(v float64) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldEQ(FieldDeliveryRatePerMin, v))
}

// DeliveryRatePerMinNEQ applies the NEQ predicate on the "delivery_rate_per_min" field.
func DeliveryRatePerMinNEQ(v float64) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldNEQ(FieldDeliveryRatePerMin, v))
}

// DeliveryRatePerMinIn applies the In predicate on the "delivery_rate_per_min" field.
func DeliveryRatePerMinIn(vs ...float64) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldIn(FieldDeliveryRatePerMin, vs...))
}

// DeliveryRatePerMinNotIn applies the NotIn predicate on the "delivery_rate_per_min" field.
func DeliveryRatePerMinNotIn(vs ...float64) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldNotIn(FieldDeliveryRatePerMin, vs...))
}

// DeliveryRatePerMinGT applies the GT predicate on the "delivery_rate_per_min" field.
func DeliveryRatePerMinGT(v float64) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldGT(FieldDeliveryRatePerMin, v))
}

// DeliveryRatePerMinGTE applies the GTE predicate on the "delivery_rate_per_min" field.
func DeliveryRatePerMinGTE(v float64) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldGTE(FieldDeliveryRatePerMin, v))
}

// DeliveryRatePerMinLT applies the LT predicate on the "delivery_rate_per_min" field.
func DeliveryRatePerMinLT(v float64) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldLT(FieldDeliveryRatePerMin, v))
}

// DeliveryRatePerMinLTE applies the LTE predicate on the "delivery_rate_per_min" field.
func DeliveryRatePerMinLTE(v float64) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldLTE(FieldDeliveryRatePerMin, v))
}

// SuspendedEQ applies the EQ predicate on the "suspended" field.
func SuspendedEQ(v bool) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldEQ(FieldSuspended, v))
}

// SuspendedNEQ applies the NEQ predicate on the "suspended" field.
func SuspendedNEQ(v bool) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldNEQ(FieldSuspended, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MetricSnapshot) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MetricSnapshot) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MetricSnapshot) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.NotPredicates(p))
}
