-- Create dsn_event and convert it to a TimescaleDB hypertable, mirroring
-- log_event. Idempotent — re-running on an already-migrated DB is safe.
--
-- The CREATE TABLE here duplicates what ent's schema diff would emit. We
-- keep it because ent.Schema.Create runs in a single transaction and
-- aborts on the audit_entry TS103 quirk on subsequent boots, so we can't
-- rely on ent to land the new table. This file is the source of truth on
-- existing dev/prod DBs; ent-generated DDL is for fresh databases only.
CREATE TABLE IF NOT EXISTS dsn_event (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    received_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    verp_token VARCHAR(128),
    message_id_ref VARCHAR(255),
    original_recipient VARCHAR(320),
    final_recipient VARCHAR(320),
    action VARCHAR(16) NOT NULL,
    status VARCHAR(16),
    status_class VARCHAR(2),
    diagnostic_code VARCHAR(1024),
    remote_mta VARCHAR(253),
    category VARCHAR(64),
    mail_class VARCHAR(64),
    tenant VARCHAR(64),
    campaign VARCHAR(64),
    raw_size INTEGER NOT NULL DEFAULT 0,
    extra_json TEXT
);

-- Composite PK includes the partitioning column (TimescaleDB TS103
-- requirement). Adding it before create_hypertable to avoid the
-- "cannot create a unique index without the partitioning column" error.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE table_schema = 'public'
      AND table_name = 'dsn_event'
      AND constraint_type = 'PRIMARY KEY'
  ) THEN
    ALTER TABLE dsn_event ADD PRIMARY KEY (id, received_at);
  END IF;
END
$$;

CREATE INDEX IF NOT EXISTS dsn_event_received_at_idx
    ON dsn_event (received_at);
CREATE INDEX IF NOT EXISTS dsn_event_final_recipient_received_at_idx
    ON dsn_event (final_recipient, received_at);
CREATE INDEX IF NOT EXISTS dsn_event_category_received_at_idx
    ON dsn_event (category, received_at);
CREATE INDEX IF NOT EXISTS dsn_event_mail_class_received_at_idx
    ON dsn_event (mail_class, received_at);
CREATE INDEX IF NOT EXISTS dsn_event_status_class_received_at_idx
    ON dsn_event (status_class, received_at);
CREATE INDEX IF NOT EXISTS dsn_event_message_id_ref_idx
    ON dsn_event (message_id_ref);

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name = 'dsn_event'
  ) AND NOT EXISTS (
    SELECT 1 FROM timescaledb_information.hypertables WHERE hypertable_name = 'dsn_event'
  ) THEN
    PERFORM create_hypertable('dsn_event', 'received_at',
      chunk_time_interval => INTERVAL '7 days',
      if_not_exists => TRUE,
      migrate_data  => TRUE);
  END IF;
END
$$;

-- Bounce volume is far lower than log_event traffic but the rows are wide
-- (diagnostic_code + extra_json). Compress chunks older than 7 days,
-- segment by category so the dashboard's group-by queries stay cheap on
-- compressed chunks. Retention matches log_event for cross-correlation.
ALTER TABLE dsn_event SET (
  timescaledb.compress,
  timescaledb.compress_segmentby = 'category'
);

SELECT add_compression_policy('dsn_event', INTERVAL '7 days', if_not_exists => TRUE);
SELECT add_retention_policy('dsn_event', INTERVAL '90 days', if_not_exists => TRUE);
