-- Defensive CREATE TABLE for global_settings — same rationale as
-- 0005_dsn_event_hypertable.sql: ent's transactional schema diff aborts
-- on the existing audit_entry TS103 quirk on subsequent boots, so we
-- can't rely on ent to land new tables on existing DBs.
--
-- Singleton enforced via CHECK (id = 1) — the table holds exactly one
-- row, kept in sync with kumopolicy.GlobalSettings at render time.
-- ent treats `Strings` fields as JSON-encoded text; we mirror that
-- here so the column types match what the generated code expects.
CREATE TABLE IF NOT EXISTS global_settings (
    id                    BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    kumo_http_listen      VARCHAR(128),
    esmtp_relay_hosts     JSONB,
    http_trusted_hosts    JSONB,
    bounce_domain         VARCHAR(253),
    bounce_sender_domains JSONB,
    bounce_prefix         VARCHAR(64),
    mail_class_header     VARCHAR(128),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by            VARCHAR(64),
    CONSTRAINT global_settings_pkey       PRIMARY KEY (id),
    CONSTRAINT global_settings_singleton  CHECK (id = 1)
);

-- Seed the row so service-layer Get() never has to handle "row missing".
-- Idempotent: ON CONFLICT keeps the existing row's values intact.
INSERT INTO global_settings (id) VALUES (1)
ON CONFLICT (id) DO NOTHING;
