-- ACME tables: account (singleton), certificates, dns provider configs.
-- Defensive CREATE TABLE for the same reason as the previous migrations:
-- ent's transactional schema diff aborts on the audit_entry TS103 quirk,
-- which would otherwise prevent these tables from landing on existing
-- databases. Each one uses GENERATED BY DEFAULT AS IDENTITY so ent's
-- IDENTITY-based id columns line up.

-- ----- acme_account (singleton) -----
CREATE TABLE IF NOT EXISTS acme_account (
    id                BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    email             VARCHAR(320) NOT NULL DEFAULT '',
    server_url        VARCHAR(512) NOT NULL DEFAULT '',
    registration_json TEXT,
    private_key_pem   TEXT,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT acme_account_pkey      PRIMARY KEY (id),
    CONSTRAINT acme_account_singleton CHECK (id = 1)
);

INSERT INTO acme_account (id, email, server_url) VALUES (1, '', '')
ON CONFLICT (id) DO NOTHING;

-- ----- acme_certificate -----
-- alt_names is JSONB so ent's Strings field round-trips; the ent
-- generator emits Set/Get helpers that decode an array, no manual
-- JSON parsing on the Go side.
CREATE TABLE IF NOT EXISTS acme_certificate (
    id                BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    domain            VARCHAR(253) NOT NULL,
    alt_names         JSONB,
    challenge_type    VARCHAR(16)  NOT NULL DEFAULT 'http-01',
    dns_provider      VARCHAR(64),
    cert_pem          TEXT,
    key_pem           TEXT,
    cert_pem_path     VARCHAR(1024),
    key_pem_path      VARCHAR(1024),
    expires_at        TIMESTAMPTZ,
    last_renewed_at   TIMESTAMPTZ,
    status            VARCHAR(16)  NOT NULL DEFAULT 'pending',
    last_error        TEXT,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT acme_certificate_pkey PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS acme_certificate_domain_idx
    ON acme_certificate (domain);
CREATE INDEX IF NOT EXISTS acme_certificate_status_expires_at_idx
    ON acme_certificate (status, expires_at);

-- ----- acme_dns_provider_config -----
-- One row per provider name. The renewer / issuer reads the row when
-- it builds a lego DNS provider; UI updates write here.
CREATE TABLE IF NOT EXISTS acme_dns_provider_config (
    id          BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    provider    VARCHAR(64) NOT NULL,
    config_json TEXT NOT NULL DEFAULT '{}',
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by  VARCHAR(64),
    CONSTRAINT acme_dns_provider_config_pkey PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS acme_dns_provider_config_provider_idx
    ON acme_dns_provider_config (provider);
