-- Defensive CREATE TABLE for login_policies — same rationale as
-- 0006_global_settings.sql: ent's transactional schema diff aborts on the
-- existing audit_entry TS103 quirk on subsequent boots, so we can't rely
-- on ent to land new tables on existing DBs. ent owns the canonical schema
-- on fresh databases; this file is the idempotent backstop.
--
-- Column types mirror what the generated ent code expects: uint32 -> BIGINT,
-- enums -> VARCHAR, the JSON-encoded time_window -> VARCHAR(1024), and the
-- nillable deleted_at -> nullable TIMESTAMPTZ (soft-delete sentinel).
CREATE TABLE IF NOT EXISTS login_policies (
    id          BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    target_id   BIGINT NOT NULL DEFAULT 0,
    type        VARCHAR(16) NOT NULL,
    method      VARCHAR(16) NOT NULL,
    value       VARCHAR(512),
    time_window VARCHAR(1024),
    reason      VARCHAR(512),
    enabled     BOOLEAN NOT NULL DEFAULT TRUE,
    created_by  BIGINT NOT NULL DEFAULT 0,
    updated_by  BIGINT NOT NULL DEFAULT 0,
    deleted_by  BIGINT NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at  TIMESTAMPTZ,
    CONSTRAINT login_policies_pkey PRIMARY KEY (id)
);

-- Hot-path index for the enforcement query (enabled + non-deleted +
-- global/per-user) and a couple of secondary lookups for the CRUD UI.
CREATE INDEX IF NOT EXISTS login_policies_applicable_idx
    ON login_policies (enabled, deleted_at, target_id);
CREATE INDEX IF NOT EXISTS login_policies_method_idx ON login_policies (method);
CREATE INDEX IF NOT EXISTS login_policies_type_idx   ON login_policies (type);
