-- Defensive CREATE TABLE for mfa_credentials — ent's auto-migrate creates it
-- on fresh installs, but its transactional diff can abort on the pre-existing
-- audit_entry TS103 quirk (same rationale as 0006/0010/0011/0012), so we add
-- it idempotently here. Column types mirror the ent schema: uint32 -> BIGINT,
-- enums -> VARCHAR, secret/label as VARCHAR, nullable timestamps for the
-- confirmed/used markers.
CREATE TABLE IF NOT EXISTS mfa_credentials (
    id           BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id      BIGINT NOT NULL,
    kind         VARCHAR(16) NOT NULL,
    secret       VARCHAR(4096) NOT NULL,
    label        VARCHAR(128),
    status       VARCHAR(16) NOT NULL DEFAULT 'active',
    sign_count   BIGINT NOT NULL DEFAULT 0,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    confirmed_at TIMESTAMPTZ,
    used_at      TIMESTAMPTZ,
    CONSTRAINT mfa_credentials_pkey PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS mfa_credentials_user_kind_status_idx
    ON mfa_credentials (user_id, kind, status);
CREATE INDEX IF NOT EXISTS mfa_credentials_user_status_idx
    ON mfa_credentials (user_id, status);
