-- Defensive CREATE TABLE for mail_webhooks — ent's auto-migrate creates it
-- on fresh installs, but its transactional diff can abort on the pre-existing
-- audit_entry TS103 quirk (same rationale as 0006/0010-0013), so we add it
-- idempotently here. Column types mirror the ent schema.
CREATE TABLE IF NOT EXISTS mail_webhooks (
    id         BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name       VARCHAR(64) NOT NULL,
    address    VARCHAR(320) NOT NULL,
    url        VARCHAR(2048) NOT NULL,
    secret     VARCHAR(255),
    enabled    BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT mail_webhooks_pkey PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS mail_webhooks_name_key ON mail_webhooks (name);
CREATE INDEX IF NOT EXISTS mail_webhooks_address_idx ON mail_webhooks (address);
CREATE INDEX IF NOT EXISTS mail_webhooks_enabled_idx ON mail_webhooks (enabled);
