package biz

import (
	"fmt"
	"sort"
	"strconv"
	"strings"
)

// RenderBaseShaping serializes active delivery blueprints into a KumoMTA shaping
// TOML document (the base layer the shaping helper loads). Each blueprint is a
// domain block grouped to its provider site via mx_rollup; the warmup engine and
// TSA layer per-IP overrides on top via separately-loaded files.
//
// Only set fields are emitted. Blocks are sorted by MX pattern for a stable,
// checksummable document.
func RenderBaseShaping(blueprints []*DeliveryBlueprint) string {
	rows := make([]*DeliveryBlueprint, 0, len(blueprints))
	for _, b := range blueprints {
		if b != nil && b.Status == BlueprintActive && strings.TrimSpace(b.MXPattern) != "" {
			rows = append(rows, b)
		}
	}
	sort.Slice(rows, func(i, j int) bool { return rows[i].MXPattern < rows[j].MXPattern })

	var b strings.Builder
	b.WriteString("# Generated by iris — base delivery blueprints. Do not edit by hand.\n")
	for _, r := range rows {
		// Top-level domain block keyed by the recipient MX pattern; mx_rollup=false
		// so it matches that exact recipient domain (verified against kumod — a
		// [domain."x"] table or mx_rollup grouping does NOT match the domain arg).
		fmt.Fprintf(&b, "\n[%s]\n", tomlQuote(r.MXPattern))
		b.WriteString("mx_rollup = false\n")
		if rate := strings.TrimSpace(r.ConnRate); rate != "" {
			fmt.Fprintf(&b, "max_connection_rate = %s\n", tomlQuote(rate))
		}
		if r.DeliveriesPerConn > 0 {
			fmt.Fprintf(&b, "max_deliveries_per_connection = %d\n", r.DeliveriesPerConn)
		}
		if r.ConnLimit > 0 {
			fmt.Fprintf(&b, "connection_limit = %d\n", r.ConnLimit)
		}
		if r.DailyCap > 0 {
			fmt.Fprintf(&b, "max_message_rate = %s\n", tomlQuote(strconv.Itoa(r.DailyCap)+"/day"))
		}
	}
	return b.String()
}

// RenderWarmupShaping serializes per-IP warmup daily-cap overrides into a shaping
// TOML document, loaded after the base so it overrides the base max_message_rate
// for the warming source. rates is source -> bucket -> "N/day"; buckets map to
// provider MX patterns via providerForBucket. Empty when no warmup is active.
func RenderWarmupShaping(rates map[string]map[string]string) string {
	// Group overrides by recipient domain so each domain block is emitted once
	// with mx_rollup=false (matching the base block's keying so the per-source
	// override merges over it — verified against kumod; without the matching
	// mx_rollup the override silently does not apply).
	type override struct{ source, rate string }
	byDomain := map[string][]override{}
	for src, buckets := range rates {
		for bucket, rate := range buckets {
			if rate == "" {
				continue
			}
			for _, mx := range providerMXPatterns(bucket) {
				byDomain[mx] = append(byDomain[mx], override{src, rate})
			}
		}
	}
	if len(byDomain) == 0 {
		return "# Generated by iris — warmup overrides (none active).\n"
	}
	domains := make([]string, 0, len(byDomain))
	for d := range byDomain {
		domains = append(domains, d)
	}
	sort.Strings(domains)

	var b strings.Builder
	b.WriteString("# Generated by iris — per-IP warmup overrides. Do not edit by hand.\n")
	for _, mx := range domains {
		fmt.Fprintf(&b, "\n[%s]\nmx_rollup = false\n", tomlQuote(mx))
		ovs := byDomain[mx]
		sort.Slice(ovs, func(i, j int) bool { return ovs[i].source < ovs[j].source })
		for _, o := range ovs {
			fmt.Fprintf(&b, "\n[%s.sources.%s]\n", tomlQuote(mx), tomlQuote(o.source))
			fmt.Fprintf(&b, "max_message_rate = %s\n", tomlQuote(o.rate))
		}
	}
	return b.String()
}

// RenderAutomation serializes operator-authored TSA automation rules into a
// shaping TOML document of [["<domain>".automation]] blocks. This file is loaded
// by the TSA daemon (not kumod); the daemon evaluates the rules against live
// delivery events and publishes the resulting back-off, which kumod merges under
// the warmup ceiling. Rules are emitted in a stable (domain, regex) order.
func RenderAutomation(rules []*AutomationRule) string {
	active := make([]*AutomationRule, 0, len(rules))
	for _, r := range rules {
		if r != nil && r.Status == AutomationActive && strings.TrimSpace(r.Domain) != "" {
			active = append(active, r)
		}
	}
	sort.Slice(active, func(i, j int) bool {
		if active[i].Domain != active[j].Domain {
			return active[i].Domain < active[j].Domain
		}
		return active[i].Regex < active[j].Regex
	})

	var b strings.Builder
	b.WriteString("# Generated by iris — TSA automation rules. Do not edit by hand.\n")
	for _, r := range active {
		fmt.Fprintf(&b, "\n[[%s.automation]]\n", tomlQuote(r.Domain))
		// Triple-quoted literal so regex backslashes need no escaping (Validate
		// rejects a regex containing a triple quote).
		fmt.Fprintf(&b, "regex = '''%s'''\n", r.Regex)
		b.WriteString("action = " + automationActionExpr(r) + "\n")
		if r.Trigger == "immediate" || r.Trigger == "" {
			b.WriteString("trigger = \"Immediate\"\n")
		} else {
			fmt.Fprintf(&b, "trigger = {Threshold=%s}\n", tomlQuote(r.Trigger))
		}
		fmt.Fprintf(&b, "duration = %s\n", tomlQuote(r.Duration))
	}
	return b.String()
}

func automationActionExpr(r *AutomationRule) string {
	switch r.Action {
	case AutomationSuspend:
		return `"Suspend"`
	case AutomationSuspendTenant:
		return `"SuspendTenant"`
	case AutomationSetConfig:
		return "{SetConfig={name=" + tomlQuote(r.ConfigName) + ", value=" + tomlQuote(r.ConfigValue) + "}}"
	default:
		return `"Suspend"`
	}
}

// providerMXPatterns maps an MBP bucket to the representative MX patterns the
// warmup override applies to. Mirrors the seed registry; the "default" bucket
// has no specific domain (handled by the base fallback), so it emits nothing.
func providerMXPatterns(bucket string) []string {
	switch bucket {
	case MBPGmail:
		return []string{"google.com", "googlemail.com"}
	case MBPMicrosoft:
		return []string{"outlook.com", "hotmail.com", "live.com", "office365.com", "msn.com"}
	case MBPYahoo:
		return []string{"yahoodns.net", "yahoo.com", "ymail.com", "aol.com"}
	default:
		return nil
	}
}

// tomlQuote returns a TOML basic-string literal, escaping backslashes and quotes.
func tomlQuote(s string) string {
	r := strings.NewReplacer(`\`, `\\`, `"`, `\"`)
	return `"` + r.Replace(s) + `"`
}
