// Package kumopolicy renders a validated Snapshot to a kumomta-compatible
// init.lua. The output binds the operator-facing model to kumomta's actual
// Lua API:
//
//   - VMTAs become egress sources (one per VMTA) plus a single-member
//     egress pool of the same name, so a routing rule targeting "vmta-fast"
//     can reuse the name as a pool reference.
//   - VMTA groups become egress pools whose entries carry per-VMTA weights.
//   - MailClasses become a header-driven shortcut at smtp_server_message_received
//     (and http_message_generated): the X-Kumo-Mail-Class header value picks
//     a class, the class points at a pool name (vmta or vmta_group).
//   - Routing rules run after the mail-class lookup; the first matching rule
//     sets msg:set_meta('tenant', <pool>) which get_queue_config maps to
//     egress_pool.
//   - DKIM identities register signers that smtp_server_message_received
//     attaches to outgoing messages whose sender domain matches.
//
// The renderer never trusts caller input verbatim: every interpolated string
// flows through MustLuaString (escaped Lua literal) or sanitizeComment
// (newline + null stripping). reSafeName upstream constrains identifiers
// before they reach the renderer at all.
package kumopolicy

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"sort"
	"strings"
	"time"
)

// Render serialises a validated Snapshot to Lua. Callers MUST call
// Snapshot.Validate first; Render double-checks via the same path so a
// programming error in callers cannot bypass validation.
func Render(s *Snapshot, opts RenderOptions) (RenderResult, error) {
	if err := s.Validate(); err != nil {
		return RenderResult{}, err
	}

	var b strings.Builder
	approx := 6 * 1024
	approx += 256 * (len(s.Listeners) + len(s.VirtualMtas) + len(s.VirtualMtaGroups))
	approx += 128 * (len(s.RoutingRules) + len(s.Suppressions) + len(s.DkimIdentities) + len(s.MailClasses))
	b.Grow(approx)

	writeHeader(&b, opts, s.GlobalSettings)
	writeLogStreamConsts(&b, s.GlobalSettings)
	writeBounceConsts(&b, s.GlobalSettings)
	writeWebhookConsts(&b, s.MailWebhooks)
	writeRspamdConsts(&b, s.GlobalSettings)
	writeInit(&b, s.Listeners, s.GlobalSettings)
	writeRedisLogHook(&b, s.GlobalSettings)
	writeDsnCatcher(&b, s.GlobalSettings)
	writeWebhookCatcher(&b, s.MailWebhooks)
	writeEgressSources(&b, s.VirtualMtas, s.GlobalSettings)
	writeEgressPools(&b, s.VirtualMtas, s.VirtualMtaGroups)
	// MailClassTable must come BEFORE writeQueueConfig — the queue-config
	// closure references CLASS_TO_POOL as an upvalue, which only resolves
	// if the local is declared in an enclosing scope at closure-creation
	// time. Otherwise Lua treats it as a missing global and the lookup nils
	// out.
	writeMailClassTable(&b, s.MailClasses)
	writeQueueConfig(&b, s.GlobalSettings, s.MailWebhooks)
	writeListenerDomains(&b, s.Listeners, s.GlobalSettings, s.MailWebhooks)
	writeRspamdHook(&b, s.GlobalSettings)
	writeDkimTable(&b, s.DkimIdentities)
	writeSuppressionLookup(&b, s.GlobalSettings)
	writeRoutingChain(&b, s.MailClasses, s.RoutingRules, s.GlobalSettings, s.MailWebhooks, opts)
	writeFooter(&b, opts)

	out := b.String()
	sum := sha256.Sum256([]byte(out))
	return RenderResult{Lua: out, SHA256: hex.EncodeToString(sum[:])}, nil
}

// RenderOptions tunes generation. DryRun emits diagnostic prints alongside
// real actions so operators can preview routing decisions in the kumomta log.
type RenderOptions struct {
	DryRun       bool
	GeneratedAt  time.Time
	GeneratedBy  string
	GeneratorVer string
}

// RenderResult holds the rendered Lua and its SHA-256 (hex).
type RenderResult struct {
	Lua    string
	SHA256 string
}

// --- header -----------------------------------------------------------------

func writeHeader(b *strings.Builder, opts RenderOptions, gs GlobalSettings) {
	if opts.GeneratedAt.IsZero() {
		opts.GeneratedAt = time.Now().UTC()
	}
	if opts.GeneratorVer == "" {
		opts.GeneratorVer = "iris/0.1.0"
	}
	fmt.Fprintf(b, "-- kumomta policy generated by %s\n", opts.GeneratorVer)
	fmt.Fprintf(b, "-- generated_at = %s\n", opts.GeneratedAt.UTC().Format(time.RFC3339))
	if opts.GeneratedBy != "" {
		fmt.Fprintf(b, "-- generated_by = %s\n", sanitizeComment(opts.GeneratedBy))
	}
	if gs.PolicyVersion != "" {
		fmt.Fprintf(b, "-- policy_version = %s\n", sanitizeComment(gs.PolicyVersion))
	}
	if opts.DryRun {
		b.WriteString("-- DRY RUN MODE\n")
	}
	b.WriteString("local kumo = require 'kumo'\n\n")
}

// --- log-stream constants ---------------------------------------------------
//
// When LogStreamRedisURL is unset the renderer emits stub locals only — the
// log_hook + tracker queue are not registered, so kumomta keeps its default
// (file-based) logging path. Setting the URL in GlobalSettings is the trigger.
func writeLogStreamConsts(b *strings.Builder, gs GlobalSettings) {
	if gs.LogStreamRedisURL == "" {
		b.WriteString("-- ===== log stream (redis): disabled =====\n\n")
		return
	}
	streamName := gs.LogStreamName
	if streamName == "" {
		streamName = LogStreamNameDefault
	}
	maxLen := gs.LogStreamMaxLen
	if maxLen == "" {
		maxLen = LogStreamMaxLenDefault
	}
	b.WriteString("-- ===== log stream (redis) =====\n")
	fmt.Fprintf(b, "local LOGSTREAM_REDIS_URL = %s\n", MustLuaString(gs.LogStreamRedisURL))
	fmt.Fprintf(b, "local LOGSTREAM_NAME      = %s\n", MustLuaString(streamName))
	fmt.Fprintf(b, "local LOGSTREAM_TRACKER   = %s\n", MustLuaString(logStreamTrackerName))
	fmt.Fprintf(b, "local LOGSTREAM_MAXLEN    = %s\n\n", MustLuaString(maxLen))
}

// writeRedisLogHook emits the log_hook + should_enqueue_log_record callback +
// the make.<tracker> custom_lua queue constructor that performs XADD against
// the configured Redis stream. No-op when LogStreamRedisURL is empty.
func writeRedisLogHook(b *strings.Builder, gs GlobalSettings) {
	if gs.LogStreamRedisURL == "" {
		return
	}
	b.WriteString(`-- Log-hook callbacks. configure_log_hook itself is registered inside the
-- single kumo.on('init') above (kumomta rejects multiple init handlers).
kumo.on('should_enqueue_log_record', function(msg, hook_name)
  if hook_name ~= LOGSTREAM_TRACKER then return false end
  local lr = msg:get_meta 'log_record'
  if not lr then return false end
  if lr.queue == LOGSTREAM_TRACKER then return false end
  local tracked = {
    Reception        = true,
    Delivery         = true,
    Bounce           = true,
    TransientFailure = true,
    Feedback         = true,
  }
  if tracked[lr.type] then
    msg:set_meta('queue', LOGSTREAM_TRACKER)
    return true
  end
  return false
end)

kumo.on('make.redis_tracker', function(_domain, _tenant, _campaign)
  local redis = require 'redis'
  local conn = redis.open { node = LOGSTREAM_REDIS_URL, pool_size = 10 }
  local connection = {}
  function connection:send(message)
    local lr = message:get_meta 'log_record'
    local etype = (lr and lr.type) or 'Unknown'
    local payload = message:get_data()
    local ok, err = pcall(function()
      conn:query('XADD', LOGSTREAM_NAME,
                 'MAXLEN', '~', LOGSTREAM_MAXLEN, '*',
                 'type', etype,
                 'data', payload)
    end)
    -- A flaky log stream MUST NOT block real mail. On failure we record the
    -- error in kumomta's local logs (configure_local_logs is still active)
    -- and ack 250 so the tracker queue drains and the message proceeds.
    -- Operators can replay missed entries from the kumomta log files.
    if not ok then
      kumo.log_error('logstream: xadd failed type=' .. etype .. ' err=' .. tostring(err))
      return string.format('250 logstream redis unavailable, dropped %s', etype)
    end
    return string.format('250 streamed %s', etype)
  end
  return connection
end)

`)
}

// --- bounce / DSN constants -------------------------------------------------
//
// Two operational modes:
//
//   - Multi-domain (BounceSenderDomains non-empty): each sender domain gets
//     its own bounce subdomain via the convention "<prefix>.<sender>". The
//     outbound hook rewrites MAIL FROM to the per-sender bounce; the catcher
//     accepts inbound at every derived bounce subdomain.
//
//   - Legacy single-domain (BounceDomain non-empty, BounceSenderDomains
//     empty): every outbound funnels through one BOUNCE_DOMAIN_FALLBACK,
//     regardless of From: domain. DMARC alignment only holds for senders
//     that share an organizational domain with that fallback.
//
//   - Disabled (both empty): emits stub constants so downstream Lua blocks
//     can reference them without nil-checks.
//
// In all three modes BOUNCE_DOMAINS (Lua set of catcher hostnames) and
// BOUNCE_SENDER_TO_BOUNCE (Lua map sender→bounce) are emitted; the
// outbound hook prefers the map and falls back to the constant.
func writeBounceConsts(b *strings.Builder, gs GlobalSettings) {
	if !bouncePipelineEnabled(gs) {
		b.WriteString("-- ===== bounce / DSN pipeline: disabled =====\n")
		b.WriteString("local BOUNCE_VERP_SECRET      = ''\n")
		b.WriteString("local DSN_STREAM_NAME         = ''\n")
		b.WriteString("local DSN_TRACKER             = ''\n")
		b.WriteString("local BOUNCE_DOMAIN_FALLBACK  = ''\n")
		b.WriteString("local BOUNCE_DOMAINS          = {}\n")
		b.WriteString("local BOUNCE_SENDER_TO_BOUNCE = {}\n\n")
		return
	}
	streamName := gs.DsnStreamName
	if streamName == "" {
		streamName = DsnStreamNameDefault
	}
	prefix := bouncePrefix(gs)
	multi := len(gs.BounceSenderDomains) > 0
	mode := "single-domain (legacy)"
	if multi {
		mode = "multi-domain"
	}
	fmt.Fprintf(b, "-- ===== bounce / DSN pipeline (mode: %s) =====\n", mode)
	fmt.Fprintf(b, "local BOUNCE_VERP_SECRET      = %s\n", MustLuaString(gs.VerpSecret))
	fmt.Fprintf(b, "local DSN_STREAM_NAME         = %s\n", MustLuaString(streamName))
	fmt.Fprintf(b, "local DSN_TRACKER             = %s\n", MustLuaString(dsnTrackerName))

	// Catcher accepts these — set form so the route_message lookup is O(1).
	domains := effectiveBounceDomains(gs)
	b.WriteString("local BOUNCE_DOMAINS          = {\n")
	for _, d := range domains {
		fmt.Fprintf(b, "  [%s] = true,\n", MustLuaString(d))
	}
	b.WriteString("}\n")

	// In multi-domain mode, emit the per-sender mapping so the outbound
	// hook can rewrite MAIL FROM to the *aligned* bounce subdomain. Empty
	// in legacy mode (the fallback handles every sender there).
	//
	// Domain keys are lowercased so the hook's `from_dom:lower()` lookup
	// always hits regardless of how the operator typed the env value.
	// Stable order — Render's SHA-256 must be deterministic.
	b.WriteString("local BOUNCE_SENDER_TO_BOUNCE = {\n")
	if multi {
		seen := make(map[string]struct{}, len(gs.BounceSenderDomains))
		senders := make([]string, 0, len(gs.BounceSenderDomains))
		for _, raw := range gs.BounceSenderDomains {
			s := strings.Trim(strings.ToLower(strings.TrimSpace(raw)), ".")
			if s == "" {
				continue
			}
			if _, dup := seen[s]; dup {
				continue
			}
			seen[s] = struct{}{}
			senders = append(senders, s)
		}
		sort.Strings(senders)
		for _, s := range senders {
			fmt.Fprintf(b, "  [%s] = %s,\n",
				MustLuaString(s),
				MustLuaString(prefix+"."+s))
		}
	}
	b.WriteString("}\n")

	// Legacy single-domain fallback. Empty in multi mode, so the outbound
	// hook leaves MAIL FROM unrewritten for senders not in the map (safer
	// than producing an unaligned rewrite for an unmanaged domain).
	fallback := ""
	if !multi {
		fallback = strings.ToLower(gs.BounceDomain)
	}
	fmt.Fprintf(b, "local BOUNCE_DOMAIN_FALLBACK  = %s\n\n", MustLuaString(fallback))
}

// defaultRelayHosts is the RFC1918 + loopback CIDR set used when the
// operator hasn't overridden EsmtpRelayHosts / HTTPTrustedHosts via
// Global Settings. Same value for both knobs because the threat model
// is identical: trust what's already on the same private network.
var defaultRelayHosts = []string{
	"127.0.0.0/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16",
}

// luaCIDRList renders a CIDR list (or sensible default when empty) as a
// Lua table literal suitable for relay_hosts / trusted_hosts. Each entry
// is escaped via MustLuaString so an operator can't smuggle a literal
// "}" or a Lua-string-closer through the UI form.
func luaCIDRList(hosts []string) string {
	clean := make([]string, 0, len(hosts))
	for _, h := range hosts {
		h = strings.TrimSpace(h)
		if h == "" {
			continue
		}
		clean = append(clean, h)
	}
	if len(clean) == 0 {
		clean = defaultRelayHosts
	}
	var b strings.Builder
	b.WriteString("{ ")
	for i, h := range clean {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(MustLuaString(h))
	}
	b.WriteString(" }")
	return b.String()
}

// bouncePipelineEnabled is the canonical predicate: any of the three
// configurations turns the pipeline on. Single source of truth so the
// renderer's writeBounceConsts / writeDsnCatcher / writeListenerDomains /
// writeQueueConfig / writeRoutingChain stay in sync.
func bouncePipelineEnabled(gs GlobalSettings) bool {
	return len(gs.BounceSenderDomains) > 0 || gs.BounceDomain != ""
}

// bouncePrefix returns the leading label used when deriving bounce
// subdomains in multi-domain mode. Defaults to BouncePrefixDefault when
// the operator didn't set IRIS_BOUNCE_DOMAIN_PREFIX. Lower-cases and
// strips stray dots so a paste-induced "Bounces." doesn't slip through.
func bouncePrefix(gs GlobalSettings) string {
	p := strings.Trim(strings.ToLower(strings.TrimSpace(gs.BouncePrefix)), ".")
	if p == "" {
		return BouncePrefixDefault
	}
	return p
}

// effectiveBounceDomains returns the catcher-side bounce hostnames in
// stable sorted order. In multi-domain mode, derived from
// BounceSenderDomains via the prefix convention; in legacy mode, the
// single BounceDomain; nil when the pipeline is disabled.
func effectiveBounceDomains(gs GlobalSettings) []string {
	if len(gs.BounceSenderDomains) > 0 {
		prefix := bouncePrefix(gs)
		out := make([]string, 0, len(gs.BounceSenderDomains))
		seen := make(map[string]struct{}, len(gs.BounceSenderDomains))
		for _, sender := range gs.BounceSenderDomains {
			d := prefix + "." + strings.ToLower(strings.TrimSpace(sender))
			if _, dup := seen[d]; dup {
				continue
			}
			seen[d] = struct{}{}
			out = append(out, d)
		}
		sort.Strings(out)
		return out
	}
	if gs.BounceDomain != "" {
		return []string{strings.ToLower(gs.BounceDomain)}
	}
	return nil
}

// writeDsnCatcher emits the custom_lua queue constructor that XADDs raw
// inbound DSNs into the Redis stream consumed by pkg/dsnstream. Routing
// into this queue happens in route_message (see writeRoutingChain), which
// matches messages whose recipient domain equals BOUNCE_DOMAIN.
//
// We share LOGSTREAM_REDIS_URL because the dsn pipeline is meaningful only
// alongside the iris consumer stack — and the dev/prod compose lives on
// the same Redis. Validation (model.go) refuses BounceDomain != "" without
// LogStreamRedisURL set, so the reference here is always defined.
func writeDsnCatcher(b *strings.Builder, gs GlobalSettings) {
	if !bouncePipelineEnabled(gs) {
		return
	}
	b.WriteString(`-- DSN catcher: routes any mail addressed at BOUNCE_DOMAIN into a custom_lua
-- queue whose constructor XADDs the raw RFC822 onto a Redis stream. The iris
-- consumer (pkg/dsnstream) reads, parses, and persists into dsn_event.
kumo.on('make.dsn_xadd', function(_domain, _tenant, _campaign)
  local redis = require 'redis'
  local conn = redis.open { node = LOGSTREAM_REDIS_URL, pool_size = 4 }
  local connection = {}
  function connection:send(message)
    local rcpt = message:recipient()
    local envelope_rcpt = (rcpt and rcpt.email) or ''
    local raw = message:get_data()
    local ok, err = pcall(function()
      conn:query('XADD', DSN_STREAM_NAME, 'MAXLEN', '~', '50000', '*',
                 'rcpt', envelope_rcpt,
                 'raw', raw)
    end)
    if not ok then
      kumo.log_error('dsn: xadd failed err=' .. tostring(err))
      -- Ack 250 even on failure so the queue drains and the receiver
      -- doesn't keep retrying. We've already accepted the message at
      -- SMTP, throwing it away here only hides the bounce from operators
      -- temporarily — kumomta's local logs will carry the failure.
      return '250 dsn redis unavailable'
    end
    return '250 streamed dsn'
  end
  return connection
end)

`)
}

// --- kumo.on('init') --------------------------------------------------------

func writeInit(b *strings.Builder, ls []Listener, gs GlobalSettings) {
	b.WriteString("kumo.on('init', function()\n")

	// Spool. Defaults match kumomta's documented paths so the rendered policy
	// works on the stock image even without operator overrides.
	spool := gs.SpoolDir
	if spool == "" {
		spool = "/var/spool/kumomta"
	}
	fmt.Fprintf(b, "  kumo.define_spool { name = 'data', path = %s }\n", MustLuaString(spool+"/data"))
	fmt.Fprintf(b, "  kumo.define_spool { name = 'meta', path = %s }\n", MustLuaString(spool+"/meta"))

	// Logs.
	logDir := gs.LogDir
	if logDir == "" {
		logDir = "/var/log/kumomta"
	}
	fmt.Fprintf(b, "  kumo.configure_local_logs { log_dir = %s }\n", MustLuaString(logDir))

	// Diagnostic (tracing) verbosity. These lines are kumomta's internal
	// ERROR/WARN/INFO/DEBUG output to stderr/journald — distinct from the
	// structured message logs above. Operators redirect stderr to a file at
	// the systemd layer; here we only control how much detail is emitted.
	diagFilter := gs.DiagLogFilter
	if diagFilter == "" {
		diagFilter = DiagLogFilterDefault
	}
	fmt.Fprintf(b, "  kumo.set_diagnostic_log_filter(%s)\n", MustLuaString(diagFilter))

	// Listeners. If none are configured we emit a single default block
	// whose listen address and relay_hosts both come from Global
	// Settings (or fall back to the dev-friendly 0:2525 + RFC1918 +
	// loopback set so the compose stack works without any UI
	// configuration). The moment a Listener row is created on the
	// Listeners page, that row renders its own block and the default
	// disappears.
	if len(ls) == 0 {
		listen := strings.TrimSpace(gs.EsmtpListenAddr)
		if listen == "" {
			listen = "0:2525"
		}
		fmt.Fprintf(b, `  kumo.start_esmtp_listener {
    listen = %s,
    relay_hosts = %s,
  }
`, MustLuaString(listen), luaCIDRList(gs.EsmtpRelayHosts))
	} else {
		for _, l := range ls {
			writeOneListener(b, l, gs)
		}
	}

	// HTTP admin/management API. The admin-service polls /api/admin/*
	// (queues, suspensions, bounces, etc.) over this socket. Without it
	// every /v1/queues request returns 502 KUMOMTA_UNREACHABLE. Trusted
	// hosts come from Global Settings → Listeners (UI-editable); fallback
	// is the same RFC1918 + loopback set as the SMTP relay default.
	//
	// Bind spec is configurable: docker-compose uses '0.0.0.0:8000' so the
	// admin-service container reaches it via the iris Docker network;
	// host-native installs use '127.0.0.1:8025' (or similar) because
	// admin-service is also on :8000 and they'd collide.
	httpListen := strings.TrimSpace(gs.KumoHTTPListen)
	if httpListen == "" {
		httpListen = "0.0.0.0:8000"
	}
	fmt.Fprintf(b, `  kumo.start_http_listener {
    listen = %s,
    trusted_hosts = %s,
  }
`, MustLuaString(httpListen), luaCIDRList(gs.HTTPTrustedHosts))

	// Log hook: kumomta only allows ONE kumo.on('init', ...) handler — if
	// the Redis stream is enabled we register the log_hook here rather than
	// in a separate init block so the policy still parses.
	//
	// per_record disables Rejection records for the *hook* only. The log hook
	// builds a synthetic Message per record, setting its envelope sender from
	// the originating message; a Rejection (4xx/5xx to an incoming SMTP
	// command, e.g. a malformed MAIL FROM) has no sender, so the rfc5321
	// mailbox parser is handed an empty string and kumod spams
	// "failed to log: ... in mailbox, got empty input". Excluding Rejection
	// from the hook silences that noise while configure_local_logs still
	// records rejections to disk for abuse/probe visibility.
	if gs.LogStreamRedisURL != "" {
		b.WriteString(`  kumo.configure_log_hook {
    name = LOGSTREAM_TRACKER,
    headers = { 'Subject', 'X-Kumo-Mail-Class', 'X-Customer-ID', 'X-Campaign-ID' },
    per_record = {
      Rejection = { enable = false },
    },
  }
`)
	}
	b.WriteString("end)\n\n")
}

func writeOneListener(b *strings.Builder, l Listener, gs GlobalSettings) {
	b.WriteString("  kumo.start_esmtp_listener {\n")
	if l.ListenAddr != "" {
		fmt.Fprintf(b, "    listen = %s,\n", MustLuaString(l.ListenAddr))
	}
	if l.Hostname != "" {
		fmt.Fprintf(b, "    hostname = %s,\n", MustLuaString(l.Hostname))
	}
	if l.TLSEnabled {
		if l.TLSCertPath != "" {
			fmt.Fprintf(b, "    tls_certificate = %s,\n", MustLuaString(l.TLSCertPath))
		}
		if l.TLSKeyPath != "" {
			fmt.Fprintf(b, "    tls_private_key = %s,\n", MustLuaString(l.TLSKeyPath))
		}
	}
	if l.MaxMessageSize > 0 {
		fmt.Fprintf(b, "    max_message_size = %d,\n", l.MaxMessageSize)
	}
	// relay_hosts is the CIDR/IP allowlist of CONNECTING CLIENTS permitted to
	// relay to arbitrary destinations. It is NOT a list of domains — per
	// recipient-domain relay is handled separately by RelayAllowed →
	// get_listener_domain's relay_to. A listener that doesn't set its own
	// allowlist falls back to the global EsmtpRelayHosts (and finally to the
	// RFC1918 + loopback default via luaCIDRList), so a value configured in
	// Global Settings still applies once an operator adds a listener row.
	relayHosts := l.RelayHosts
	if len(relayHosts) == 0 {
		relayHosts = gs.EsmtpRelayHosts
	}
	fmt.Fprintf(b, "    relay_hosts = %s,\n", luaCIDRList(relayHosts))
	b.WriteString("  }\n")
}

// --- egress sources ---------------------------------------------------------

func writeEgressSources(b *strings.Builder, vs []VirtualMta, gs GlobalSettings) {
	b.WriteString("-- ===== egress sources (one per VMTA) =====\n")
	// Default outbound EHLO/HELO. Applied to every source that doesn't set
	// its own ehlo_domain — including the implicit 'default' source kumomta
	// builds when no routing rule matched — so outbound never announces the
	// bare system hostname (which receivers reject: "Helo command rejected:
	// Host not found" / rspamd HFILTER_HELO_5). A per-VMTA HeloName still
	// wins. Empty leaves kumomta's default (system hostname).
	fmt.Fprintf(b, "local EGRESS_EHLO_DEFAULT = %s\n", MustLuaString(strings.TrimSpace(gs.EgressEhloDomain)))
	b.WriteString("local SOURCES = {}\n")
	cp := append([]VirtualMta(nil), vs...)
	sort.Slice(cp, func(i, j int) bool { return cp[i].Name < cp[j].Name })
	for _, v := range cp {
		fmt.Fprintf(b, "SOURCES[%s] = {\n", MustLuaString(v.Name))
		// kumomta's make_egress_source takes a single source_address; we
		// emit the first IP and treat the rest as fallbacks an operator can
		// build per-VMTA overrides on top of via the egress pool entries.
		if len(v.SourceIPs) > 0 {
			fmt.Fprintf(b, "  source_address = %s,\n", MustLuaString(strings.TrimSpace(v.SourceIPs[0])))
		}
		if v.HeloName != "" {
			fmt.Fprintf(b, "  ehlo_domain = %s,\n", MustLuaString(v.HeloName))
		}
		// Connection limits live on the pool config in kumomta; we stash
		// them here for operators who want to wrap make_egress_pool to
		// thread the values through.
		if v.MaxConnections > 0 {
			fmt.Fprintf(b, "  _max_connections = %d,\n", v.MaxConnections)
		}
		if v.MaxMessagesPerConnection > 0 {
			fmt.Fprintf(b, "  _max_messages_per_connection = %d,\n", v.MaxMessagesPerConnection)
		}
		b.WriteString("}\n")
	}
	b.WriteString(`
kumo.on('get_egress_source', function(name)
  local cfg = SOURCES[name]
  local clean = {}
  if cfg then
    -- Strip _-prefixed pseudo-fields kumomta doesn't accept.
    for k, val in pairs(cfg) do
      if string.sub(k, 1, 1) ~= '_' then clean[k] = val end
    end
  end
  clean.name = name
  -- Apply the default EHLO to any source lacking its own (incl. the
  -- implicit 'default' source). Per-VMTA helo_name already populated
  -- clean.ehlo_domain above and is preserved.
  if (clean.ehlo_domain == nil or clean.ehlo_domain == '') and EGRESS_EHLO_DEFAULT ~= '' then
    clean.ehlo_domain = EGRESS_EHLO_DEFAULT
  end
  return kumo.make_egress_source(clean)
end)

`)
}

// --- egress pools -----------------------------------------------------------

func writeEgressPools(b *strings.Builder, vs []VirtualMta, gs []VirtualMtaGroup) {
	b.WriteString("-- ===== egress pools (one per VMTA + one per group) =====\n")
	b.WriteString("local POOLS = {}\n")

	// Singleton pools for VMTAs so a routing rule targeting a vmta name
	// resolves through the same get_egress_pool callback as a group.
	cp := append([]VirtualMta(nil), vs...)
	sort.Slice(cp, func(i, j int) bool { return cp[i].Name < cp[j].Name })
	for _, v := range cp {
		fmt.Fprintf(b, "POOLS[%s] = { entries = { { name = %s } } }\n",
			MustLuaString(v.Name), MustLuaString(v.Name))
	}

	gp := append([]VirtualMtaGroup(nil), gs...)
	sort.Slice(gp, func(i, j int) bool { return gp[i].Name < gp[j].Name })
	for _, g := range gp {
		if !g.Enabled {
			continue
		}
		fmt.Fprintf(b, "POOLS[%s] = { entries = {\n", MustLuaString(g.Name))
		for _, m := range g.Members {
			if !m.Enabled || m.Weight == 0 {
				continue
			}
			fmt.Fprintf(b, "  { name = %s, weight = %d },\n", MustLuaString(m.VmtaName), m.Weight)
		}
		b.WriteString("} }\n")
	}

	b.WriteString(`
kumo.on('get_egress_pool', function(name)
  local cfg = POOLS[name]
  if not cfg or not cfg.entries or #cfg.entries == 0 then
    -- Unknown pool: fall back to a single source with the same name, so
    -- routing rules can reference VMTAs that haven't been wrapped in a pool.
    return kumo.make_egress_pool { name = name, entries = { { name = name } } }
  end
  return kumo.make_egress_pool { name = name, entries = cfg.entries }
end)

`)
}

// --- get_queue_config -------------------------------------------------------
//
// The routing chain sets msg:set_meta('tenant', <pool-name>) when a rule
// fires; get_queue_config picks up that tenant value and uses it as the
// egress_pool. The default pool ('default') only matters when no rule
// matched — it routes to a synthetic pool with no entries, which kumomta
// surfaces as "no source available" so misconfiguration is loud.
func writeQueueConfig(b *strings.Builder, gs GlobalSettings, whs []MailWebhook) {
	b.WriteString("-- ===== queue → egress pool mapping =====\n")

	// Test-mode MX overrides: emit a Lua table the e2e harness uses to
	// pin specific recipient domains at mock SMTP receivers without
	// needing a real DNS server. The map is empty in production.
	if len(gs.TestDomainRoutes) > 0 {
		b.WriteString("local TEST_DOMAIN_ROUTES = {\n")
		// Stable order — Render's SHA-256 must be deterministic.
		keys := make([]string, 0, len(gs.TestDomainRoutes))
		for k := range gs.TestDomainRoutes {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for _, k := range keys {
			fmt.Fprintf(b, "  [%s] = %s,\n", MustLuaString(k), MustLuaString(gs.TestDomainRoutes[k]))
		}
		b.WriteString("}\n")
	} else {
		b.WriteString("local TEST_DOMAIN_ROUTES = {}\n")
	}

	b.WriteString("kumo.on('get_queue_config', function(domain, tenant, campaign, routing_domain)\n")
	if gs.LogStreamRedisURL != "" {
		// Tracker queue routes to the Redis-XADD custom_lua constructor; it
		// has its own retry policy because Redis hiccups must not block real
		// mail. The queue name matches LOGSTREAM_TRACKER above.
		b.WriteString(`  if domain == LOGSTREAM_TRACKER then
    return kumo.make_queue_config {
      protocol = { custom_lua = { constructor = 'make.redis_tracker' } },
      retry_interval = '30s',
      max_retry_interval = '5m',
    }
  end
`)
	}
	if bouncePipelineEnabled(gs) {
		// Inbound DSN routing: route_message tags bounce-domain mail with
		// queue=DSN_TRACKER. Here we hand that queue's protocol over to the
		// make.dsn_xadd custom_lua constructor.
		b.WriteString(`  if domain == DSN_TRACKER then
    return kumo.make_queue_config {
      protocol = { custom_lua = { constructor = 'make.dsn_xadd' } },
      retry_interval = '30s',
      max_retry_interval = '5m',
    }
  end
`)
	}
	if len(enabledWebhooks(whs)) > 0 {
		// Inbound webhook routing: route_message tags matching mail with
		// queue=WEBHOOK_TRACKER, delivered by the make.webhook_post HTTP POST.
		b.WriteString(`  if domain == WEBHOOK_TRACKER then
    return kumo.make_queue_config {
      protocol = { custom_lua = { constructor = 'make.webhook_post' } },
      retry_interval = '1m',
      max_retry_interval = '30m',
    }
  end
`)
	}
	// Pool resolution. In the legacy `tenant@domain` queue mode, the tenant
	// is a class name → pool lookup, falling back to tenant-as-literal-pool,
	// then 'default'. In one-queue-per-vmta mode the queue meta is set
	// upstream to the pool name itself, so kumomta calls us with a
	// single-segment queue (tenant nil) and `domain` IS the pool.
	b.WriteString(`  local pool
  if not tenant or tenant == '' then
    -- Single-segment queue (one-queue-per-vmta mode). The queue name is
    -- the pool; no class indirection.
    pool = domain
  else
    pool = CLASS_TO_POOL[tenant]
    if not pool or pool == '' then pool = tenant end
    if not pool or pool == '' then pool = 'default' end
  end
  -- Test-mode override: pin the destination MX for matching domains.
  -- Skips DNS resolution entirely, points at a fixed host:port. In
  -- one-queue-per-vmta mode the domain arg is the pool name, so the
  -- recipient's domain arrives via routing_domain instead -- try both.
  local mx_lookup = (routing_domain ~= nil and routing_domain ~= '') and routing_domain or domain
  local mx = TEST_DOMAIN_ROUTES[mx_lookup]
  if mx then
    return kumo.make_queue_config {
      egress_pool = pool,
      protocol = { smtp = { mx_list = { mx } } },
      retry_interval = '10s',
      max_retry_interval = '1m',
    }
  end
`)
	// Normal delivery queue. Operator-configured retry/age fields are
	// appended when set; otherwise kumomta's defaults apply.
	fmt.Fprintf(b, "  return kumo.make_queue_config {\n    egress_pool = pool,%s\n  }\nend)\n\n",
		queueRetryFields(gs, "    "))
}

// queueRetryFields renders the operator-configured retry/age fields for the
// normal queue config. Each is omitted when empty so kumomta's defaults
// (retry_interval 20m, doubling, max_age 7d) apply. indent is the leading
// whitespace used to align fields inside the make_queue_config table.
func queueRetryFields(gs GlobalSettings, indent string) string {
	var b strings.Builder
	for _, f := range []struct{ key, val string }{
		{"retry_interval", strings.TrimSpace(gs.EgressRetryInterval)},
		{"max_retry_interval", strings.TrimSpace(gs.EgressMaxRetryInterval)},
		{"max_age", strings.TrimSpace(gs.EgressMaxAge)},
	} {
		if f.val != "" {
			fmt.Fprintf(&b, "\n%s%s = %s,", indent, f.key, MustLuaString(f.val))
		}
	}
	return b.String()
}

// --- inbound mail webhooks --------------------------------------------------

// enabledWebhooks filters to the active webhooks (defensive — the snapshot
// already loads only enabled rows).
func enabledWebhooks(whs []MailWebhook) []MailWebhook {
	out := make([]MailWebhook, 0, len(whs))
	for _, w := range whs {
		if w.Enabled {
			out = append(out, w)
		}
	}
	return out
}

const webhookTracker = "iris_webhook"

// writeWebhookConsts emits the lookup tables and the WEBHOOK_TRACKER queue
// name. Exact-address webhooks key WEBHOOK_BY_EMAIL; bare-domain catch-alls
// key WEBHOOK_BY_DOMAIN. Both are declared even when empty so later closures
// resolve them as upvalues.
func writeWebhookConsts(b *strings.Builder, whs []MailWebhook) {
	whs = enabledWebhooks(whs)
	b.WriteString("-- ===== inbound mail webhooks =====\n")
	fmt.Fprintf(b, "local WEBHOOK_TRACKER = %s\n", MustLuaString(webhookTracker))
	b.WriteString("local WEBHOOK_BY_EMAIL = {}\n")
	b.WriteString("local WEBHOOK_BY_DOMAIN = {}\n")
	for _, w := range whs {
		table := "WEBHOOK_BY_EMAIL"
		key := strings.ToLower(w.Address)
		if w.IsDomainCatchAll() {
			table = "WEBHOOK_BY_DOMAIN"
			key = w.WebhookDomain()
		}
		fmt.Fprintf(b, "%s[%s] = { url = %s, secret = %s }\n",
			table, MustLuaString(key), MustLuaString(w.URL), MustLuaString(w.Secret))
	}
	b.WriteString("\n")
}

// writeWebhookCatcher emits the custom_lua queue constructor that POSTs the
// raw message to the matched endpoint. A 2xx acks (250); anything else (or a
// transport error) defers so kumomta retries on its normal backoff.
func writeWebhookCatcher(b *strings.Builder, whs []MailWebhook) {
	if len(enabledWebhooks(whs)) == 0 {
		return
	}
	b.WriteString(`kumo.on('make.webhook_post', function(_domain, _tenant, _campaign)
  local connection = {}
  function connection:send(message)
    local rcpt = message:recipient()
    local email = (rcpt and rcpt.email or ''):lower()
    local dom = (rcpt and rcpt.domain or ''):lower()
    local route = WEBHOOK_BY_EMAIL[email] or WEBHOOK_BY_DOMAIN[dom]
    if not route then
      return '250 no webhook route (dropped)'
    end
    local body = message:get_data()
    local client = kumo.http.build_client {}
    local req = client:post(route.url)
    req:header('Content-Type', 'message/rfc822')
    req:header('X-Iris-Recipient', email)
    req:header('X-Iris-Message-Id', tostring(message:id()))
    if route.secret and route.secret ~= '' then
      local sig = kumo.digest.hmac_sha256({ key_data = route.secret }, body)
      req:header('X-Iris-Signature', tostring(sig))
    end
    req:body(body)
    local ok, resp = pcall(function() return req:send() end)
    if not ok then
      kumo.log_error('webhook: post failed err=' .. tostring(resp))
      return string.format('451 4.4.1 webhook post error: %s', tostring(resp))
    end
    local code = resp:status_code()
    if code >= 200 and code < 300 then
      return string.format('250 forwarded to webhook (%d)', code)
    end
    return string.format('451 4.4.1 webhook returned %d', code)
  end
  return connection
end)

`)
}

// --- inbound rspamd spam filtering ------------------------------------------

// rspamdEnabled reports whether inbound scanning is configured (mode tag or
// enforce + a URL).
func rspamdEnabled(gs GlobalSettings) bool {
	m := strings.ToLower(strings.TrimSpace(gs.RspamdMode))
	return (m == "tag" || m == "enforce") && strings.TrimSpace(gs.RspamdURL) != ""
}

// rspamdEnforce reports whether rspamd's reject/defer verdicts are honored
// (vs tag-only).
func rspamdEnforce(gs GlobalSettings) bool {
	return strings.ToLower(strings.TrimSpace(gs.RspamdMode)) == "enforce"
}

// writeRspamdConsts emits the rspamd endpoint + enforce flag (only when
// enabled). Declared early so the reception hook can capture them.
func writeRspamdConsts(b *strings.Builder, gs GlobalSettings) {
	if !rspamdEnabled(gs) {
		return
	}
	b.WriteString("-- ===== inbound spam filtering (rspamd) =====\n")
	fmt.Fprintf(b, "local RSPAMD_URL = %s\n", MustLuaString(strings.TrimSpace(gs.RspamdURL)))
	fmt.Fprintf(b, "local RSPAMD_ENFORCE = %t\n\n", rspamdEnforce(gs))
}

// writeRspamdHook defines the iris_rspamd_scan(msg) Lua function that scans
// inbound mail for hosted domains through rspamd's /checkv2 and honors the
// verdict. KumoMTA permits only ONE handler per event, so this is NOT its own
// kumo.on('smtp_server_message_received', …) — instead the single routing-chain
// handler calls iris_rspamd_scan BEFORE route_message (see writeRoutingChain),
// so a reject/defer happens before any webhook/DSN handling. It's wired only
// into the SMTP path, not http_message_generated, so API-injected mail is
// never scanned. Fails open: if rspamd is unreachable or its response can't be
// parsed, the message is accepted.
func writeRspamdHook(b *strings.Builder, gs GlobalSettings) {
	if !rspamdEnabled(gs) {
		return
	}
	b.WriteString(`local function iris_rspamd_scan(msg)
  local rcpt = msg:recipient()
  local rdom = (rcpt and rcpt.domain or ''):lower()
  -- Inbound-to-hosted only: skip outbound relay (external recipient) and
  -- bounce/DSN subdomains (system mail must not be spam-rejected).
  if not (LISTENER_DOMAINS and LISTENER_DOMAINS[rdom]) then return end
  if BOUNCE_DOMAINS and BOUNCE_DOMAINS[rdom] then return end
  local s = msg:sender()
  local client = kumo.http.build_client {}
  local req = client:post(RSPAMD_URL .. '/checkv2')
  req:header('From', (s and s.email) or '')
  req:header('Rcpt', (rcpt and rcpt.email) or '')
  req:header('Deliver-To', (rcpt and rcpt.email) or '')
  local ok_ip, ip = pcall(function() return msg:get_meta('received_from') end)
  if ok_ip and ip and ip ~= '' then req:header('Ip', tostring(ip)) end
  req:body(msg:get_data())
  local ok, resp = pcall(function() return req:send() end)
  if not ok then
    kumo.log_error('rspamd: request failed: ' .. tostring(resp))
    return -- fail-open
  end
  if resp:status_code() ~= 200 then
    kumo.log_error('rspamd: unexpected status ' .. tostring(resp:status_code()))
    return -- fail-open
  end
  local ok2, r = pcall(function() return kumo.serde.json_parse(resp:text()) end)
  if not ok2 or type(r) ~= 'table' then
    return -- fail-open
  end
  local score = r.score or 0
  local action = r.action or 'no action'
  msg:prepend_header('X-Spam-Score', string.format('%.2f', score))
  msg:prepend_header('X-Rspamd-Action', tostring(action))
  if action == 'reject' then
    if RSPAMD_ENFORCE then
      kumo.reject(550, '5.7.1 message rejected as spam')
      return
    end
    msg:prepend_header('X-Spam', 'yes')
  elseif action == 'soft reject' or action == 'greylist' then
    if RSPAMD_ENFORCE then
      kumo.reject(451, '4.7.1 greylisted, please try again later')
      return
    end
  elseif action == 'add header' or action == 'rewrite subject' then
    msg:prepend_header('X-Spam', 'yes')
    msg:prepend_header('X-Spam-Status', string.format('Yes, score=%.2f', score))
  end
end

`)
}

// --- listener domains -------------------------------------------------------

func writeListenerDomains(b *strings.Builder, ls []Listener, gs GlobalSettings, whs []MailWebhook) {
	// Aggregate domain → cfg across all listeners. If the same domain appears
	// on multiple listeners with different settings the last wins; the admin
	// service should prevent that upstream.
	type rule struct {
		relay     bool
		requireTL bool
	}
	domains := map[string]rule{}
	for _, l := range ls {
		for _, d := range l.Domains {
			domains[d.Domain] = rule{relay: d.RelayAllowed, requireTL: d.RequireTLS}
		}
	}
	// Each bounce domain is a hostname we accept inbound DSNs at. In
	// multi-domain mode that's one entry per sender (bounces.test-1.com,
	// bounces.test2.com, …); in legacy mode it's the single fallback.
	// Operators don't have to add these as Listener rows in the UI —
	// the env-driven config wires them implicitly.
	for _, d := range effectiveBounceDomains(gs) {
		domains[d] = rule{relay: true, requireTL: false}
	}
	// Accept inbound mail for every webhook recipient's domain so kumomta
	// relays it into the chain (where route_message hands it to the webhook
	// queue) instead of rejecting it as an unknown destination.
	for _, w := range enabledWebhooks(whs) {
		domains[w.WebhookDomain()] = rule{relay: true, requireTL: false}
	}
	if len(domains) == 0 {
		return
	}
	keys := make([]string, 0, len(domains))
	for k := range domains {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	b.WriteString("-- ===== listener domains =====\n")
	b.WriteString("local LISTENER_DOMAINS = {\n")
	for _, k := range keys {
		r := domains[k]
		// require_tls is enforced via listener-level TLS config in
		// kumomta, not on make_listener_domain (which doesn't accept
		// the field). We keep the column on the data model so future
		// versions of kumomta — or our own admission check — can
		// surface it; for now it's a no-op in the rendered Lua.
		_ = r.requireTL
		fmt.Fprintf(b, "  [%s] = { relay_to = %t },\n",
			MustLuaString(k), r.relay)
	}
	b.WriteString("}\n\n")
	b.WriteString(`kumo.on('get_listener_domain', function(domain, listener)
  local cfg = LISTENER_DOMAINS[domain]
  if not cfg then return nil end
  return kumo.make_listener_domain {
    relay_to = cfg.relay_to,
  }
end)

`)
}

// --- mail class lookup table -----------------------------------------------

func writeMailClassTable(b *strings.Builder, mcs []MailClass) {
	b.WriteString("-- ===== mail classes (X-Kumo-Mail-Class router) =====\n")
	// MAIL_CLASSES drives the header → routing-target match in route_message.
	// CLASS_TO_POOL is a parallel index used by get_queue_config to translate
	// the queue's tenant (which equals the mail class name, so /v1/queues
	// shows one row per class) back into the egress pool that should ship it.
	b.WriteString("local MAIL_CLASSES = {}\n")
	b.WriteString("local CLASS_TO_POOL = {}\n")
	cp := append([]MailClass(nil), mcs...)
	sort.Slice(cp, func(i, j int) bool { return cp[i].Name < cp[j].Name })
	for _, m := range cp {
		if !m.Enabled {
			continue
		}
		fmt.Fprintf(b, "MAIL_CLASSES[%s] = { kind = %s, ref = %s }\n",
			MustLuaString(m.Name), MustLuaString(m.TargetKind), MustLuaString(m.TargetRef))
		fmt.Fprintf(b, "CLASS_TO_POOL[%s] = %s\n",
			MustLuaString(m.Name), MustLuaString(m.TargetRef))
	}
	b.WriteString("\n")
}

// --- dkim signer table ------------------------------------------------------

func writeDkimTable(b *strings.Builder, ids []DkimIdentity) {
	// Always declare the table so the smtp_client_message_sending handler
	// can index it unconditionally — leaving it undeclared turns a no-op
	// "no DKIM configured" path into a runtime "undefined global" error
	// the first time kumomta tries to deliver a message.
	if len(ids) == 0 {
		b.WriteString("-- ===== dkim signers (none configured) =====\n")
		b.WriteString("local DKIM_BY_DOMAIN = {}\n\n")
		return
	}
	b.WriteString("-- ===== dkim signers =====\n")
	b.WriteString("local DKIM_BY_DOMAIN = {}\n")
	cp := append([]DkimIdentity(nil), ids...)
	sort.Slice(cp, func(i, j int) bool { return cp[i].Domain < cp[j].Domain })
	for _, d := range cp {
		// Translate ed25519/rsa-1024/rsa-2048/rsa-4096 → kumomta's algorithm names.
		algo := d.Algorithm
		switch algo {
		case "ed25519":
			algo = "ed25519"
		case "rsa-1024", "rsa-2048", "rsa-4096", "rsa":
			algo = "sha256"
		}
		fmt.Fprintf(b, "DKIM_BY_DOMAIN[%s] = { selector = %s, key = %s, algo = %s }\n",
			MustLuaString(d.Domain),
			MustLuaString(d.Selector),
			MustLuaString(d.KeyPath),
			MustLuaString(algo),
		)
	}
	b.WriteString("\n")
}

// --- suppression lookup -----------------------------------------------------
//
// At ~1M messages/day with multi-million-entry suppression lists, embedding
// every entry into init.lua becomes prohibitive: the rendered file grows
// past 50 MB, every /v1/policy/apply re-parses it, and every kumod replica
// keeps a private copy in Lua state. We instead defer to Redis (already in
// the deployment for log streaming) at message-receive time. A
// kumo.memoize TTL cache absorbs bursts to the same recipient without
// hitting Redis on every message.
//
// Two SETs hold the truth:
//   - kumo:supp:addr  exact addresses (envelope.recipient.email)
//   - kumo:supp:dom   exact recipient domains
//
// admin-service dual-writes both on Create/Delete and runs a startup
// resync that rebuilds the SETs from PostgreSQL — so a Redis flush, a
// fresh deployment, or drift after a network partition all repair
// themselves on the next admin-service boot.
//
// Fail-open is deliberate. If Redis is unreachable we log and let the
// message proceed; blocking legitimate mail because Redis hiccupped is
// strictly worse than letting one suppressed recipient slip through.
// The next epoch (10s) and the next resync are independent self-heals.
func writeSuppressionLookup(b *strings.Builder, gs GlobalSettings) {
	b.WriteString("-- ===== suppression list (redis-backed; SISMEMBER + memoize) =====\n")
	// is_suppressed is a forward-declared local so route_message captures
	// it as an upvalue regardless of whether Redis is configured. With
	// no Redis we leave it as the stub that returns nil; with Redis we
	// reassign inside the do-block so the connection and memoize cache
	// are kept private.
	b.WriteString("local is_suppressed = function(_rcpt, _rdom) return nil end\n")
	if gs.LogStreamRedisURL == "" {
		// No Redis configured — operator has opted out of the suppression
		// list. Stub stays in place; route_message's call is a no-op.
		b.WriteString("\n")
		return
	}
	// kumomta's redis module: same connection style the log_hook uses.
	// pool_size matches typical worker count + headroom; ttl = 15s caps
	// the staleness window for a freshly-added suppression to take
	// effect (delete is symmetric — at most 15s of one-extra-reject).
	b.WriteString(`do
  local redis = require 'redis'
  local supp_conn = redis.open {
    node = LOGSTREAM_REDIS_URL,
    pool_size = 32,
  }
  -- Memoize collapses repeat lookups (retries, multi-recipient sends,
  -- list bursts) onto a single Redis hit. capacity sized for ~15s of
  -- working set at a few hundred msg/s; tune up if your queue depth
  -- consistently exceeds it.
  local function _check(rcpt, rdom)
    local ok, hit = pcall(function()
      if supp_conn:query('SISMEMBER', 'kumo:supp:addr', rcpt) == 1 then return 'addr' end
      if supp_conn:query('SISMEMBER', 'kumo:supp:dom',  rdom) == 1 then return 'dom'  end
      return nil
    end)
    if not ok then
      kumo.log_error('suppression: redis check failed: ' .. tostring(hit))
      return nil   -- fail-open: don't block legit mail on a Redis hiccup
    end
    return hit
  end
  is_suppressed = kumo.memoize(_check, {
    name = 'suppression-check',
    ttl = '15s',
    capacity = 100000,
  })
end

`)
}

// --- the routing chain ------------------------------------------------------
//
// Both the SMTP server (smtp_server_message_received) and the HTTP injection
// API (http_message_generated) dispatch into the same Lua function so policy
// decisions stay consistent across both entry points.
func writeRoutingChain(b *strings.Builder, mcs []MailClass, rs []RoutingRule, gs GlobalSettings, whs []MailWebhook, opts RenderOptions) {
	header := gs.MailClassHeader
	if header == "" {
		header = MailClassHeaderDefault
	}

	b.WriteString("-- ===== routing chain (suppression → mail class → routing rules → DKIM) =====\n")

	// Header hygiene: submission/injection paths often omit Date and
	// Message-ID, which receivers' rspamd penalizes (MISSING_DATE,
	// MISSING_MID). Add them only when absent so relayed mail that already
	// carries them is untouched. Runs at reception (route_message is hooked
	// on both smtp_server_message_received and http_message_generated), so
	// the headers exist before the outbound DKIM signer runs and are
	// covered by the signature. The Message-ID domain is the configured
	// egress EHLO FQDN when set, else the envelope-sender domain.
	fmt.Fprintf(b, "local IRIS_MID_DOMAIN = %s\n", MustLuaString(strings.TrimSpace(gs.EgressEhloDomain)))
	b.WriteString(`local function iris_add_missing_headers(msg)
  if (msg:get_first_named_header_value('Date') or '') == '' then
    -- pcall so an unexpected os.date failure degrades to "no Date added"
    -- rather than failing the message.
    local ok, d = pcall(os.date, '!%a, %d %b %Y %H:%M:%S +0000')
    if ok and d and d ~= '' then
      msg:prepend_header('Date', d)
    end
  end
  if (msg:get_first_named_header_value('Message-ID') or '') == '' then
    local dom = IRIS_MID_DOMAIN
    if dom == '' then
      local s = msg:sender()
      dom = (s and s.domain) or 'localhost'
    end
    msg:prepend_header('Message-ID', string.format('<%s@%s>', msg:id(), dom))
  end
end

`)

	b.WriteString("local function route_message(msg)\n")
	if opts.DryRun {
		b.WriteString("  print('[DRY-RUN] route_message')\n")
	}
	b.WriteString("  iris_add_missing_headers(msg)\n")

	// 0) inbound DSN catcher. Mail arriving at any of our configured bounce
	// domains is funneled straight into the DSN_TRACKER queue (custom_lua →
	// XADD onto Redis) and skips the rest of the chain. We do this before
	// suppression because a suppression match would fire kumo.reject(550),
	// which would itself trigger another DSN — a loop. The lookup is a Lua
	// set so multi-domain mode (one entry per sender's bounce subdomain)
	// stays O(1).
	if bouncePipelineEnabled(gs) {
		b.WriteString(`  do
    local rcpt = msg:recipient()
    local rdom = (rcpt and rcpt.domain or ''):lower()
    if BOUNCE_DOMAINS[rdom] then
      msg:set_meta('queue', DSN_TRACKER)
      return
    end
  end
`)
	}

	// 0b) inbound webhook catcher. Mail addressed to a configured webhook
	// recipient (exact email or a bare-domain catch-all) is routed straight
	// to the WEBHOOK_TRACKER queue, which POSTs it to the endpoint. Checked
	// before suppression for the same loop-avoidance reason as DSNs.
	if len(enabledWebhooks(whs)) > 0 {
		b.WriteString(`  do
    local rcpt = msg:recipient()
    local email = (rcpt and rcpt.email or ''):lower()
    local rdom = (rcpt and rcpt.domain or ''):lower()
    if WEBHOOK_BY_EMAIL[email] or WEBHOOK_BY_DOMAIN[rdom] then
      msg:set_meta('queue', WEBHOOK_TRACKER)
      return
    end
  end
`)
	}

	// 1) suppression check via the memoized Redis lookup. is_suppressed is
	// declared higher in the file (writeSuppressionLookup); it returns
	// 'addr' / 'dom' on a hit, nil otherwise. No-Redis deployments get a
	// stub that always returns nil — the suppression list is opt-in.
	b.WriteString(`  do
    local rcpt = ((msg:recipient() and msg:recipient().email) or ''):lower()
    local rdom = ((msg:recipient() and msg:recipient().domain) or ''):lower()
    if is_suppressed(rcpt, rdom) then
      kumo.reject(550, 'recipient is on the suppression list')
      return
    end
  end
`)

	// 2) mail class header lookup. The class NAME becomes the tenant, so
	// kumomta's queue grouping (visible in /v1/queues) buckets one row per
	// class — `<classname>@<domain>` — instead of collapsing everything by
	// egress pool. The pool itself is recovered in get_queue_config via the
	// parallel CLASS_TO_POOL lookup. mailclass meta is also set so the log
	// hook indexes it for the Logs UI search.
	if len(mcs) > 0 {
		fmt.Fprintf(b, `  do
    local v = msg:get_first_named_header_value(%s)
    if v and v ~= '' then
      local hit = MAIL_CLASSES[v]
      if hit then
        msg:set_meta('mailclass', v)
        msg:set_meta('tenant', v)
        return
      end
    end
  end
`, MustLuaString(header))
	}

	// 3) routing rules in (priority asc, name asc) order.
	cp := append([]RoutingRule(nil), rs...)
	sort.Slice(cp, func(i, j int) bool {
		if cp[i].Priority != cp[j].Priority {
			return cp[i].Priority < cp[j].Priority
		}
		return cp[i].Name < cp[j].Name
	})
	for _, r := range cp {
		if !r.Enabled {
			continue
		}
		fmt.Fprintf(b, "  -- rule: %s (priority=%d)\n", sanitizeComment(r.Name), r.Priority)
		b.WriteString("  if (function()\n")
		for _, c := range r.Conditions {
			b.WriteString("    if not (")
			b.WriteString(emitCondition(c))
			b.WriteString(") then return false end\n")
		}
		b.WriteString("    return true\n  end)() then\n")
		b.WriteString(emitTarget(r.Target, opts))
		b.WriteString("  end\n")
	}

	// Fallthrough: nothing classified or routed this message. Force
	// tenant='default' so it lands in a single 'default@<domain>' queue
	// instead of inheriting whatever stale tenant kumomta might infer.
	// mailclass is left blank — the Logs UI shows '—' for unclassified rows.
	b.WriteString(`  if not msg:get_meta('tenant') or msg:get_meta('tenant') == '' then
    msg:set_meta('tenant', 'default')
  end
`)

	// One-queue-per-VMTA: collapse the queue key to the resolved egress pool
	// name. Resolution mirrors get_queue_config so the two stay in sync —
	// tenant → CLASS_TO_POOL → tenant-as-pool → 'default'. Kumomta sees a
	// single-segment queue and calls get_queue_config with tenant=nil, which
	// the renderer's queue-config block already handles.
	if gs.QueuePerVmta {
		b.WriteString(`  do
    local t = msg:get_meta('tenant') or ''
    local p = CLASS_TO_POOL[t]
    if not p or p == '' then p = t end
    if not p or p == '' then p = 'default' end
    msg:set_meta('queue', p)
  end
`)
	}

	b.WriteString("end\n\n")

	// Hook routing into both the SMTP and HTTP entry points. KumoMTA allows
	// only one handler per event, so any inbound-only pre-processing (rspamd
	// scan) is invoked from inside the single SMTP handler, before routing,
	// rather than as a second kumo.on(...). A scan that rejects/defers raises
	// and unwinds before route_message runs. The HTTP path never scans
	// (API-injected mail is not inbound).
	if rspamdEnabled(gs) {
		b.WriteString(`kumo.on('smtp_server_message_received', function(msg) iris_rspamd_scan(msg) route_message(msg) end)
kumo.on('http_message_generated',         function(msg) route_message(msg) end)

`)
	} else {
		b.WriteString(`kumo.on('smtp_server_message_received', function(msg) route_message(msg) end)
kumo.on('http_message_generated',         function(msg) route_message(msg) end)

`)
	}

	// DKIM signing + VERP rewrite. Both run at outbound dispatch and need to
	// share a hook because (a) kumomta runs handlers in registration order
	// and we must DKIM-sign with the *original* envelope-sender domain
	// before VERP rewrites MAIL FROM, and (b) keeping them in one block
	// makes that ordering self-evident at review time.
	b.WriteString(`-- ===== DKIM signing + VERP rewrite (outbound) =====
kumo.on('smtp_client_message_sending', function(msg)
  local s = msg:sender()
  local d = s and s.domain or nil
  -- DKIM first: signing depends on the From-domain, which here is read
  -- from the envelope sender (set at injection from the SMTP MAIL FROM).
  -- Must finish before any rewrite that changes the envelope sender.
  if d and d ~= '' then
    local k = DKIM_BY_DOMAIN[d]
    if k then
      if k.algo == 'ed25519' then
        msg:dkim_sign(kumo.dkim.ed25519_signer { domain = d, selector = k.selector, key = k.key })
      else
        msg:dkim_sign(kumo.dkim.rsa_sha256_signer { domain = d, selector = k.selector, key = k.key })
      end
    end
  end
`)
	if bouncePipelineEnabled(gs) {
		// VERP MAIL FROM rewrite. Token format matches pkg/verp.Encode
		// (hex16 of HMAC-SHA256(secret, msgid), then "." then msgid). The
		// per-sender bounce domain comes from BOUNCE_SENDER_TO_BOUNCE so
		// DMARC's relaxed alignment holds against the From: domain;
		// senders not in the map fall back to BOUNCE_DOMAIN_FALLBACK
		// (legacy single-domain mode); senders matching neither are left
		// unrewritten — better than producing an unaligned MAIL FROM for
		// a domain we don't host.
		//
		// Skip when sender is empty (DSN passthrough, per RFC 3464: DSNs
		// themselves carry MAIL FROM:<>) — VERPing those would create a
		// self-addressed bounce loop.
		b.WriteString(`  do
    local from_addr = (s and s.email) or ''
    local from_dom = (s and s.domain or ''):lower()
    if from_addr ~= '' then
      local bounce_dom = BOUNCE_SENDER_TO_BOUNCE[from_dom]
      if not bounce_dom or bounce_dom == '' then
        bounce_dom = BOUNCE_DOMAIN_FALLBACK
      end
      if bounce_dom and bounce_dom ~= '' then
        local mid = msg:id()
        if mid and mid ~= '' then
          local mac = kumo.digest.hmac_sha256({ key_data = BOUNCE_VERP_SECRET }, mid)
          local prefix = string.sub(tostring(mac), 1, 16)
          msg:set_sender(string.format('b+%s.%s@%s', prefix, mid, bounce_dom))
        end
      end
    end
  end
`)
	}
	b.WriteString(`end)

`)
}

// --- emit one routing-rule condition or target -----------------------------

// emitCondition produces a Lua boolean expression for a single condition.
// Both `field` and `op` are pre-validated against allow-lists upstream.
func emitCondition(c RuleCondition) string {
	var subj string
	switch c.Field {
	case "from":
		subj = "((msg:sender() and msg:sender().email) or ''):lower()"
	case "from_domain":
		subj = "((msg:sender() and msg:sender().domain) or ''):lower()"
	case "to":
		subj = "((msg:recipient() and msg:recipient().email) or ''):lower()"
	case "to_domain":
		subj = "((msg:recipient() and msg:recipient().domain) or ''):lower()"
	case "header.subject":
		subj = "(msg:get_first_named_header_value('subject') or '')"
	case "source_ip":
		// kumomta exposes the peer address via the message's received_from
		// meta; tostring() makes the comparison string-safe.
		subj = "(msg:get_meta('received_from') or '')"
	default:
		return "false"
	}
	val := MustLuaString(strings.ToLower(c.Value))
	switch c.Op {
	case "equals":
		return fmt.Sprintf("(%s == %s)", subj, val)
	case "contains":
		return fmt.Sprintf("(string.find(%s, %s, 1, true) ~= nil)", subj, val)
	case "startswith":
		return fmt.Sprintf("(%s:sub(1, #%s) == %s)", subj, val, val)
	case "endswith":
		return fmt.Sprintf("(%s:sub(-#%s) == %s)", subj, val, val)
	case "regex":
		// Lua patterns are not full regex; we still validated the value as a
		// Go-RE2 pattern upstream so authors got early feedback. The runtime
		// match here uses string.find with the value as a Lua pattern, which
		// covers the simple cases authors typically write.
		return fmt.Sprintf("(string.find(%s, %s) ~= nil)", subj, val)
	}
	return "false"
}

// emitTarget produces the Lua statement(s) executed when a rule matches. The
// dry-run prefix is interleaved with the real action so operators see both
// the intent and the effect in the kumomta log.
func emitTarget(t RuleTarget, opts RenderOptions) string {
	dry := ""
	if opts.DryRun {
		dry = "    print('[DRY-RUN] target=" + sanitizeComment(t.Kind) + "/" + sanitizeComment(t.Ref) + "')\n"
	}
	switch t.Kind {
	case "vmta", "vmta_group":
		// Both kinds resolve through the same POOLS table; tenant=pool_name.
		return dry + fmt.Sprintf("    msg:set_meta('tenant', %s)\n    return\n", MustLuaString(t.Ref))
	case "queue":
		// Direct queue override — bypasses the tenant→pool indirection.
		return dry + fmt.Sprintf("    msg:set_meta('queue', %s)\n    return\n", MustLuaString(t.Ref))
	case "reject":
		text := t.RejectText
		if text == "" {
			text = "rejected by routing rule"
		}
		return dry + fmt.Sprintf("    kumo.reject(%d, %s)\n    return\n", t.RejectCode, MustLuaString(text))
	case "discard":
		// Ack with 250 OK so the sender sees success, but route to the null
		// queue which kumomta treats as "drop on the floor". Operators who
		// want a hard reject should use `reject` instead.
		return dry + "    kumo.reject(250, 'discarded by policy')\n    return\n"
	}
	return ""
}

// --- footer -----------------------------------------------------------------

func writeFooter(b *strings.Builder, opts RenderOptions) {
	b.WriteString("\n-- end of generated policy\n")
}

// --- helpers (kept so tests + other writers reuse them) --------------------

// sanitizeComment strips control bytes so a malicious comment cannot
// terminate the comment context. Lua "--" comments end at end-of-line, so
// the only real risk is newline injection.
func sanitizeComment(s string) string {
	if s == "" {
		return ""
	}
	r := strings.NewReplacer("\n", " ", "\r", " ", "\x00", "")
	return r.Replace(s)
}

// toIdent converts a name into a safe Lua identifier; falls back to "x".
// Retained for backward compatibility with callers outside this file.
func toIdent(s string) string {
	if s == "" {
		return "x"
	}
	var b strings.Builder
	b.Grow(len(s) + 1)
	if c := s[0]; !((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || c == '_') {
		b.WriteByte('_')
	}
	for i := 0; i < len(s); i++ {
		c := s[i]
		switch {
		case (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || c == '_':
			b.WriteByte(c)
		case c >= '0' && c <= '9':
			b.WriteByte(c)
		default:
			b.WriteByte('_')
		}
	}
	return b.String()
}
