// Code generated by ent, DO NOT EDIT.

package mailclass

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the mailclass type in the database.
	Label = "mail_class"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldHeaderName holds the string denoting the header_name field in the database.
	FieldHeaderName = "header_name"
	// FieldHeaderValue holds the string denoting the header_value field in the database.
	FieldHeaderValue = "header_value"
	// FieldTargetKind holds the string denoting the target_kind field in the database.
	FieldTargetKind = "target_kind"
	// FieldTargetRef holds the string denoting the target_ref field in the database.
	FieldTargetRef = "target_ref"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the mailclass in the database.
	Table = "mail_classes"
)

// Columns holds all SQL columns for mailclass fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldDescription,
	FieldEnabled,
	FieldHeaderName,
	FieldHeaderValue,
	FieldTargetKind,
	FieldTargetRef,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	DescriptionValidator func(string) error
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// HeaderNameValidator is a validator for the "header_name" field. It is called by the builders before save.
	HeaderNameValidator func(string) error
	// HeaderValueValidator is a validator for the "header_value" field. It is called by the builders before save.
	HeaderValueValidator func(string) error
	// TargetKindValidator is a validator for the "target_kind" field. It is called by the builders before save.
	TargetKindValidator func(string) error
	// TargetRefValidator is a validator for the "target_ref" field. It is called by the builders before save.
	TargetRefValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the MailClass queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByHeaderName orders the results by the header_name field.
func ByHeaderName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHeaderName, opts...).ToFunc()
}

// ByHeaderValue orders the results by the header_value field.
func ByHeaderValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHeaderValue, opts...).ToFunc()
}

// ByTargetKind orders the results by the target_kind field.
func ByTargetKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTargetKind, opts...).ToFunc()
}

// ByTargetRef orders the results by the target_ref field.
func ByTargetRef(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTargetRef, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
